/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assessmentfeedbacksystem.GUI;

import assessmentfeedbacksystem.AdminStaff;
import assessmentfeedbacksystem.GUI.AdminStaff.AdminDashboardFrame;
import assessmentfeedbacksystem.GUI.AcademicLeader.AcademicLeaderMainFrame;
import assessmentfeedbacksystem.AcademicLeader;
import assessmentfeedbacksystem.GUI.Lecturer.MainFrame;
import assessmentfeedbacksystem.GUI.Student.StudentMainFrame;
import assessmentfeedbacksystem.Grade;
import assessmentfeedbacksystem.Lecturer;
import assessmentfeedbacksystem.Student;
import assessmentfeedbacksystem.User;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;

/**
 *
 * @author samanthawoo
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        id_field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        login_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        password_field = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(940, 600));
        setMinimumSize(new java.awt.Dimension(940, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(940, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setMaximumSize(new java.awt.Dimension(470, 600));
        jPanel5.setMinimumSize(new java.awt.Dimension(470, 600));
        jPanel5.setPreferredSize(new java.awt.Dimension(470, 600));
        java.awt.GridBagLayout jPanel5Layout = new java.awt.GridBagLayout();
        jPanel5Layout.columnWidths = new int[] {0};
        jPanel5Layout.rowHeights = new int[] {0, 15, 0, 15, 0};
        jPanel5.setLayout(jPanel5Layout);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 58, 138));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Assessment Feedback System");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel5.add(jLabel3, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 58, 138));
        jLabel5.setText("Track • Evaluate • Improve");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel5.add(jLabel5, gridBagConstraints);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/LoginLogo.jpg"))); // NOI18N
        jLabel6.setToolTipText("");
        jPanel5.add(jLabel6, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel5);

        jPanel1.setBackground(new java.awt.Color(237, 241, 246));
        jPanel1.setMaximumSize(new java.awt.Dimension(470, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(470, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(470, 600));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0};
        jPanel1Layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel1.setLayout(jPanel1Layout);

        id_field.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        id_field.setToolTipText("");
        id_field.setMaximumSize(new java.awt.Dimension(320, 35));
        id_field.setMinimumSize(new java.awt.Dimension(320, 35));
        id_field.setPreferredSize(new java.awt.Dimension(320, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(id_field, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("User ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Login");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 20, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        login_button.setBackground(new java.awt.Color(30, 58, 138));
        login_button.setForeground(new java.awt.Color(255, 255, 255));
        login_button.setText("Login");
        login_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 58, 138), 1, true));
        login_button.setContentAreaFilled(false);
        login_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_button.setFocusPainted(false);
        login_button.setFocusable(false);
        login_button.setMaximumSize(new java.awt.Dimension(320, 40));
        login_button.setMinimumSize(new java.awt.Dimension(320, 40));
        login_button.setOpaque(true);
        login_button.setPreferredSize(new java.awt.Dimension(320, 40));
        login_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_buttonMouseExited(evt);
            }
        });
        login_button.addActionListener(this::login_buttonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 40, 0);
        jPanel1.add(login_button, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jLabel2, gridBagConstraints);

        password_field.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        password_field.setMaximumSize(new java.awt.Dimension(320, 35));
        password_field.setMinimumSize(new java.awt.Dimension(320, 35));
        password_field.setPreferredSize(new java.awt.Dimension(320, 35));
        password_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                password_fieldKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(password_field, gridBagConstraints);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        String id_input = id_field.getText().trim();
        char[] hash_password_input = password_field.getPassword();
        String password_input = new String(hash_password_input);
        
        // Validation and verification
        if(id_input.isEmpty() || password_input.isEmpty()){
            JOptionPane.showMessageDialog(this, "ID and password cannot be empty.", "Invalid Input", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // call user login function
        User logged_in_user = User.login(id_input, password_input);
        
        // if login successs
        if(logged_in_user != null){
            String role = logged_in_user.getRole();
            if(role.equals("Admin Staff")){
                AdminStaff admin = (AdminStaff) logged_in_user;
                AdminDashboardFrame admin_dashboard = new AdminDashboardFrame(admin);
                admin_dashboard.setVisible(true);
                this.dispose();
            }else if(role.equals("Academic Leader")){
                AcademicLeader al = (AcademicLeader) logged_in_user;
                AcademicLeaderMainFrame al_mainframe = new AcademicLeaderMainFrame(al);
                al_mainframe.setVisible(true);
                this.dispose();
            }else if(role.equals("Lecturer")){
                Lecturer lecturer = (Lecturer) logged_in_user;
                MainFrame lecturer_mainFrame = new MainFrame(lecturer);
                lecturer_mainFrame.setVisible(true);
                this.dispose();
            } else if(role.equals("Student")) {
                Student student = (Student) logged_in_user; new Grade().initializeGrade();
                assessmentfeedbacksystem.NotificationService.createWelcomeNotification(id_input);

                StudentMainFrame student_dashboard = new StudentMainFrame(id_input);
                student_dashboard.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Role not recognized.");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Invalid ID or password.", "Invalid Input", JOptionPane.WARNING_MESSAGE);
        }
        id_field.setText("");
        password_field.setText("");
    }//GEN-LAST:event_login_buttonActionPerformed

    private void password_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_fieldKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            login_buttonActionPerformed(null);
        }
    }//GEN-LAST:event_password_fieldKeyPressed

    private void login_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_buttonMouseEntered
        login_button.setBackground(new java.awt.Color(59, 91, 179));
    }//GEN-LAST:event_login_buttonMouseEntered

    private void login_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_buttonMouseExited
        login_button.setBackground(new java.awt.Color(30, 58, 138));
    }//GEN-LAST:event_login_buttonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        new Grade().initializeGrade();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton login_button;
    private javax.swing.JPasswordField password_field;
    // End of variables declaration//GEN-END:variables
}   
