/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assessmentfeedbacksystem.GUI.AcademicLeader;

import assessmentfeedbacksystem.AcademicLeader;
import java.awt.BorderLayout;
import java.awt.CardLayout;

/**
 *
 * @author samanthawoo
 */

public class AcademicLeaderMainFrame extends javax.swing.JFrame {
    
    private AcademicLeader logged_in_al;
    
    public AcademicLeaderMainFrame(AcademicLeader al) {
        this.logged_in_al = al;
        initComponents();
        setLocationRelativeTo(null);
        
        TopBar topBar = new TopBar();
        topBarContainer.removeAll();
        topBarContainer.add(topBar, BorderLayout.CENTER);

        SideNavBar sideBar = new SideNavBar(this);
        sideBarContainer.removeAll();
        sideBarContainer.add(sideBar, BorderLayout.CENTER);

        topBarContainer.revalidate();
        sideBarContainer.revalidate();

        showPage("DASHBOARD");
    }
    
    public void showPage(String page) {
        CardLayout cl = (CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, page);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topBarContainer = new javax.swing.JPanel();
        sideBarContainer = new javax.swing.JPanel();
        contentPanel = new javax.swing.JPanel();
        moduleManagementPanel1 = new assessmentfeedbacksystem.GUI.AcademicLeader.ModuleManagementPanel(logged_in_al);
        reportManagementPanel1 = new assessmentfeedbacksystem.GUI.AcademicLeader.ReportManagementPanel(logged_in_al);
        dashboardPanel1 = new assessmentfeedbacksystem.GUI.AcademicLeader.DashboardPanel(this, logged_in_al);
        profileContainerPanel1 = new assessmentfeedbacksystem.GUI.AcademicLeader.ProfileContainerPanel(logged_in_al);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(940, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(940, 600));

        topBarContainer.setPreferredSize(new java.awt.Dimension(0, 60));
        topBarContainer.setRequestFocusEnabled(false);
        topBarContainer.setLayout(new java.awt.BorderLayout());
        getContentPane().add(topBarContainer, java.awt.BorderLayout.PAGE_START);

        sideBarContainer.setPreferredSize(new java.awt.Dimension(170, 0));
        sideBarContainer.setLayout(new java.awt.BorderLayout());
        getContentPane().add(sideBarContainer, java.awt.BorderLayout.LINE_START);

        contentPanel.setLayout(new java.awt.CardLayout());
        contentPanel.add(moduleManagementPanel1, "MODULE");
        contentPanel.add(reportManagementPanel1, "REPORT");
        contentPanel.add(dashboardPanel1, "DASHBOARD");
        contentPanel.add(profileContainerPanel1, "PROFILE");

        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
//    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AcademicLeaderMainFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private assessmentfeedbacksystem.GUI.AcademicLeader.DashboardPanel dashboardPanel1;
    private assessmentfeedbacksystem.GUI.AcademicLeader.ModuleManagementPanel moduleManagementPanel1;
    private assessmentfeedbacksystem.GUI.AcademicLeader.ProfileContainerPanel profileContainerPanel1;
    private assessmentfeedbacksystem.GUI.AcademicLeader.ReportManagementPanel reportManagementPanel1;
    private javax.swing.JPanel sideBarContainer;
    private javax.swing.JPanel topBarContainer;
    // End of variables declaration//GEN-END:variables
}
