/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.AcademicLeader;

import javax.swing.table.DefaultTableModel;
import assessmentfeedbacksystem.Module;
import assessmentfeedbacksystem.Lecturer;
import assessmentfeedbacksystem.ClassModel;
import assessmentfeedbacksystem.AcademicLeader;

/**
 *
 * @author xinyun
 */

public class ActiveModuleTablePanel extends javax.swing.JPanel {

    private ActiveModuleContainerPanel parent;
    private AcademicLeader logged_in_al;
    
    /**
     * Creates new form ActiveModuleTablePanel
     */
    
    public ActiveModuleTablePanel() {
        initComponents();
    }
    
    public ActiveModuleTablePanel(ActiveModuleContainerPanel parent, AcademicLeader logged_in_al) {
        this.parent = parent;
        this.logged_in_al = logged_in_al;
        initComponents();
        applyStatusRenderer();
        loadActiveModules();
    }
    
    private void applyStatusRenderer() {
        tblActiveModules.getColumnModel()
            .getColumn(4)
            .setCellRenderer(new StatusBadgeRenderer());
    }
    
    private void loadActiveModules() {
        DefaultTableModel model = (DefaultTableModel) tblActiveModules.getModel();
        model.setRowCount(0);
        
        if (logged_in_al == null) {
            return;
        }

        for (Module m : Module.getActiveModules()) {
            
            if (!m.getCreatedBy().equals(logged_in_al.getUser_id())) {
                continue;
            }           
            
            model.addRow(new Object[]{
                m.getModuleId(),
                m.getModuleCode(),
                m.getModuleName(),
                Lecturer.getLecturerNameById(m.getLecturer().getUser_id()),
                ClassModel.getClassByModuleId(m.getModuleId()) != null ? "Active" : "Waiting for Class"
            });
        }
    }
    
    public void reloadActiveTable() {
        DefaultTableModel model = (DefaultTableModel) tblActiveModules.getModel();
        model.setRowCount(0);
        
        if (logged_in_al == null) {
            return;
        }

        for (Module m : Module.getActiveModules()) {
            
            if (!m.getCreatedBy().equals(logged_in_al.getUser_id())) {
                continue;
            }
            
            model.addRow(new Object[]{
                m.getModuleId(),
                m.getModuleCode(),
                m.getModuleName(),
                Lecturer.getLecturerNameById(m.getLecturer().getUser_id()),
                ClassModel.getClassByModuleId(m.getModuleId()) != null ? "Active" : "Waiting for Class"
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblActiveModules = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnAddModule = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 15, 20));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 15));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel1.setText("Active Modules");
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        tblActiveModules.setAutoCreateRowSorter(true);
        tblActiveModules.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "moduleId", "Module Code", "Module Name", "Lecturer", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblActiveModules.setFillsViewportHeight(true);
        tblActiveModules.setFocusable(false);
        tblActiveModules.setRowHeight(35);
        tblActiveModules.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblActiveModules.setShowGrid(false);
        tblActiveModules.getTableHeader().setReorderingAllowed(false);
        tblActiveModules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblActiveModulesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblActiveModules);
        if (tblActiveModules.getColumnModel().getColumnCount() > 0) {
            tblActiveModules.getColumnModel().getColumn(0).setMinWidth(0);
            tblActiveModules.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblActiveModules.getColumnModel().getColumn(0).setMaxWidth(0);
            tblActiveModules.getColumnModel().getColumn(1).setPreferredWidth(110);
            tblActiveModules.getColumnModel().getColumn(2).setPreferredWidth(300);
            tblActiveModules.getColumnModel().getColumn(3).setPreferredWidth(215);
            tblActiveModules.getColumnModel().getColumn(4).setPreferredWidth(160);
        }

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 5));

        btnAddModule.setBackground(new java.awt.Color(45, 94, 168));
        btnAddModule.setForeground(new java.awt.Color(255, 255, 255));
        btnAddModule.setText("+ Add Module");
        btnAddModule.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddModule.setFocusable(false);
        btnAddModule.setPreferredSize(new java.awt.Dimension(117, 30));
        btnAddModule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddModuleMouseClicked(evt);
            }
        });
        jPanel2.add(btnAddModule);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void tblActiveModulesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblActiveModulesMouseClicked
        // TODO add your handling code here:
        if (parent == null) {
            return;
        }
        
        int row = tblActiveModules.getSelectedRow();
        if (row < 0) {
            return;
        }

        String moduleId = tblActiveModules.getValueAt(row, 0).toString();

        for (Module m : Module.getActiveModules()) { 
            if (m.getModuleId().equals(moduleId)) {
                parent.showDetail(m);
                break;
            }
        }
    }//GEN-LAST:event_tblActiveModulesMouseClicked

    private void btnAddModuleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddModuleMouseClicked
        // TODO add your handling code here:
        if (parent != null) {
            parent.showAddForm();
        }
    }//GEN-LAST:event_btnAddModuleMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddModule;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblActiveModules;
    // End of variables declaration//GEN-END:variables
}
