/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.AcademicLeader;

import java.awt.CardLayout;
import assessmentfeedbacksystem.Module;
import assessmentfeedbacksystem.AcademicLeader;

/**
 *
 * @author xinyun
 */

public class ActiveModuleContainerPanel extends javax.swing.JPanel {

    private CardLayout cardLayout;
    private ActiveModuleTablePanel tablePanel;
    private ActiveModuleDetailPanel detailPanel;
    private AcademicLeader logged_in_user;
    private AddModulePanel addPanel;
    private EditModulePanel editPanel;
    
    /**
     * Creates new form ActiveModuleContainerPanel
     */
    
    public ActiveModuleContainerPanel(){
        initComponents();

    }
    
    public ActiveModuleContainerPanel(AcademicLeader logged_in_al) {
        this.logged_in_user = logged_in_al;
        initComponents();
        setupCards();
    }
    
    private void setupCards() {
        cardLayout = (CardLayout) getLayout();

        tablePanel = new ActiveModuleTablePanel(this, logged_in_user);
        detailPanel = new ActiveModuleDetailPanel(this, logged_in_user);
        addPanel = new AddModulePanel(this, logged_in_user);
        editPanel = new EditModulePanel(this, logged_in_user);

        add(tablePanel, "TABLE");
        add(detailPanel, "DETAIL");
        add(addPanel, "ADD");
        add(editPanel, "EDIT");

        showTable();
    }
    
    public void showTable() {
        tablePanel.reloadActiveTable();
        cardLayout.show(this, "TABLE");
    }

    public void showDetail(Module module) {
        detailPanel.setModule(module);
        tablePanel.reloadActiveTable(); 
        cardLayout.show(this, "DETAIL");
    }
    
    public void showAddForm() {
        addPanel.resetForm();
        cardLayout.show(this, "ADD");
    }
    
    public void showEdit(Module module) {
        editPanel.setModule(module);
        cardLayout.show(this, "EDIT");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTableCard = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        activeModuleTablePanel1 = new assessmentfeedbacksystem.GUI.AcademicLeader.ActiveModuleTablePanel(this, logged_in_user);
        pnlDetailCard = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        activeModuleDetailPanel1 = new assessmentfeedbacksystem.GUI.AcademicLeader.ActiveModuleDetailPanel(this, logged_in_user);
        pnlAddModuleCard = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        addModulePanel1 = new assessmentfeedbacksystem.GUI.AcademicLeader.AddModulePanel(this, logged_in_user);
        pnlEditModuleCard = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        editModulePanel1 = new assessmentfeedbacksystem.GUI.AcademicLeader.EditModulePanel(this, logged_in_user);

        setBackground(new java.awt.Color(237, 241, 246));
        setLayout(new java.awt.CardLayout());

        pnlTableCard.setBackground(new java.awt.Color(255, 255, 255));
        pnlTableCard.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(activeModuleTablePanel1, java.awt.BorderLayout.CENTER);

        pnlTableCard.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(pnlTableCard, "TABLE");

        pnlDetailCard.setBackground(new java.awt.Color(255, 255, 255));
        pnlDetailCard.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel3.add(activeModuleDetailPanel1, java.awt.BorderLayout.CENTER);

        pnlDetailCard.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        add(pnlDetailCard, "DETAIL");

        pnlAddModuleCard.setBackground(new java.awt.Color(255, 255, 255));
        pnlAddModuleCard.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(addModulePanel1, java.awt.BorderLayout.CENTER);

        pnlAddModuleCard.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(pnlAddModuleCard, "ADD");

        pnlEditModuleCard.setBackground(new java.awt.Color(255, 255, 255));
        pnlEditModuleCard.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());
        jPanel4.add(editModulePanel1, java.awt.BorderLayout.CENTER);

        pnlEditModuleCard.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(pnlEditModuleCard, "EDIT");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private assessmentfeedbacksystem.GUI.AcademicLeader.ActiveModuleDetailPanel activeModuleDetailPanel1;
    private assessmentfeedbacksystem.GUI.AcademicLeader.ActiveModuleTablePanel activeModuleTablePanel1;
    private assessmentfeedbacksystem.GUI.AcademicLeader.AddModulePanel addModulePanel1;
    private assessmentfeedbacksystem.GUI.AcademicLeader.EditModulePanel editModulePanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel pnlAddModuleCard;
    private javax.swing.JPanel pnlDetailCard;
    private javax.swing.JPanel pnlEditModuleCard;
    private javax.swing.JPanel pnlTableCard;
    // End of variables declaration//GEN-END:variables
}
