/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.AcademicLeader;

import assessmentfeedbacksystem.AcademicLeader;
import assessmentfeedbacksystem.Module;
import assessmentfeedbacksystem.Lecturer;
import assessmentfeedbacksystem.ClassModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author xinyun
 */

public class ActiveModuleDetailPanel extends javax.swing.JPanel {
    
    private ActiveModuleContainerPanel parent;
    private AcademicLeader logged_in_user;
    private Module currentModule;
    private boolean deleteMode; 
    
    /**
     * Creates new form ActiveModuleDetailPanel
     */
    
    public ActiveModuleDetailPanel() {
        initComponents();
    }
    
    public ActiveModuleDetailPanel(ActiveModuleContainerPanel parent, AcademicLeader logged_in_user) {
        this.parent = parent;
        this.logged_in_user = logged_in_user;
        initComponents();
    }
    
    public void setModule(Module m) {
        this.currentModule = m;
        
        lblModuleCodeValue.setText(m.getModuleCode());
        lblModuleNameValue.setText(m.getModuleName());
        lblCreditHourValue.setText(String.valueOf(m.getCreditHour()));
        lblLecturerValue.setText(Lecturer.getLecturerNameById(m.getLecturer().getUser_id()));
        
        ClassModel c = ClassModel.getClassByModuleId(m.getModuleId());
        
        if (c != null) {
            lblStudentCountValue.setText(String.valueOf(c.getNoOfStudentInClass(c.getClassId())));
            
            // button show "Deactivate" as text
            deleteMode = false;
            btnDeactivate.setText("Deactivate");
            btnDeactivate.setBackground(new java.awt.Color(255, 205, 210));
            btnDeactivate.setForeground(new java.awt.Color(183, 28, 28));
        
        } else {
            lblStudentCountValue.setText("0 (Waiting for class to be created)");
            
            // button show "Delete" as text
            deleteMode = true;
            btnDeactivate.setText("Delete");
            btnDeactivate.setBackground(new java.awt.Color(255, 205, 210));
            btnDeactivate.setForeground(new java.awt.Color(183, 28, 28));
        }
        
        lblDateValue.setText(m.getDateCreated().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        headerPanel = new javax.swing.JPanel();
        backPanel = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        titlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        detailContentPanel = new javax.swing.JPanel();
        lblModuleCode = new javax.swing.JLabel();
        lblModuleCodeValue = new javax.swing.JLabel();
        lblModuleName = new javax.swing.JLabel();
        lblModuleNameValue = new javax.swing.JLabel();
        lblCreditHour = new javax.swing.JLabel();
        lblCreditHourValue = new javax.swing.JLabel();
        lblLecturer = new javax.swing.JLabel();
        lblLecturerValue = new javax.swing.JLabel();
        lblStudentCount = new javax.swing.JLabel();
        lblStudentCountValue = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblDateValue = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        btnDeactivate = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20));
        setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setLayout(new java.awt.BorderLayout());

        backPanel.setBackground(new java.awt.Color(255, 255, 255));
        backPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0));

        btnClose.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnClose.setForeground(new java.awt.Color(120, 120, 120));
        btnClose.setText("x");
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setFocusable(false);
        btnClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        backPanel.add(btnClose);

        headerPanel.add(backPanel, java.awt.BorderLayout.CENTER);

        titlePanel.setBackground(new java.awt.Color(255, 255, 255));
        titlePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 9, 5));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel1.setText("Module Detail");
        titlePanel.add(jLabel1);

        headerPanel.add(titlePanel, java.awt.BorderLayout.SOUTH);

        add(headerPanel, java.awt.BorderLayout.PAGE_START);

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setLayout(new javax.swing.BoxLayout(bodyPanel, javax.swing.BoxLayout.Y_AXIS));

        detailContentPanel.setBackground(new java.awt.Color(255, 255, 255));
        detailContentPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 10, 0));
        detailContentPanel.setLayout(new java.awt.GridBagLayout());

        lblModuleCode.setForeground(new java.awt.Color(102, 102, 102));
        lblModuleCode.setText("Module Code");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblModuleCode, gridBagConstraints);

        lblModuleCodeValue.setBackground(new java.awt.Color(225, 236, 247));
        lblModuleCodeValue.setText("[Module Code Value]");
        lblModuleCodeValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblModuleCodeValue.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblModuleCodeValue, gridBagConstraints);

        lblModuleName.setForeground(new java.awt.Color(102, 102, 102));
        lblModuleName.setText("Module Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblModuleName, gridBagConstraints);

        lblModuleNameValue.setBackground(new java.awt.Color(225, 236, 247));
        lblModuleNameValue.setText("[Module Name Value]");
        lblModuleNameValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblModuleNameValue.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblModuleNameValue, gridBagConstraints);

        lblCreditHour.setForeground(new java.awt.Color(102, 102, 102));
        lblCreditHour.setText("Credit Hour");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblCreditHour, gridBagConstraints);

        lblCreditHourValue.setBackground(new java.awt.Color(225, 236, 247));
        lblCreditHourValue.setText("[Credit Hour Value]");
        lblCreditHourValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblCreditHourValue.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblCreditHourValue, gridBagConstraints);

        lblLecturer.setForeground(new java.awt.Color(102, 102, 102));
        lblLecturer.setText("Lecturer Assigned");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblLecturer, gridBagConstraints);

        lblLecturerValue.setBackground(new java.awt.Color(225, 236, 247));
        lblLecturerValue.setText("[Lecturer Assigned Value]");
        lblLecturerValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblLecturerValue.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblLecturerValue, gridBagConstraints);

        lblStudentCount.setForeground(new java.awt.Color(102, 102, 102));
        lblStudentCount.setText("Student Count");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblStudentCount, gridBagConstraints);

        lblStudentCountValue.setBackground(new java.awt.Color(225, 236, 247));
        lblStudentCountValue.setText("[Student Count Value]");
        lblStudentCountValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblStudentCountValue.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblStudentCountValue, gridBagConstraints);

        lblDate.setForeground(new java.awt.Color(102, 102, 102));
        lblDate.setText("Date Created");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblDate, gridBagConstraints);

        lblDateValue.setBackground(new java.awt.Color(225, 236, 247));
        lblDateValue.setText("[Date Created Value]");
        lblDateValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblDateValue.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblDateValue, gridBagConstraints);

        bodyPanel.add(detailContentPanel);

        buttonPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnDeactivate.setBackground(new java.awt.Color(255, 205, 210));
        btnDeactivate.setForeground(new java.awt.Color(183, 28, 28));
        btnDeactivate.setText("Deactivate");
        btnDeactivate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        btnDeactivate.setBorderPainted(false);
        btnDeactivate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeactivate.setFocusable(false);
        btnDeactivate.setPreferredSize(new java.awt.Dimension(94, 30));
        btnDeactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeactivateActionPerformed(evt);
            }
        });
        buttonPanel.add(btnDeactivate);

        btnEdit.setBackground(new java.awt.Color(45, 94, 168));
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.setFocusPainted(false);
        btnEdit.setFocusable(false);
        btnEdit.setPreferredSize(new java.awt.Dimension(72, 30));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        buttonPanel.add(btnEdit);

        bodyPanel.add(buttonPanel);

        add(bodyPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        if (parent != null) {
            parent.showTable();
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        // TODO add your handling code here:
        btnClose.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        // TODO add your handling code here:
        btnClose.setForeground(new java.awt.Color(120, 120, 120));
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnDeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeactivateActionPerformed
        // TODO add your handling code here:
        if (currentModule == null) {
            return;
        }

        String actionText = deleteMode ? "delete" : "deactivate";
        String actionTitle = deleteMode ? "Delete" : "Deactivate";

        int confirm = JOptionPane.showConfirmDialog(
            null,
            "Are you sure you want to " + actionText + " this module?\nThis action cannot be undone.",
            "Confirm " + actionTitle,
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return; 
        }

        boolean success;

        if (deleteMode) {
            success = Module.deleteModule(
                currentModule.getModuleId(),
                false
            );
        } else {
            success = Module.deactivateModule(
                currentModule.getModuleId(),
                true
            );
        }

        if (success) {
            JOptionPane.showMessageDialog(
                null,
                "Module successfully " + (deleteMode ? "deleted." : "deactivated."),
                "Success",
                JOptionPane.INFORMATION_MESSAGE
            );
            
            if (deleteMode) {
                parent.showTable();
            } else {
                ModuleManagementPanel parentPanel = (ModuleManagementPanel) SwingUtilities.getAncestorOfClass(ModuleManagementPanel.class, this);
                if (parentPanel != null) {
                    parentPanel.getTabMain().setSelectedComponent(parentPanel.getPnlInactive());
                    parentPanel.getInactiveModuleContainerPanel().showTable(); 
                }
            }
        } else {
            JOptionPane.showMessageDialog(
                null,
                "Operation failed. Please try again.",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnDeactivateActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (parent != null && currentModule != null) {
            parent.showEdit(currentModule);
        }
    }//GEN-LAST:event_btnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backPanel;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDeactivate;
    private javax.swing.JButton btnEdit;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel detailContentPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCreditHour;
    private javax.swing.JLabel lblCreditHourValue;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDateValue;
    private javax.swing.JLabel lblLecturer;
    private javax.swing.JLabel lblLecturerValue;
    private javax.swing.JLabel lblModuleCode;
    private javax.swing.JLabel lblModuleCodeValue;
    private javax.swing.JLabel lblModuleName;
    private javax.swing.JLabel lblModuleNameValue;
    private javax.swing.JLabel lblStudentCount;
    private javax.swing.JLabel lblStudentCountValue;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
