/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.AcademicLeader;

import assessmentfeedbacksystem.AcademicLeader;
import assessmentfeedbacksystem.Module;
import assessmentfeedbacksystem.FileManager;
import assessmentfeedbacksystem.Lecturer;
import javax.swing.JOptionPane;

/**
 *
 * @author xinyun
 */

public class AddModulePanel extends javax.swing.JPanel {
    
    private ActiveModuleContainerPanel parent;
    private AcademicLeader logged_in_al;

    /**
     * Creates new form AddModulePanel
     */
    
    public AddModulePanel() {
        initComponents();
    }
    
    public AddModulePanel(ActiveModuleContainerPanel parent, AcademicLeader logged_in_al) {
        this.parent = parent;
        this.logged_in_al = logged_in_al;
        initComponents();
        loadLecturers();
    }
    
    private void loadLecturers() {
        cmbLecturer.removeAllItems();

        for (String line : FileManager.readFile("User.txt")) {
            String[] data = line.split(";");
            if (data.length < 12) continue;

            if (data[7].equals("Lecturer") &&
                data[11].equals(logged_in_al.getUser_id())) {

                cmbLecturer.addItem(data[0] + " - " + data[1]);
            }
        }
    }
    
    private String generateNextModuleId() {
        int max = 0;
        for (Module m : Module.getAllModules()) {
            int num = Integer.parseInt(m.getModuleId().substring(1));
            max = Math.max(max, num);
        }
        return String.format("M%03d", max + 1);
    }
    
    public void resetForm() {
        txtModuleCode.setText("");
        txtModuleName.setText("");
        spnCreditHour.setValue(3.0);
        if (cmbLecturer.getItemCount() > 0) {
            cmbLecturer.setSelectedIndex(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        headerPanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        titlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        descPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        lblModuleCode = new javax.swing.JLabel();
        txtModuleCode = new javax.swing.JTextField();
        lblModuleName = new javax.swing.JLabel();
        txtModuleName = new javax.swing.JTextField();
        lblCreditHour = new javax.swing.JLabel();
        spnCreditHour = new javax.swing.JSpinner();
        lblLecturer = new javax.swing.JLabel();
        cmbLecturer = new javax.swing.JComboBox<>();
        submitPanel = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20));
        setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setLayout(new java.awt.BorderLayout());

        buttonPanel.setBackground(new java.awt.Color(255, 255, 255));
        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0));

        btnClose.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnClose.setForeground(new java.awt.Color(120, 120, 120));
        btnClose.setText("x");
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setFocusable(false);
        btnClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        buttonPanel.add(btnClose);

        headerPanel.add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        titlePanel.setBackground(new java.awt.Color(255, 255, 255));
        titlePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 9, 5));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel1.setText("Create Module");
        titlePanel.add(jLabel1);

        headerPanel.add(titlePanel, java.awt.BorderLayout.CENTER);

        descPanel.setBackground(new java.awt.Color(255, 255, 255));
        descPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 9, 2));

        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Please fill in this form to create a new module.");
        descPanel.add(jLabel2);

        headerPanel.add(descPanel, java.awt.BorderLayout.PAGE_END);

        add(headerPanel, java.awt.BorderLayout.PAGE_START);

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setLayout(new javax.swing.BoxLayout(bodyPanel, javax.swing.BoxLayout.Y_AXIS));

        formPanel.setBackground(new java.awt.Color(255, 255, 255));
        formPanel.setLayout(new java.awt.GridBagLayout());

        lblModuleCode.setForeground(new java.awt.Color(102, 102, 102));
        lblModuleCode.setText("Module Code");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblModuleCode, gridBagConstraints);

        txtModuleCode.setPreferredSize(new java.awt.Dimension(64, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 10);
        formPanel.add(txtModuleCode, gridBagConstraints);

        lblModuleName.setForeground(new java.awt.Color(102, 102, 102));
        lblModuleName.setText("Module Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblModuleName, gridBagConstraints);

        txtModuleName.setPreferredSize(new java.awt.Dimension(64, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 10);
        formPanel.add(txtModuleName, gridBagConstraints);

        lblCreditHour.setForeground(new java.awt.Color(102, 102, 102));
        lblCreditHour.setText("Credit Hour");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblCreditHour, gridBagConstraints);

        spnCreditHour.setModel(new javax.swing.SpinnerNumberModel(3.0d, 0.5d, 5.0d, 0.1d));
        spnCreditHour.setPreferredSize(new java.awt.Dimension(68, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 10);
        formPanel.add(spnCreditHour, gridBagConstraints);

        lblLecturer.setForeground(new java.awt.Color(102, 102, 102));
        lblLecturer.setText("Lecturer Assigned");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblLecturer, gridBagConstraints);

        cmbLecturer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbLecturer.setPreferredSize(new java.awt.Dimension(72, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 10);
        formPanel.add(cmbLecturer, gridBagConstraints);

        bodyPanel.add(formPanel);

        submitPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnCancel.setBackground(new java.awt.Color(232, 242, 255));
        btnCancel.setForeground(new java.awt.Color(45, 94, 168));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        btnCancel.setBorderPainted(false);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setFocusable(false);
        btnCancel.setPreferredSize(new java.awt.Dimension(72, 30));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        submitPanel.add(btnCancel);

        btnCreate.setBackground(new java.awt.Color(45, 94, 168));
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("Create Module");
        btnCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreate.setFocusable(false);
        btnCreate.setPreferredSize(new java.awt.Dimension(115, 30));
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        submitPanel.add(btnCreate);

        bodyPanel.add(submitPanel);

        add(bodyPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String moduleId = generateNextModuleId();
        String code = txtModuleCode.getText().trim();
        String name = txtModuleName.getText().trim();
        
        if (code.isEmpty() || name.isEmpty()) {
            JOptionPane.showMessageDialog(
                null,
                "Please fill in all required fields.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
            );
            return; 
        }

        double credit = ((Number) spnCreditHour.getValue()).doubleValue();
        String lecturerItem = cmbLecturer.getSelectedItem().toString();
        String lecturerId = lecturerItem.split(" - ")[0];    
        
        Module m = new Module(
            moduleId,
            code,
            name,
            credit,
            Lecturer.getLecturerById(lecturerId),
            "Active",
            logged_in_al.getUser_id(),
            java.time.LocalDate.now()
        );

        boolean success = Module.createModule(m);

        if (success) {
            JOptionPane.showMessageDialog(null, "Module created successfully.","Success",JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Failed to create module.","Error",JOptionPane.ERROR_MESSAGE);
        }

        parent.showTable();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        parent.showTable();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
        parent.showTable();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        // TODO add your handling code here:
        btnClose.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        // TODO add your handling code here:
        btnClose.setForeground(new java.awt.Color(120, 120, 120));
    }//GEN-LAST:event_btnCloseMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCreate;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JComboBox<String> cmbLecturer;
    private javax.swing.JPanel descPanel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCreditHour;
    private javax.swing.JLabel lblLecturer;
    private javax.swing.JLabel lblModuleCode;
    private javax.swing.JLabel lblModuleName;
    private javax.swing.JSpinner spnCreditHour;
    private javax.swing.JPanel submitPanel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField txtModuleCode;
    private javax.swing.JTextField txtModuleName;
    // End of variables declaration//GEN-END:variables
}
