/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.AcademicLeader;

import assessmentfeedbacksystem.AcademicLeader;
import assessmentfeedbacksystem.ClassEnrolmentReportService;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.chart.renderer.category.BarRenderer;
import javax.swing.BorderFactory;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.NumberTickUnit;
import org.jfree.chart.renderer.category.StandardBarPainter;

/**
 *
 * @author xinyun
 */
public class ClassEnrolmentBarChartPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClassEnrolmentBarChartPanel
     */
    public ClassEnrolmentBarChartPanel() {
        initComponents();
    }
    
    public void loadChart(AcademicLeader al) {

        DefaultCategoryDataset dataset =
            new DefaultCategoryDataset();

        for (Object[] row :ClassEnrolmentReportService.getClassEnrolmentChartData(al)) {
            String className = row[0].toString();
            int count = (int) row[1];

            dataset.addValue(
                count,
                "Enrolment",
                className
            );
        }

        JFreeChart chart = ChartFactory.createBarChart(
            "Class Enrolment",
            "Class Name",
            "Number of Enrolled Students",
            dataset,
            PlotOrientation.VERTICAL,
            false,
            true,
            false
        );

        chart.setBackgroundPaint(java.awt.Color.WHITE);

        var plot = chart.getCategoryPlot();
        plot.setBackgroundPaint(java.awt.Color.WHITE);
        plot.setRangeGridlinePaint(new java.awt.Color(220,220,220));
        plot.setRangeGridlineStroke(new java.awt.BasicStroke(0.8f));

        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setDrawBarOutline(false);
        renderer.setBarPainter(new StandardBarPainter());
        renderer.setSeriesPaint(0, new java.awt.Color(100,149,237));
        renderer.setMaximumBarWidth(0.15);

        NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
        rangeAxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());
        rangeAxis.setTickLabelFont(
            new java.awt.Font("Helvetica Neue", java.awt.Font.PLAIN, 11)
        );
        rangeAxis.setLabelFont(
            new java.awt.Font("Helvetica Neue", java.awt.Font.BOLD, 12)
        );
        
        rangeAxis.setTickUnit(new NumberTickUnit(1));
        
        var domainAxis = plot.getDomainAxis();
        domainAxis.setTickLabelFont(
            new java.awt.Font("Helvetica Neue", java.awt.Font.PLAIN, 11)
        );
        domainAxis.setLabelFont(
            new java.awt.Font("Helvetica Neue", java.awt.Font.BOLD, 12)
        );
        
        chart.getTitle().setFont(
            new java.awt.Font("Helvetica Neue", java.awt.Font.BOLD, 13)
        );

        ChartPanel panel = new ChartPanel(chart);
        panel.setBackground(java.awt.Color.WHITE);
        panel.setBorder(
            BorderFactory.createEmptyBorder(15, 25, 15, 25)
        );

        this.removeAll();
        this.setLayout(new java.awt.BorderLayout());
        this.add(panel, java.awt.BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
