/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.AcademicLeader;

import assessmentfeedbacksystem.AcademicLeader;

/**
 *
 * @author xinyun
 */
public class DashboardChartPanel extends javax.swing.JPanel {
    
    private AcademicLeader logged_in_al;
    private AcademicLeaderMainFrame mainFrame;

    /**
     * Creates new form DashboardChartPanel
     */
    public DashboardChartPanel() {
        initComponents();
    }
    
    public void loadData(AcademicLeaderMainFrame mainFrame, AcademicLeader al) {
        this.mainFrame = mainFrame;
        this.logged_in_al = al;
        departmentLecturerAllocationBarChartPanel1.loadChart(al);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allocationChartPanel = new javax.swing.JPanel();
        departmentLecturerAllocationBarChartPanel1 = new assessmentfeedbacksystem.GUI.AcademicLeader.DepartmentLecturerAllocationBarChartPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new java.awt.BorderLayout());

        allocationChartPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout departmentLecturerAllocationBarChartPanel1Layout = new javax.swing.GroupLayout(departmentLecturerAllocationBarChartPanel1);
        departmentLecturerAllocationBarChartPanel1.setLayout(departmentLecturerAllocationBarChartPanel1Layout);
        departmentLecturerAllocationBarChartPanel1Layout.setHorizontalGroup(
            departmentLecturerAllocationBarChartPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        departmentLecturerAllocationBarChartPanel1Layout.setVerticalGroup(
            departmentLecturerAllocationBarChartPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        allocationChartPanel.add(departmentLecturerAllocationBarChartPanel1, java.awt.BorderLayout.CENTER);

        add(allocationChartPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel allocationChartPanel;
    private assessmentfeedbacksystem.GUI.AcademicLeader.DepartmentLecturerAllocationBarChartPanel departmentLecturerAllocationBarChartPanel1;
    // End of variables declaration//GEN-END:variables
}
