/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.AcademicLeader;

import assessmentfeedbacksystem.AcademicLeader;
import assessmentfeedbacksystem.ClassModel;
import assessmentfeedbacksystem.Module;
import java.awt.Color;
import java.awt.Font;
import java.time.LocalDate;
import java.time.format.TextStyle;
import java.util.List;
import java.util.Locale;
import javax.swing.Box;
import javax.swing.JLabel;

/**
 *
 * @author xinyun
 */
public class DashboardPanel extends javax.swing.JPanel {
    
    private AcademicLeader logged_in_al;
    private AcademicLeaderMainFrame mainFrame;

    /**
     * Creates new form DashboardPanel
     */
    public DashboardPanel() {
        initComponents();
    }
    
    public DashboardPanel(AcademicLeaderMainFrame mainFrame, AcademicLeader al) {
        this.mainFrame = mainFrame;
        this.logged_in_al = al;
        initComponents();

        // welcome
        lblWelcome.setText("Welcome back, " + al.getName() + "!");
        
        // today
        LocalDate today = LocalDate.now();

        String formattedDate =
                today.getDayOfMonth() + " " +
                today.getMonth().getDisplayName(TextStyle.FULL, Locale.ENGLISH) + " " +
                today.getYear() + ", " +
                today.getDayOfWeek().getDisplayName(TextStyle.FULL, Locale.ENGLISH);

        lblTodayDate.setText(formattedDate);

        // module
        List<Module> activeModules = Module.getActiveModules().stream()
            .filter(m -> m.getCreatedBy().equals(logged_in_al.getUser_id()))
            .toList();

        List<Module> inactiveModules = Module.getInactiveModules().stream()
            .filter(m -> m.getCreatedBy().equals(logged_in_al.getUser_id()))
            .toList();

        int activeCount = activeModules.size();
        int inactiveCount = inactiveModules.size();

        List<Module> waitingModules = activeModules.stream()
            .filter(m -> ClassModel.getClassByModuleId(m.getModuleId()) == null)
            .toList();

        int waitingCount = waitingModules.size();
        int percent = activeCount == 0 ? 0 : (waitingCount * 100 / activeCount);

        // progress circle
        ((ProgressCirclePanel)pnlCircle).setPercentage(percent);
        lblProgressText.setText("Modules Without Class: " + waitingCount);
        
        // widget panels
        widgetActive.setData("Active Modules", activeCount);
        widgetActive.setTheme(new Color(22, 163, 74));     
        
        widgetInactive.setData("Inactive Modules", inactiveCount);
        widgetInactive.setTheme(new Color(37, 99, 235));
        
        dashboardChartPanel1.loadData(mainFrame, al);
        
        // module list below progress circle
        pnlModuleList.removeAll(); 
        pnlModuleList.add(jSeparator1);
        pnlModuleList.add(Box.createVerticalStrut(12));
        pnlModuleList.add(lblWaitingTitle);

        for (Module m : waitingModules) {
            JLabel lbl = new JLabel("•  " + m.getModuleName());
            lbl.setForeground(new Color(85, 85, 85));
//            lbl.setForeground(new Color(220, 38, 38));
            lbl.setFont(new Font("Helvetica Neue", Font.PLAIN, 13));
            lbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 0, 1, 0));
            pnlModuleList.add(lbl);
        }
        
        pnlModuleList.revalidate();
        pnlModuleList.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        pnlBody = new javax.swing.JPanel();
        pnlLeft = new javax.swing.JPanel();
        pnlWidgetRow = new javax.swing.JPanel();
        widgetActive = new assessmentfeedbacksystem.GUI.AcademicLeader.StatWidgetPanel();
        widgetInactive = new assessmentfeedbacksystem.GUI.AcademicLeader.StatWidgetPanel();
        pnlChartHolder = new javax.swing.JPanel();
        dashboardChartPanel1 = new assessmentfeedbacksystem.GUI.AcademicLeader.DashboardChartPanel();
        pnlRight = new javax.swing.JPanel();
        pnlToday = new javax.swing.JPanel();
        lblTodayTitle = new javax.swing.JLabel();
        lblTodayDate = new javax.swing.JLabel();
        pnlProgress = new javax.swing.JPanel();
        pnlCircle = new ProgressCirclePanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        lblProgressText = new javax.swing.JLabel();
        pnlModuleList = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        lblWaitingTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(237, 241, 246));
        setPreferredSize(new java.awt.Dimension(770, 540));
        setLayout(new java.awt.BorderLayout(15, 5));

        pnlHeader.setBackground(new java.awt.Color(237, 241, 246));
        pnlHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 19, 10, 5));
        pnlHeader.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        lblWelcome.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblWelcome.setText("Welcome back, Academic Leader ");
        pnlHeader.add(lblWelcome);

        add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlBody.setBackground(new java.awt.Color(237, 241, 246));
        pnlBody.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 35, 30, 35));
        pnlBody.setLayout(new java.awt.BorderLayout(20, 5));

        pnlLeft.setBackground(new java.awt.Color(237, 241, 246));
        pnlLeft.setLayout(new java.awt.BorderLayout());

        pnlWidgetRow.setBackground(new java.awt.Color(237, 241, 246));
        pnlWidgetRow.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 15, 0));
        pnlWidgetRow.setPreferredSize(new java.awt.Dimension(0, 110));
        pnlWidgetRow.setLayout(new java.awt.GridLayout(1, 3, 15, 0));
        pnlWidgetRow.add(widgetActive);
        pnlWidgetRow.add(widgetInactive);

        pnlLeft.add(pnlWidgetRow, java.awt.BorderLayout.NORTH);

        pnlChartHolder.setBackground(new java.awt.Color(237, 241, 246));
        pnlChartHolder.setLayout(new java.awt.BorderLayout());
        pnlChartHolder.add(dashboardChartPanel1, java.awt.BorderLayout.CENTER);

        pnlLeft.add(pnlChartHolder, java.awt.BorderLayout.CENTER);

        pnlBody.add(pnlLeft, java.awt.BorderLayout.CENTER);

        pnlRight.setBackground(new java.awt.Color(255, 255, 255));
        pnlRight.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlRight.setPreferredSize(new java.awt.Dimension(280, 0));
        pnlRight.setLayout(new java.awt.BorderLayout());

        pnlToday.setBackground(new java.awt.Color(255, 255, 255));
        pnlToday.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20));
        pnlToday.setPreferredSize(new java.awt.Dimension(250, 60));
        pnlToday.setLayout(new javax.swing.BoxLayout(pnlToday, javax.swing.BoxLayout.Y_AXIS));

        lblTodayTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 11)); // NOI18N
        lblTodayTitle.setForeground(new java.awt.Color(100, 116, 139));
        lblTodayTitle.setText("TODAY");
        pnlToday.add(lblTodayTitle);

        lblTodayDate.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblTodayDate.setForeground(new java.awt.Color(0, 102, 153));
        lblTodayDate.setText("1 January 2026, Thursday ");
        pnlToday.add(lblTodayDate);

        pnlRight.add(pnlToday, java.awt.BorderLayout.PAGE_START);

        pnlProgress.setBackground(new java.awt.Color(255, 255, 255));
        pnlProgress.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        pnlProgress.setLayout(new javax.swing.BoxLayout(pnlProgress, javax.swing.BoxLayout.Y_AXIS));

        pnlCircle.setBackground(new java.awt.Color(255, 255, 255));
        pnlCircle.setPreferredSize(new java.awt.Dimension(110, 110));

        javax.swing.GroupLayout pnlCircleLayout = new javax.swing.GroupLayout(pnlCircle);
        pnlCircle.setLayout(pnlCircleLayout);
        pnlCircleLayout.setHorizontalGroup(
            pnlCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        pnlCircleLayout.setVerticalGroup(
            pnlCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );

        pnlProgress.add(pnlCircle);
        pnlProgress.add(filler1);

        lblProgressText.setForeground(new java.awt.Color(100, 116, 139));
        lblProgressText.setText("Modules Without Class ");
        lblProgressText.setAlignmentX(0.5F);
        pnlProgress.add(lblProgressText);

        pnlRight.add(pnlProgress, java.awt.BorderLayout.CENTER);

        pnlModuleList.setBackground(new java.awt.Color(255, 255, 255));
        pnlModuleList.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 20, 20));
        pnlModuleList.setLayout(new javax.swing.BoxLayout(pnlModuleList, javax.swing.BoxLayout.Y_AXIS));

        jSeparator1.setMinimumSize(new java.awt.Dimension(1, 3));
        jSeparator1.setPreferredSize(new java.awt.Dimension(1, 3));
        pnlModuleList.add(jSeparator1);
        pnlModuleList.add(filler2);

        lblWaitingTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblWaitingTitle.setForeground(new java.awt.Color(153, 27, 27));
        lblWaitingTitle.setText("⚠ Modules Waiting for Class");
        pnlModuleList.add(lblWaitingTitle);

        pnlRight.add(pnlModuleList, java.awt.BorderLayout.SOUTH);

        pnlBody.add(pnlRight, java.awt.BorderLayout.EAST);

        add(pnlBody, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private assessmentfeedbacksystem.GUI.AcademicLeader.DashboardChartPanel dashboardChartPanel1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblProgressText;
    private javax.swing.JLabel lblTodayDate;
    private javax.swing.JLabel lblTodayTitle;
    private javax.swing.JLabel lblWaitingTitle;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlChartHolder;
    private javax.swing.JPanel pnlCircle;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlModuleList;
    private javax.swing.JPanel pnlProgress;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlToday;
    private javax.swing.JPanel pnlWidgetRow;
    private assessmentfeedbacksystem.GUI.AcademicLeader.StatWidgetPanel widgetActive;
    private assessmentfeedbacksystem.GUI.AcademicLeader.StatWidgetPanel widgetInactive;
    // End of variables declaration//GEN-END:variables
}
