/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.AcademicLeader;

import assessmentfeedbacksystem.AcademicLeader;
import assessmentfeedbacksystem.DepartmentLecturerAllocationReportService;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.chart.renderer.category.BarRenderer;
import javax.swing.BorderFactory;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.NumberTickUnit;
import org.jfree.chart.renderer.category.StandardBarPainter;

/**
 *
 * @author xinyun
 */
public class DepartmentLecturerAllocationBarChartPanel extends javax.swing.JPanel {

    /**
     * Creates new form DepartmentLecturerAllocationBarChartPanel
     */
    public DepartmentLecturerAllocationBarChartPanel() {
        initComponents();
    }
    
    public void loadChart(AcademicLeader al) {

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        for (Object[] row :
                DepartmentLecturerAllocationReportService
                        .getLecturerAllocationChartData(al)) {

            String lecturerLabel = row[0].toString();
            int active = (int) row[1];
            int inactive = (int) row[2];

            dataset.addValue(active, "Active Modules", lecturerLabel);
            dataset.addValue(inactive, "Inactive Modules", lecturerLabel);
        }

        JFreeChart barChart = ChartFactory.createBarChart(
            "Lecturer Module Allocation",
            "Lecturer",
            "Number of Modules",
            dataset,
            PlotOrientation.VERTICAL,
            true,   
            true,
            false
        );

        barChart.setBackgroundPaint(java.awt.Color.WHITE);

        var plot = barChart.getCategoryPlot();
        plot.setBackgroundPaint(java.awt.Color.WHITE);
        plot.setRangeGridlinePaint(new java.awt.Color(220, 220, 220));
        plot.setRangeGridlineStroke(new java.awt.BasicStroke(0.8f));

        // bar
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setMaximumBarWidth(0.15);
        renderer.setItemMargin(0.05); 
        renderer.setDrawBarOutline(false);
        renderer.setBarPainter(new StandardBarPainter());

//        renderer.setSeriesPaint(0, new java.awt.Color(79, 129, 189));
        renderer.setSeriesPaint(0, new java.awt.Color(100, 149, 237));
        renderer.setSeriesPaint(1, new java.awt.Color(192, 80, 77));   

        // label
//        renderer.setItemLabelGenerator(
//            new StandardCategoryItemLabelGenerator("{2}",
//                new DecimalFormat("0"))
//        );
//        renderer.setItemLabelsVisible(true);
//        renderer.setItemLabelFont(
//            new java.awt.Font("Helvetica Neue", java.awt.Font.PLAIN, 10)
//        );

        NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();

        rangeAxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());

        rangeAxis.setTickLabelFont(
            new java.awt.Font("Helvetica Neue", java.awt.Font.PLAIN, 11)
        );
        rangeAxis.setLabelFont(
            new java.awt.Font("Helvetica Neue", java.awt.Font.BOLD, 12)
        );
        
        rangeAxis.setTickUnit(new NumberTickUnit(1));

        var domainAxis = plot.getDomainAxis();
        domainAxis.setTickLabelFont(
            new java.awt.Font("Helvetica Neue", java.awt.Font.PLAIN, 11)
        );
        domainAxis.setLabelFont(
            new java.awt.Font("Helvetica Neue", java.awt.Font.BOLD, 12)
        );
        
        // legend
        var legend = barChart.getLegend();
        legend.setFrame(org.jfree.chart.block.BlockBorder.NONE);
        legend.setBackgroundPaint(java.awt.Color.WHITE);
        legend.setItemFont(new java.awt.Font("Helvetica Neue", java.awt.Font.PLAIN, 11));


        barChart.getTitle().setFont(
            new java.awt.Font("Helvetica Neue", java.awt.Font.BOLD, 13)
        );

        ChartPanel chartPanel = new ChartPanel(barChart);
        chartPanel.setBackground(java.awt.Color.WHITE);
        chartPanel.setBorder(
            BorderFactory.createEmptyBorder(15, 25, 15, 25)
        );

        this.removeAll();
        this.setLayout(new java.awt.BorderLayout());
        this.add(chartPanel, java.awt.BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
