/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.AcademicLeader;

import assessmentfeedbacksystem.AcademicLeader;
import assessmentfeedbacksystem.User;
import javax.swing.JOptionPane;

/**
 *
 * @author xinyun
 */

public class EditProfilePanel extends javax.swing.JPanel {
    
    private AcademicLeader logged_in_user;
    private ProfileContainerPanel parent;
    
    /**
     * Creates new form ActiveModuleDetailPanel
     */
    
    public EditProfilePanel() {
        initComponents();
    }
    
    public EditProfilePanel(ProfileContainerPanel parent, AcademicLeader user) {
        this.parent = parent;
        this.logged_in_user = user;
        initComponents();
        setUser(logged_in_user);
    }
    
    public void setUser(AcademicLeader user) {
        if (user == null) return;
        
        this.logged_in_user = user;

        lblUserIDValue.setText(user.getUser_id());
        lblUserNameValue.setText(user.getName());
        txtEmailAddress.setText(user.getEmail());
        txtContactNumber.setText(user.getContact_no());
        
        String gender = user.getGender();
        if (gender == null) {
            lblGenderValue.setText("-");
        } else if (gender.equalsIgnoreCase("M")) {
            lblGenderValue.setText("Male");
        } else if (gender.equalsIgnoreCase("F")) {
            lblGenderValue.setText("Female");
        } else {
            lblGenderValue.setText(gender);
        }

        lblDOBValue.setText(
            user.getDob() != null ? user.getDob().toString() : "-"
        );
        lblRoleValue.setText(user.getRole());
        lblDepartmentValue.setText(
            user.getDepartment() != null ? user.getDepartment() : "-"
        );

        pswPassword.setText("");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        headerPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bodyPanel = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        profileIconPanel = new javax.swing.JPanel();
        profileIcon = new javax.swing.JLabel();
        lblUserID = new javax.swing.JLabel();
        lblUserIDValue = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblRoleValue = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblUserNameValue = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        txtEmailAddress = new javax.swing.JTextField();
        lblContactNumber = new javax.swing.JLabel();
        txtContactNumber = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        lblGenderValue = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblDOBValue = new javax.swing.JLabel();
        lblDepartment = new javax.swing.JLabel();
        lblDepartmentValue = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        pswPassword = new javax.swing.JPasswordField();
        submitPanel = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(237, 241, 246));
        setLayout(new java.awt.BorderLayout(15, 5));

        headerPanel.setBackground(new java.awt.Color(237, 241, 246));
        headerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        titlePanel.setBackground(new java.awt.Color(237, 241, 246));
        titlePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 15, 10, 5));
        titlePanel.setLayout(new javax.swing.BoxLayout(titlePanel, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Profile Detail");
        titlePanel.add(jLabel1);

        jPanel1.setBackground(new java.awt.Color(237, 241, 246));
        titlePanel.add(jPanel1);

        headerPanel.add(titlePanel);

        add(headerPanel, java.awt.BorderLayout.PAGE_START);

        bodyPanel.setBackground(new java.awt.Color(237, 241, 246));
        bodyPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 35, 30, 35));
        bodyPanel.setLayout(new javax.swing.BoxLayout(bodyPanel, javax.swing.BoxLayout.Y_AXIS));

        formPanel.setBackground(new java.awt.Color(255, 255, 255));
        formPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 0, 20));
        formPanel.setLayout(new java.awt.GridBagLayout());

        profileIconPanel.setBackground(new java.awt.Color(247, 247, 247));
        profileIconPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        profileIconPanel.setPreferredSize(new java.awt.Dimension(180, 180));
        profileIconPanel.setLayout(new java.awt.BorderLayout());

        profileIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit profile.png"))); // NOI18N
        profileIcon.setAlignmentX(0.5F);
        profileIconPanel.add(profileIcon, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.insets = new java.awt.Insets(30, 5, 30, 30);
        formPanel.add(profileIconPanel, gridBagConstraints);

        lblUserID.setForeground(new java.awt.Color(102, 102, 102));
        lblUserID.setText("User ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblUserID, gridBagConstraints);

        lblUserIDValue.setBackground(new java.awt.Color(225, 236, 247));
        lblUserIDValue.setText("[User ID Value]");
        lblUserIDValue.setToolTipText("");
        lblUserIDValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblUserIDValue.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblUserIDValue, gridBagConstraints);

        lblRole.setForeground(new java.awt.Color(102, 102, 102));
        lblRole.setText("Role");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblRole, gridBagConstraints);

        lblRoleValue.setBackground(new java.awt.Color(225, 236, 247));
        lblRoleValue.setText("[Role Value]");
        lblRoleValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblRoleValue.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblRoleValue, gridBagConstraints);

        lblUserName.setForeground(new java.awt.Color(102, 102, 102));
        lblUserName.setText("User Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblUserName, gridBagConstraints);

        lblUserNameValue.setBackground(new java.awt.Color(225, 236, 247));
        lblUserNameValue.setText("[User Name Value]");
        lblUserNameValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblUserNameValue.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblUserNameValue, gridBagConstraints);

        lblEmailAddress.setForeground(new java.awt.Color(102, 102, 102));
        lblEmailAddress.setText("Email Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblEmailAddress, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 8);
        formPanel.add(txtEmailAddress, gridBagConstraints);

        lblContactNumber.setForeground(new java.awt.Color(102, 102, 102));
        lblContactNumber.setText("Contact Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblContactNumber, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 8);
        formPanel.add(txtContactNumber, gridBagConstraints);

        lblGender.setForeground(new java.awt.Color(102, 102, 102));
        lblGender.setText("Gender");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblGender, gridBagConstraints);

        lblGenderValue.setBackground(new java.awt.Color(225, 236, 247));
        lblGenderValue.setText("[Gender Value]");
        lblGenderValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblGenderValue.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblGenderValue, gridBagConstraints);

        lblDOB.setForeground(new java.awt.Color(102, 102, 102));
        lblDOB.setText("DOB");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblDOB, gridBagConstraints);

        lblDOBValue.setBackground(new java.awt.Color(225, 236, 247));
        lblDOBValue.setText("[DOB Value]");
        lblDOBValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblDOBValue.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblDOBValue, gridBagConstraints);

        lblDepartment.setForeground(new java.awt.Color(102, 102, 102));
        lblDepartment.setText("Department");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblDepartment, gridBagConstraints);

        lblDepartmentValue.setBackground(new java.awt.Color(225, 236, 247));
        lblDepartmentValue.setText("[Department Value]");
        lblDepartmentValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblDepartmentValue.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblDepartmentValue, gridBagConstraints);

        lblPassword.setForeground(new java.awt.Color(102, 102, 102));
        lblPassword.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblPassword, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 8);
        formPanel.add(pswPassword, gridBagConstraints);

        bodyPanel.add(formPanel);

        submitPanel.setBackground(new java.awt.Color(255, 255, 255));
        submitPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 12, 12, 12));

        btnCancel.setBackground(new java.awt.Color(232, 242, 255));
        btnCancel.setForeground(new java.awt.Color(45, 94, 168));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        btnCancel.setBorderPainted(false);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setFocusable(false);
        btnCancel.setPreferredSize(new java.awt.Dimension(72, 30));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        submitPanel.add(btnCancel);

        btnSave.setBackground(new java.awt.Color(45, 94, 168));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save Changes");
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.setFocusPainted(false);
        btnSave.setFocusable(false);
        btnSave.setPreferredSize(new java.awt.Dimension(115, 30));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        submitPanel.add(btnSave);

        bodyPanel.add(submitPanel);

        add(bodyPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String email = txtEmailAddress.getText().trim();
        String contact = txtContactNumber.getText().trim();
        String password = new String(pswPassword.getPassword()).trim();

        if (email.isEmpty() || contact.isEmpty()) {
            JOptionPane.showMessageDialog(
                null,
                "Please fill in all required fields.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        boolean success = User.updateProfile(
            logged_in_user.getUser_id(),
            email,
            contact,
            password.isEmpty() ? null : password
        );

        if (!success) {
            JOptionPane.showMessageDialog(
                null,
                "Failed to update profile.",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        logged_in_user.setEmail(email);
        logged_in_user.setContact_no(contact);
        if (!password.isEmpty()) {
            logged_in_user.setPassword(password);
        }

        JOptionPane.showMessageDialog(
            null,
            "Profile updated successfully.",
            "Success",
            JOptionPane.INFORMATION_MESSAGE
        );

        parent.showDetail(); 
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        parent.showDetail();
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContactNumber;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDOBValue;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblDepartmentValue;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGenderValue;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblRoleValue;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JLabel lblUserIDValue;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserNameValue;
    private javax.swing.JLabel profileIcon;
    private javax.swing.JPanel profileIconPanel;
    private javax.swing.JPasswordField pswPassword;
    private javax.swing.JPanel submitPanel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtEmailAddress;
    // End of variables declaration//GEN-END:variables
}
