/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.AcademicLeader;

import assessmentfeedbacksystem.AcademicLeader;
import assessmentfeedbacksystem.Module;
import assessmentfeedbacksystem.FileManager;
import assessmentfeedbacksystem.ClassModel;
import assessmentfeedbacksystem.Lecturer;
import javax.swing.JOptionPane;

/**
 *
 * @author xinyun
 */

public class EditModulePanel extends javax.swing.JPanel {
    
    private ActiveModuleContainerPanel parent;
    private AcademicLeader logged_in_al;
    private Module currentModule;

    /**
     * Creates new form EditModulePanel
     */
    
    public EditModulePanel() {
        initComponents();
    }
    
    public EditModulePanel(ActiveModuleContainerPanel parent, AcademicLeader logged_in_al) {
        this.parent = parent;
        this.logged_in_al = logged_in_al;
        initComponents();
        loadLecturers();
    }
    
    private void loadLecturers() {
        cmbLecturer.removeAllItems();

        for (String line : FileManager.readFile("User.txt")) {
            String[] data = line.split(";");
            if (data.length < 12) continue;

            if (data[7].equals("Lecturer") &&
                data[11].equals(logged_in_al.getUser_id())) {
                cmbLecturer.addItem(data[0] + " - " + data[1]);
            }
        }
    }
    
    public void setModule(Module m) {
        this.currentModule = m;

        txtModuleCode.setText(m.getModuleCode());
        txtModuleName.setText(m.getModuleName());
        spnCreditHour.setValue(m.getCreditHour());

        for (int i = 0; i < cmbLecturer.getItemCount(); i++) {
            if (cmbLecturer.getItemAt(i).startsWith(m.getLecturer().getUser_id())) {
                cmbLecturer.setSelectedIndex(i);
                break;
            }
        }
        
        ClassModel c = ClassModel.getClassByModuleId(m.getModuleId());
        
        if (c != null) {
            lblStudentCountValue.setText(String.valueOf(ClassModel.getNoOfStudentInClass(c.getClassId())));     
        } else {
            lblStudentCountValue.setText("0 (Waiting for class to be created)");
        }
        
        lblDateValue.setText(m.getDateCreated().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        headerPanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        titlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        lblModuleCode = new javax.swing.JLabel();
        txtModuleCode = new javax.swing.JTextField();
        lblModuleName = new javax.swing.JLabel();
        txtModuleName = new javax.swing.JTextField();
        lblCreditHour = new javax.swing.JLabel();
        spnCreditHour = new javax.swing.JSpinner();
        lblLecturer = new javax.swing.JLabel();
        cmbLecturer = new javax.swing.JComboBox<>();
        lblStudentCount = new javax.swing.JLabel();
        lblStudentCountValue = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblDateValue = new javax.swing.JLabel();
        submitPanel = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20));
        setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setLayout(new java.awt.BorderLayout());

        buttonPanel.setBackground(new java.awt.Color(255, 255, 255));
        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0));

        btnClose.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnClose.setForeground(new java.awt.Color(120, 120, 120));
        btnClose.setText("x");
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setFocusable(false);
        btnClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        buttonPanel.add(btnClose);

        headerPanel.add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        titlePanel.setBackground(new java.awt.Color(255, 255, 255));
        titlePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 9, 5));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel1.setText("Edit Module");
        titlePanel.add(jLabel1);

        headerPanel.add(titlePanel, java.awt.BorderLayout.CENTER);

        add(headerPanel, java.awt.BorderLayout.PAGE_START);

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setLayout(new javax.swing.BoxLayout(bodyPanel, javax.swing.BoxLayout.Y_AXIS));

        formPanel.setBackground(new java.awt.Color(255, 255, 255));
        formPanel.setLayout(new java.awt.GridBagLayout());

        lblModuleCode.setForeground(new java.awt.Color(102, 102, 102));
        lblModuleCode.setText("Module Code");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblModuleCode, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 10, 4, 10);
        formPanel.add(txtModuleCode, gridBagConstraints);

        lblModuleName.setForeground(new java.awt.Color(102, 102, 102));
        lblModuleName.setText("Module Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblModuleName, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 10, 4, 10);
        formPanel.add(txtModuleName, gridBagConstraints);

        lblCreditHour.setForeground(new java.awt.Color(102, 102, 102));
        lblCreditHour.setText("Credit Hour");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblCreditHour, gridBagConstraints);

        spnCreditHour.setModel(new javax.swing.SpinnerNumberModel(3.0d, 0.5d, 5.0d, 0.1d));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 10, 4, 10);
        formPanel.add(spnCreditHour, gridBagConstraints);

        lblLecturer.setForeground(new java.awt.Color(102, 102, 102));
        lblLecturer.setText("Lecturer Assigned");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblLecturer, gridBagConstraints);

        cmbLecturer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(cmbLecturer, gridBagConstraints);

        lblStudentCount.setForeground(new java.awt.Color(102, 102, 102));
        lblStudentCount.setText("Student Count");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblStudentCount, gridBagConstraints);

        lblStudentCountValue.setBackground(new java.awt.Color(225, 236, 247));
        lblStudentCountValue.setText("[Student Count Value]");
        lblStudentCountValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblStudentCountValue.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblStudentCountValue, gridBagConstraints);

        lblDate.setForeground(new java.awt.Color(102, 102, 102));
        lblDate.setText("Date Created");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblDate, gridBagConstraints);

        lblDateValue.setBackground(new java.awt.Color(225, 236, 247));
        lblDateValue.setText("[Date Created Value]");
        lblDateValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblDateValue.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        formPanel.add(lblDateValue, gridBagConstraints);

        bodyPanel.add(formPanel);

        submitPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnCancel.setBackground(new java.awt.Color(232, 242, 255));
        btnCancel.setForeground(new java.awt.Color(45, 94, 168));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        btnCancel.setBorderPainted(false);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setFocusable(false);
        btnCancel.setPreferredSize(new java.awt.Dimension(72, 30));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        submitPanel.add(btnCancel);

        btnSave.setBackground(new java.awt.Color(45, 94, 168));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save Changes");
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.setFocusable(false);
        btnSave.setPreferredSize(new java.awt.Dimension(115, 30));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        submitPanel.add(btnSave);

        bodyPanel.add(submitPanel);

        add(bodyPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        if (currentModule != null) {
            parent.showDetail(currentModule);
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        if (currentModule != null) {
            parent.showDetail(currentModule);
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (currentModule == null) return;
        
        String code = txtModuleCode.getText().trim();
        String name = txtModuleName.getText().trim();
        double credit = ((Number) spnCreditHour.getValue()).doubleValue();

        if (code.isEmpty() || name.isEmpty()) {
            JOptionPane.showMessageDialog(
                null,
                "Please fill in all required fields.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        currentModule.setModuleCode(code);
        currentModule.setModuleName(name);
        currentModule.setCreditHour(credit);

        String lecturerItem = cmbLecturer.getSelectedItem().toString();
//        currentModule.setLecturerId(lecturerItem.split(" - ")[0]);
        currentModule.setLecturer(Lecturer.getLecturerById(lecturerItem.split(" - ")[0]));
        
        boolean success = Module.updateModule(currentModule);

        if (success) {
            JOptionPane.showMessageDialog(null, "Module updated successfully.","Success",JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Failed to update module.","Error",JOptionPane.ERROR_MESSAGE);
        }

        parent.showDetail(currentModule);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        // TODO add your handling code here:
        btnClose.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        // TODO add your handling code here:
        btnClose.setForeground(new java.awt.Color(120, 120, 120));
    }//GEN-LAST:event_btnCloseMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JComboBox<String> cmbLecturer;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCreditHour;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDateValue;
    private javax.swing.JLabel lblLecturer;
    private javax.swing.JLabel lblModuleCode;
    private javax.swing.JLabel lblModuleName;
    private javax.swing.JLabel lblStudentCount;
    private javax.swing.JLabel lblStudentCountValue;
    private javax.swing.JSpinner spnCreditHour;
    private javax.swing.JPanel submitPanel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField txtModuleCode;
    private javax.swing.JTextField txtModuleName;
    // End of variables declaration//GEN-END:variables
}
