/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.AcademicLeader;

import assessmentfeedbacksystem.AcademicLeader;
import assessmentfeedbacksystem.GradeDistributionReportService;
import javax.swing.BorderFactory;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author xinyun
 */
public class GradeDistributionPieChartPanel extends javax.swing.JPanel {

    /**
     * Creates new form GradeDistributionPieChartPanel
     */
    public GradeDistributionPieChartPanel() {
        initComponents();
    }
    
    public void loadChart(AcademicLeader al) {

        DefaultPieDataset dataset = new DefaultPieDataset();

        for (Object[] row:GradeDistributionReportService.getGradeDistributionChartData(al)) {

            String grade = row[0].toString();
            int count = (int) row[1];

            if (count > 0) {
                dataset.setValue(grade, count);
            }
        }

        JFreeChart pieChart = ChartFactory.createPieChart(
            "Grade Distribution",
            dataset,
            true,
            true,
            false
        );

        pieChart.setBackgroundPaint(java.awt.Color.WHITE);
        pieChart.getTitle().setFont(
            new java.awt.Font("Helvetica Neue", java.awt.Font.BOLD, 14)
        );
        
//        if (pieChart.getLegend() != null) {
//            pieChart.getLegend().setPosition(RectangleEdge.RIGHT);
//        }

        PiePlot plot = (PiePlot) pieChart.getPlot();
        plot.setBackgroundPaint(java.awt.Color.WHITE);
        plot.setOutlineVisible(false);
        
        plot.setSectionOutlinesVisible(false);
        plot.setInteriorGap(0.06);
        
        plot.setLabelFont(new java.awt.Font("Helvetica Neue", java.awt.Font.BOLD, 11));
        plot.setLabelPaint(java.awt.Color.WHITE);
        plot.setLabelBackgroundPaint(null);
        plot.setLabelOutlinePaint(null);
        plot.setLabelShadowPaint(null);

        plot.setSimpleLabels(true);
        plot.setLabelLinkPaint(java.awt.Color.GRAY);
        plot.setLabelLinkStroke(new java.awt.BasicStroke(0.8f));
        plot.setLabelGenerator(
            new org.jfree.chart.labels.StandardPieSectionLabelGenerator(
                "{2}"
            )
        );
        
        plot.setSectionPaint("A+", new java.awt.Color(46, 204, 113));   
        plot.setSectionPaint("A",  new java.awt.Color(39, 174, 96));
        plot.setSectionPaint("B+", new java.awt.Color(52, 152, 219));  
        plot.setSectionPaint("B",  new java.awt.Color(41, 128, 185));
        plot.setSectionPaint("C+", new java.awt.Color(241, 196, 15));  
        plot.setSectionPaint("C",  new java.awt.Color(243, 156, 18));
        plot.setSectionPaint("C-", new java.awt.Color(230, 126, 34)); 
        plot.setSectionPaint("D",  new java.awt.Color(231, 76, 60));  
        plot.setSectionPaint("F+", new java.awt.Color(192, 57, 43));
        plot.setSectionPaint("F",  new java.awt.Color(127, 140, 141)); 
        plot.setSectionPaint("F-", new java.awt.Color(95, 106, 106));
        
        if (pieChart.getLegend() != null) {
            pieChart.getLegend().setFrame(
                org.jfree.chart.block.BlockBorder.NONE
            );
            pieChart.getLegend().setItemFont(
                new java.awt.Font("Helvetica Neue", java.awt.Font.PLAIN, 11)
            );
        }
        
        ChartPanel chartPanel = new ChartPanel(pieChart);
        chartPanel.setBackground(java.awt.Color.WHITE);
        chartPanel.setBorder(
            BorderFactory.createEmptyBorder(15, 25, 15, 25)
        );

        this.removeAll();
        this.setLayout(new java.awt.BorderLayout());
        this.add(chartPanel, java.awt.BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
