/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.AcademicLeader;

import javax.swing.table.DefaultTableModel;
import assessmentfeedbacksystem.Module;
import assessmentfeedbacksystem.Lecturer;
import assessmentfeedbacksystem.AcademicLeader;

/**
 *
 * @author xinyun
 */

public class InactiveModuleTablePanel extends javax.swing.JPanel {
    
    private InactiveModuleContainerPanel parent;
    private AcademicLeader logged_in_al;

    /**
     * Creates new form InactiveModuleTablePanel
     */
    
    public InactiveModuleTablePanel() {
        initComponents();
    }
    
    public InactiveModuleTablePanel(InactiveModuleContainerPanel parent, AcademicLeader logged_in_al) {
        this.parent = parent;
        this.logged_in_al = logged_in_al;
        initComponents();
        applyStatusRenderer();
        loadInactiveModules();
    }
    
    private void applyStatusRenderer() {
        tblInactiveModules.getColumnModel()
            .getColumn(4)
            .setCellRenderer(new StatusBadgeRenderer());
    }
    
    private void loadInactiveModules() {
        DefaultTableModel model = (DefaultTableModel) tblInactiveModules.getModel();
        model.setRowCount(0);
        
        if (logged_in_al == null) {
            return;
        }

        for (Module m : Module.getInactiveModules()) {
            
            if (!m.getCreatedBy().equals(logged_in_al.getUser_id())) {
                continue;
            }           
            
            model.addRow(new Object[]{
                m.getModuleId(),
                m.getModuleCode(),
                m.getModuleName(),
                Lecturer.getLecturerNameById(m.getLecturer().getUser_id()),
                m.getStatus(),
            });
        }
    }
    
    public void reloadInactiveTable() {
        DefaultTableModel model = (DefaultTableModel) tblInactiveModules.getModel();
        model.setRowCount(0);
        
        if (logged_in_al == null) {
            return;
        }

        for (Module m : Module.getInactiveModules()) {
            
            if (!m.getCreatedBy().equals(logged_in_al.getUser_id())) {
                continue;
            }
            
            model.addRow(new Object[]{
                m.getModuleId(),
                m.getModuleCode(),
                m.getModuleName(),
                Lecturer.getLecturerNameById(m.getLecturer().getUser_id()),
                m.getStatus(),
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInactiveModules = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 15, 20));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 15));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel1.setText("Inactive Modules");
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        tblInactiveModules.setAutoCreateRowSorter(true);
        tblInactiveModules.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "moduleId", "Module Code", "Module Name", "Lecturer", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInactiveModules.setFillsViewportHeight(true);
        tblInactiveModules.setFocusable(false);
        tblInactiveModules.setRowHeight(35);
        tblInactiveModules.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblInactiveModules.setShowGrid(false);
        tblInactiveModules.getTableHeader().setReorderingAllowed(false);
        tblInactiveModules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInactiveModulesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInactiveModules);
        if (tblInactiveModules.getColumnModel().getColumnCount() > 0) {
            tblInactiveModules.getColumnModel().getColumn(0).setMinWidth(0);
            tblInactiveModules.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblInactiveModules.getColumnModel().getColumn(0).setMaxWidth(0);
            tblInactiveModules.getColumnModel().getColumn(1).setPreferredWidth(110);
            tblInactiveModules.getColumnModel().getColumn(2).setPreferredWidth(300);
            tblInactiveModules.getColumnModel().getColumn(3).setPreferredWidth(215);
            tblInactiveModules.getColumnModel().getColumn(4).setPreferredWidth(160);
        }

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void tblInactiveModulesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInactiveModulesMouseClicked
        // TODO add your handling code here:
        if (parent == null) {
            return;
        }
        
        int row = tblInactiveModules.getSelectedRow();
        if (row < 0) {
            return;
        }

        String moduleId = tblInactiveModules.getValueAt(row, 0).toString();

        for (Module m : Module.getInactiveModules()) { 
            if (m.getModuleId().equals(moduleId)) {
                parent.showDetail(m);
                break;
            }
        }
    }//GEN-LAST:event_tblInactiveModulesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInactiveModules;
    // End of variables declaration//GEN-END:variables
}
