/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.AcademicLeader;

import java.awt.CardLayout;
import assessmentfeedbacksystem.Module;
import assessmentfeedbacksystem.AcademicLeader;

/**
 *
 * @author xinyun
 */

public class InactiveModuleContainerPanel extends javax.swing.JPanel {
    
    private CardLayout cardLayout;
    private InactiveModuleTablePanel tablePanel;
    private InactiveModuleDetailPanel detailPanel;
    private AcademicLeader logged_in_user;

    /**
     * Creates new form InactiveModuleContainerPanel
     */
    
    public InactiveModuleContainerPanel() {
        initComponents();
    }
    
    public InactiveModuleContainerPanel(AcademicLeader logged_in_al) {
        this.logged_in_user = logged_in_al;
        initComponents();
        setupCards();
    }
    
    private void setupCards() {
        cardLayout = (CardLayout) getLayout();

        tablePanel = new InactiveModuleTablePanel(this, logged_in_user);
        detailPanel = new InactiveModuleDetailPanel(this, logged_in_user);

        add(tablePanel, "TABLE");
        add(detailPanel, "DETAIL");

        showTable();
    }
    
    public void showTable() {
        tablePanel.reloadInactiveTable();
        cardLayout.show(this, "TABLE");
    }

    public void showDetail(Module module) {
        detailPanel.setModule(module);
        tablePanel.reloadInactiveTable(); 
        cardLayout.show(this, "DETAIL");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTableCard = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        inactiveModuleTablePanel1 = new assessmentfeedbacksystem.GUI.AcademicLeader.InactiveModuleTablePanel(this, logged_in_user);
        pnlDetailCard = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        inactiveModuleDetailPanel1 = new assessmentfeedbacksystem.GUI.AcademicLeader.InactiveModuleDetailPanel(this, logged_in_user);

        setLayout(new java.awt.CardLayout());

        pnlTableCard.setBackground(new java.awt.Color(255, 255, 255));
        pnlTableCard.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(inactiveModuleTablePanel1, java.awt.BorderLayout.CENTER);

        pnlTableCard.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(pnlTableCard, "TABLE");

        pnlDetailCard.setBackground(new java.awt.Color(255, 255, 255));
        pnlDetailCard.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(inactiveModuleDetailPanel1, java.awt.BorderLayout.CENTER);

        pnlDetailCard.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(pnlDetailCard, "DETAIL");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private assessmentfeedbacksystem.GUI.AcademicLeader.InactiveModuleDetailPanel inactiveModuleDetailPanel1;
    private assessmentfeedbacksystem.GUI.AcademicLeader.InactiveModuleTablePanel inactiveModuleTablePanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlDetailCard;
    private javax.swing.JPanel pnlTableCard;
    // End of variables declaration//GEN-END:variables
}
