/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.AcademicLeader;

import assessmentfeedbacksystem.AcademicLeader;
import assessmentfeedbacksystem.LecturerPerformanceReportService;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.chart.labels.StandardCategoryItemLabelGenerator;
import org.jfree.chart.renderer.category.BarRenderer;
import java.text.DecimalFormat;
import javax.swing.BorderFactory;
import org.jfree.chart.renderer.category.StandardBarPainter;

/**
 *
 * @author xinyun
 */
public class LecturerPerformanceBarChartPanel extends javax.swing.JPanel {

    /**
     * Creates new form LecturerPerformanceBarChartPanel
     */
    public LecturerPerformanceBarChartPanel() {
        initComponents();
    }
    
    public void loadChart(AcademicLeader al) {

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        for (Object[] row : LecturerPerformanceReportService.getLecturerAverageRatings(al)) {

            String lecturerLabel = row[0].toString();
            double avgRating  = (double) row[1];

            dataset.addValue(avgRating, "Average Rating", lecturerLabel);
        }

        JFreeChart barChart = ChartFactory.createBarChart(
            "Average Lecturer Rating",
            "Lecturer",
            "Average Rating",
            dataset,
            PlotOrientation.VERTICAL,
            false,
            true,
            false
        );
        
        barChart.setBackgroundPaint(java.awt.Color.WHITE);

        var plot = barChart.getCategoryPlot();
        plot.setBackgroundPaint(java.awt.Color.WHITE);
        plot.setRangeGridlinePaint(new java.awt.Color(220,220,220));
        plot.setRangeGridlineStroke(new java.awt.BasicStroke(0.8f));

        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setMaximumBarWidth(0.15); 
//        renderer.setItemMargin(0.20); 
        renderer.setDrawBarOutline(false);
        renderer.setBarPainter(new StandardBarPainter());
        renderer.setSeriesPaint(0, new java.awt.Color(100, 149, 237));
        
        renderer.setItemLabelGenerator(
            new StandardCategoryItemLabelGenerator("{2}",
                new DecimalFormat("0.00"))
        );
        renderer.setItemLabelsVisible(true);
        renderer.setItemLabelFont(
            new java.awt.Font("Helvetica Neue", java.awt.Font.PLAIN, 10)
        );

        var rangeAxis = plot.getRangeAxis();
        rangeAxis.setRange(0.0, 100.0);
        rangeAxis.setTickLabelFont(new java.awt.Font("Helvetica Neue", java.awt.Font.PLAIN, 11));
        rangeAxis.setLabelFont(new java.awt.Font("Helvetica Neue", java.awt.Font.BOLD, 12));

        var domainAxis = plot.getDomainAxis();
        domainAxis.setTickLabelFont(new java.awt.Font("Helvetica Neue", java.awt.Font.PLAIN, 11));
        domainAxis.setLabelFont(new java.awt.Font("Helvetica Neue", java.awt.Font.BOLD, 12));

        plot.getRangeAxis().setRange(0.0, 5.0);
        
        barChart.getTitle().setFont(
            new java.awt.Font("Helvetica Neue", java.awt.Font.BOLD, 13)
        );

        ChartPanel chartPanel = new ChartPanel(barChart);
        chartPanel.setBackground(java.awt.Color.WHITE);
        chartPanel.setBorder(
            BorderFactory.createEmptyBorder(15, 25, 15, 25)
        );

        this.removeAll();
        this.setLayout(new java.awt.BorderLayout());
        this.add(chartPanel, java.awt.BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
