/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.AcademicLeader;

import assessmentfeedbacksystem.AcademicLeader;
import assessmentfeedbacksystem.ModulePerformanceReportService;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xinyun
 */
public class ModulePerformanceReportPanel extends javax.swing.JPanel {
    
    private AcademicLeader logged_in_al;

    /**
     * Creates new form ModulePerformanceReportPanel
     */
    public ModulePerformanceReportPanel() {
        initComponents();
    }
    
    public ModulePerformanceReportPanel(AcademicLeader al) {
        initComponents();
        this.logged_in_al = al;
        loadReportData();
        modulePerformanceBarChartPanel1.loadChart(logged_in_al);
    }
    
    public void loadReportData() {
        DefaultTableModel model = (DefaultTableModel) tblModulePerformance.getModel();
        model.setRowCount(0);

        for (Object[] row : ModulePerformanceReportService.getModulePerformanceData(logged_in_al)) {
            model.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        ContentPanel = new javax.swing.JPanel();
        headerContentPanel = new javax.swing.JPanel();
        leftTextPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        descPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        exportPanel = new javax.swing.JPanel();
        btnExport = new javax.swing.JButton();
        chartContainerPanel = new javax.swing.JPanel();
        modulePerformanceBarChartPanel1 = new assessmentfeedbacksystem.GUI.AcademicLeader.ModulePerformanceBarChartPanel();
        tableContainerPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblModulePerformance = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(ContentPanel);
        jScrollPane1.setBorder(BorderFactory.createEmptyBorder());
        jScrollPane1.getViewport().setBorder(null);
        jScrollPane1.getViewport().setBackground(Color.WHITE);

        ContentPanel.setBackground(new java.awt.Color(255, 255, 255));
        ContentPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 15, 20));
        ContentPanel.setLayout(new javax.swing.BoxLayout(ContentPanel, javax.swing.BoxLayout.Y_AXIS));

        headerContentPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerContentPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 13, 0));
        headerContentPanel.setLayout(new java.awt.BorderLayout(0, 15));

        leftTextPanel.setBackground(new java.awt.Color(255, 255, 255));
        leftTextPanel.setLayout(new javax.swing.BoxLayout(leftTextPanel, javax.swing.BoxLayout.Y_AXIS));

        titlePanel.setBackground(new java.awt.Color(255, 255, 255));
        titlePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel1.setText("Module Performance Report");
        titlePanel.add(jLabel1);

        leftTextPanel.add(titlePanel);

        descPanel.setBackground(new java.awt.Color(255, 255, 255));
        descPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 0));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Shows student performance for your modules, including average marks and pass/fail rates.");
        descPanel.add(jLabel2);

        leftTextPanel.add(descPanel);

        headerContentPanel.add(leftTextPanel, java.awt.BorderLayout.CENTER);

        exportPanel.setBackground(new java.awt.Color(255, 255, 255));
        exportPanel.setLayout(new java.awt.GridBagLayout());

        btnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/export.png"))); // NOI18N
        btnExport.setToolTipText("Export Report");
        btnExport.setBorderPainted(false);
        btnExport.setContentAreaFilled(false);
        btnExport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExport.setFocusPainted(false);
        btnExport.setFocusable(false);
        btnExport.setMargin(new java.awt.Insets(2, 0, 2, 0));
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        exportPanel.add(btnExport, gridBagConstraints);

        headerContentPanel.add(exportPanel, java.awt.BorderLayout.EAST);

        ContentPanel.add(headerContentPanel);

        chartContainerPanel.setBackground(new java.awt.Color(255, 255, 255));
        chartContainerPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 2, 20, 2), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153))));
        chartContainerPanel.setPreferredSize(new java.awt.Dimension(452, 300));
        chartContainerPanel.setRequestFocusEnabled(false);
        chartContainerPanel.setLayout(new java.awt.BorderLayout());

        modulePerformanceBarChartPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout modulePerformanceBarChartPanel1Layout = new javax.swing.GroupLayout(modulePerformanceBarChartPanel1);
        modulePerformanceBarChartPanel1.setLayout(modulePerformanceBarChartPanel1Layout);
        modulePerformanceBarChartPanel1Layout.setHorizontalGroup(
            modulePerformanceBarChartPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );
        modulePerformanceBarChartPanel1Layout.setVerticalGroup(
            modulePerformanceBarChartPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        chartContainerPanel.add(modulePerformanceBarChartPanel1, java.awt.BorderLayout.CENTER);

        ContentPanel.add(chartContainerPanel);

        tableContainerPanel.setBackground(new java.awt.Color(255, 255, 255));
        tableContainerPanel.setPreferredSize(new java.awt.Dimension(452, 335));
        tableContainerPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255));

        tblModulePerformance.setAutoCreateRowSorter(true);
        tblModulePerformance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "moduleId", "Module Code", "Module Name", "Lecturer ID", "Average Marks (%)", "Pass Rate (%)", "Fail Rate (%)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblModulePerformance.setFillsViewportHeight(true);
        tblModulePerformance.setFocusable(false);
        tblModulePerformance.setRowHeight(28);
        tblModulePerformance.setShowGrid(false);
        tblModulePerformance.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblModulePerformance);
        if (tblModulePerformance.getColumnModel().getColumnCount() > 0) {
            tblModulePerformance.getColumnModel().getColumn(0).setMinWidth(0);
            tblModulePerformance.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblModulePerformance.getColumnModel().getColumn(0).setMaxWidth(0);
            tblModulePerformance.getColumnModel().getColumn(1).setPreferredWidth(45);
            tblModulePerformance.getColumnModel().getColumn(2).setPreferredWidth(120);
            tblModulePerformance.getColumnModel().getColumn(3).setPreferredWidth(35);
            tblModulePerformance.getColumnModel().getColumn(4).setPreferredWidth(75);
            tblModulePerformance.getColumnModel().getColumn(5).setPreferredWidth(45);
            tblModulePerformance.getColumnModel().getColumn(6).setPreferredWidth(40);
        }

        tableContainerPanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        ContentPanel.add(tableContainerPanel);

        jScrollPane1.setViewportView(ContentPanel);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        try {
            javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
            chooser.setDialogTitle("Save Report as PDF");

            if (chooser.showSaveDialog(null) != javax.swing.JFileChooser.APPROVE_OPTION) {
                return;
            }

            java.io.File file = chooser.getSelectedFile();
            if (!file.getName().toLowerCase().endsWith(".pdf")) {
                file = new java.io.File(file.getAbsolutePath() + ".pdf");
            }

            boolean exportBtnVisible = btnExport.isVisible();
            btnExport.setVisible(false);
            java.awt.image.BufferedImage headerImg = capturePanel(headerContentPanel);
            btnExport.setVisible(exportBtnVisible);

            java.awt.image.BufferedImage chartImg  = capturePanel(chartContainerPanel);
            java.awt.image.BufferedImage tableImg  = capturePanel(tableContainerPanel);

            com.itextpdf.text.Image header = com.itextpdf.text.Image.getInstance(headerImg, null);
            com.itextpdf.text.Image chart  = com.itextpdf.text.Image.getInstance(chartImg, null);
            com.itextpdf.text.Image table  = com.itextpdf.text.Image.getInstance(tableImg, null);

            float pageWidth =
            com.itextpdf.text.PageSize.A4.getWidth() - 80;

            header.scaleToFit(pageWidth, 200);
            chart.scaleToFit(pageWidth, 400);
            table.scaleToFit(pageWidth, 500);   

            com.itextpdf.text.Document document =
            new com.itextpdf.text.Document(
                com.itextpdf.text.PageSize.A4,
                40, 40, 50, 50
            );

            com.itextpdf.text.pdf.PdfWriter writer =
                com.itextpdf.text.pdf.PdfWriter.getInstance(
                    document,
                    new java.io.FileOutputStream(file)
                );

            writer.setPageEvent(new assessmentfeedbacksystem.PdfHeaderFooter());

            document.open();

            document.add(header);
            document.add(com.itextpdf.text.Chunk.NEWLINE);
            document.add(chart);
            document.add(table);

            document.close();
            
            int choice = javax.swing.JOptionPane.showConfirmDialog(
                null,
                "Report exported successfully.\n\nDo you want to open the PDF now?",
                "Export Complete",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE
            );

            if (choice == javax.swing.JOptionPane.YES_OPTION) {
                if (java.awt.Desktop.isDesktopSupported()) {
                    java.awt.Desktop.getDesktop().open(file);
                }
            }

//            javax.swing.JOptionPane.showMessageDialog(
//                this,
//                "Report exported successfully!",
//                "Export Complete",
//                javax.swing.JOptionPane.INFORMATION_MESSAGE
//            );

        } catch (Exception ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(
                null,
                "Failed to export report.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnExportActionPerformed

    private java.awt.image.BufferedImage capturePanel(javax.swing.JComponent panel) {
        java.awt.image.BufferedImage image =
            new java.awt.image.BufferedImage(
                panel.getWidth(),
                panel.getHeight(),
                java.awt.image.BufferedImage.TYPE_INT_RGB
            );

        java.awt.Graphics2D g2 = image.createGraphics();
        g2.setColor(java.awt.Color.WHITE);
        g2.fillRect(0, 0, image.getWidth(), image.getHeight());
        panel.paint(g2);
        g2.dispose();

        return image;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JButton btnExport;
    private javax.swing.JPanel chartContainerPanel;
    private javax.swing.JPanel descPanel;
    private javax.swing.JPanel exportPanel;
    private javax.swing.JPanel headerContentPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel leftTextPanel;
    private assessmentfeedbacksystem.GUI.AcademicLeader.ModulePerformanceBarChartPanel modulePerformanceBarChartPanel1;
    private javax.swing.JPanel tableContainerPanel;
    private javax.swing.JTable tblModulePerformance;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
