/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.AcademicLeader;

import assessmentfeedbacksystem.AcademicLeader;

/**
 *
 * @author xinyun
 */

public class ModuleManagementPanel extends javax.swing.JPanel {
    
    private AcademicLeader logged_in_al;

    /**
     * Creates new form ModuleManagementPanel
     */
    
    public ModuleManagementPanel() {
        initComponents();
        setupTabListener();
    }
    
    public ModuleManagementPanel(AcademicLeader al) {
        this.logged_in_al = al;
        initComponents();
        setupTabListener();
    }
    
    private void setupTabListener() {
        tabMain.addChangeListener(e -> {
            if (tabMain.getSelectedComponent() == pnlActive) {
                activeModuleContainerPanel1.showTable(); 
            } else if (tabMain.getSelectedComponent() == pnlInactive) {
                inactiveModuleContainerPanel1.showTable(); 
            }
        });
    }
    
    public javax.swing.JTabbedPane getTabMain() {
        return tabMain;
    }

    public javax.swing.JPanel getPnlInactive() {
        return pnlInactive;
    }

    public InactiveModuleContainerPanel getInactiveModuleContainerPanel() {
        return inactiveModuleContainerPanel1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerMain = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tabMain = new javax.swing.JTabbedPane();
        pnlActive = new javax.swing.JPanel();
        activeModuleContainerPanel1 = new assessmentfeedbacksystem.GUI.AcademicLeader.ActiveModuleContainerPanel(logged_in_al);
        pnlInactive = new javax.swing.JPanel();
        inactiveModuleContainerPanel1 = new assessmentfeedbacksystem.GUI.AcademicLeader.InactiveModuleContainerPanel(logged_in_al);

        setBackground(new java.awt.Color(237, 241, 246));
        setPreferredSize(new java.awt.Dimension(770, 540));
        setLayout(new java.awt.BorderLayout(15, 5));

        headerMain.setBackground(new java.awt.Color(237, 241, 246));
        headerMain.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        headerPanel.setBackground(new java.awt.Color(237, 241, 246));
        headerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 19, 0, 5));
        headerPanel.setLayout(new javax.swing.BoxLayout(headerPanel, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Module Management");
        headerPanel.add(jLabel1);

        jPanel2.setBackground(new java.awt.Color(237, 241, 246));
        headerPanel.add(jPanel2);

        headerMain.add(headerPanel);

        add(headerMain, java.awt.BorderLayout.PAGE_START);

        tabMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 35, 20, 35));
        tabMain.setFocusable(false);

        pnlActive.setBackground(new java.awt.Color(237, 241, 246));
        pnlActive.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 12, 12, 12));
        pnlActive.setLayout(new java.awt.BorderLayout());
        pnlActive.add(activeModuleContainerPanel1, java.awt.BorderLayout.CENTER);

        tabMain.addTab("Active Modules", pnlActive);

        pnlInactive.setBackground(new java.awt.Color(237, 241, 246));
        pnlInactive.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 12, 12, 12));
        pnlInactive.setLayout(new java.awt.BorderLayout());
        pnlInactive.add(inactiveModuleContainerPanel1, java.awt.BorderLayout.CENTER);

        tabMain.addTab("Inactive Modules", pnlInactive);

        add(tabMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private assessmentfeedbacksystem.GUI.AcademicLeader.ActiveModuleContainerPanel activeModuleContainerPanel1;
    private javax.swing.JPanel headerMain;
    private javax.swing.JPanel headerPanel;
    private assessmentfeedbacksystem.GUI.AcademicLeader.InactiveModuleContainerPanel inactiveModuleContainerPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlActive;
    private javax.swing.JPanel pnlInactive;
    private javax.swing.JTabbedPane tabMain;
    // End of variables declaration//GEN-END:variables
}
