/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.AcademicLeader;

import assessmentfeedbacksystem.AcademicLeader;

/**
 *
 * @author xinyun
 */

public class ProfileDetailPanel extends javax.swing.JPanel {
    
    private AcademicLeader logged_in_user;
    private ProfileContainerPanel parent;
    
    /**
     * Creates new form ActiveModuleDetailPanel
     */
    
    public ProfileDetailPanel() {
        initComponents();
    }
    
    public ProfileDetailPanel(ProfileContainerPanel parent, AcademicLeader logged_in_user) {
        this.parent = parent;
        this.logged_in_user = logged_in_user;
        initComponents();
        setUser(logged_in_user);
    }
    
    public void setUser(AcademicLeader user) {
        if (user == null) {
            // Design-time or not logged in yet
            clearFields();
            return;
        }
        
        this.logged_in_user = user;

        lblUserIDValue.setText(user.getUser_id());
        lblUserNameValue.setText(user.getName());
        lblEmailAddressValue.setText(user.getEmail());
        lblContactNumberValue.setText(user.getContact_no());
        
        String gender = user.getGender();
        if (gender == null) {
            lblGenderValue.setText("-");
        } else if (gender.equalsIgnoreCase("M")) {
            lblGenderValue.setText("Male");
        } else if (gender.equalsIgnoreCase("F")) {
            lblGenderValue.setText("Female");
        } else {
            lblGenderValue.setText(gender);
        }

        lblDOBValue.setText(
            user.getDob() != null ? user.getDob().toString() : "-"
        );
        lblRoleValue.setText(user.getRole());
        lblDepartmentValue.setText(
            user.getDepartment() != null ? user.getDepartment() : "-"
        );

        lblPasswordValue.setText("********");
    }
    
    private void clearFields() {
        lblUserIDValue.setText("-");
        lblUserNameValue.setText("-");
        lblEmailAddressValue.setText("-");
        lblContactNumberValue.setText("-");
        lblGenderValue.setText("-");
        lblDOBValue.setText("-");
        lblRoleValue.setText("-");
        lblDepartmentValue.setText("-");
        lblPasswordValue.setText("********");
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        headerPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bodyPanel = new javax.swing.JPanel();
        detailContentPanel = new javax.swing.JPanel();
        profileIconPanel = new javax.swing.JPanel();
        profileIcon = new javax.swing.JLabel();
        lblUserID = new javax.swing.JLabel();
        lblUserIDValue = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblRoleValue = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblUserNameValue = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        lblEmailAddressValue = new javax.swing.JLabel();
        lblContactNumber = new javax.swing.JLabel();
        lblContactNumberValue = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblGenderValue = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblDOBValue = new javax.swing.JLabel();
        lblDepartment = new javax.swing.JLabel();
        lblDepartmentValue = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblPasswordValue = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();

        setBackground(new java.awt.Color(237, 241, 246));
        setLayout(new java.awt.BorderLayout(15, 5));

        headerPanel.setBackground(new java.awt.Color(237, 241, 246));
        headerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        titlePanel.setBackground(new java.awt.Color(237, 241, 246));
        titlePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 15, 10, 5));
        titlePanel.setLayout(new javax.swing.BoxLayout(titlePanel, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Profile Detail");
        titlePanel.add(jLabel1);

        jPanel1.setBackground(new java.awt.Color(237, 241, 246));
        titlePanel.add(jPanel1);

        headerPanel.add(titlePanel);

        add(headerPanel, java.awt.BorderLayout.PAGE_START);

        bodyPanel.setBackground(new java.awt.Color(237, 241, 246));
        bodyPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 35, 30, 35));
        bodyPanel.setLayout(new javax.swing.BoxLayout(bodyPanel, javax.swing.BoxLayout.Y_AXIS));

        detailContentPanel.setBackground(new java.awt.Color(255, 255, 255));
        detailContentPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 0, 20));
        detailContentPanel.setLayout(new java.awt.GridBagLayout());

        profileIconPanel.setBackground(new java.awt.Color(247, 247, 247));
        profileIconPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        profileIconPanel.setPreferredSize(new java.awt.Dimension(180, 180));
        profileIconPanel.setLayout(new java.awt.BorderLayout());

        profileIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit profile.png"))); // NOI18N
        profileIcon.setAlignmentX(0.5F);
        profileIconPanel.add(profileIcon, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.insets = new java.awt.Insets(30, 5, 30, 30);
        detailContentPanel.add(profileIconPanel, gridBagConstraints);

        lblUserID.setForeground(new java.awt.Color(102, 102, 102));
        lblUserID.setText("User ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblUserID, gridBagConstraints);

        lblUserIDValue.setBackground(new java.awt.Color(225, 236, 247));
        lblUserIDValue.setText("[User ID Value]");
        lblUserIDValue.setToolTipText("");
        lblUserIDValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblUserIDValue.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblUserIDValue, gridBagConstraints);

        lblRole.setForeground(new java.awt.Color(102, 102, 102));
        lblRole.setText("Role");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblRole, gridBagConstraints);

        lblRoleValue.setBackground(new java.awt.Color(225, 236, 247));
        lblRoleValue.setText("[Role Value]");
        lblRoleValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblRoleValue.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblRoleValue, gridBagConstraints);

        lblUserName.setForeground(new java.awt.Color(102, 102, 102));
        lblUserName.setText("User Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblUserName, gridBagConstraints);

        lblUserNameValue.setBackground(new java.awt.Color(225, 236, 247));
        lblUserNameValue.setText("[User Name Value]");
        lblUserNameValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblUserNameValue.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblUserNameValue, gridBagConstraints);

        lblEmailAddress.setForeground(new java.awt.Color(102, 102, 102));
        lblEmailAddress.setText("Email Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblEmailAddress, gridBagConstraints);

        lblEmailAddressValue.setBackground(new java.awt.Color(225, 236, 247));
        lblEmailAddressValue.setText("[Email Address Value]");
        lblEmailAddressValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblEmailAddressValue.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblEmailAddressValue, gridBagConstraints);

        lblContactNumber.setForeground(new java.awt.Color(102, 102, 102));
        lblContactNumber.setText("Contact Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblContactNumber, gridBagConstraints);

        lblContactNumberValue.setBackground(new java.awt.Color(225, 236, 247));
        lblContactNumberValue.setText("[Contact Number Value]");
        lblContactNumberValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblContactNumberValue.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblContactNumberValue, gridBagConstraints);

        lblGender.setForeground(new java.awt.Color(102, 102, 102));
        lblGender.setText("Gender");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblGender, gridBagConstraints);

        lblGenderValue.setBackground(new java.awt.Color(225, 236, 247));
        lblGenderValue.setText("[Gender Value]");
        lblGenderValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblGenderValue.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblGenderValue, gridBagConstraints);

        lblDOB.setForeground(new java.awt.Color(102, 102, 102));
        lblDOB.setText("DOB");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblDOB, gridBagConstraints);

        lblDOBValue.setBackground(new java.awt.Color(225, 236, 247));
        lblDOBValue.setText("[DOB Value]");
        lblDOBValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblDOBValue.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblDOBValue, gridBagConstraints);

        lblDepartment.setForeground(new java.awt.Color(102, 102, 102));
        lblDepartment.setText("Department");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblDepartment, gridBagConstraints);

        lblDepartmentValue.setBackground(new java.awt.Color(225, 236, 247));
        lblDepartmentValue.setText("[Department Value]");
        lblDepartmentValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblDepartmentValue.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblDepartmentValue, gridBagConstraints);

        lblPassword.setForeground(new java.awt.Color(102, 102, 102));
        lblPassword.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblPassword, gridBagConstraints);

        lblPasswordValue.setBackground(new java.awt.Color(225, 236, 247));
        lblPasswordValue.setText("[Password Value]");
        lblPasswordValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblPasswordValue.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblPasswordValue, gridBagConstraints);

        bodyPanel.add(detailContentPanel);

        buttonPanel.setBackground(new java.awt.Color(255, 255, 255));
        buttonPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 12, 12, 12));

        btnEdit.setBackground(new java.awt.Color(45, 94, 168));
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit Profile");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.setFocusPainted(false);
        btnEdit.setFocusable(false);
        btnEdit.setPreferredSize(new java.awt.Dimension(100, 30));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        buttonPanel.add(btnEdit);

        bodyPanel.add(buttonPanel);

        add(bodyPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (parent != null) {
            parent.showEdit();
        }
    }//GEN-LAST:event_btnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel detailContentPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContactNumber;
    private javax.swing.JLabel lblContactNumberValue;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDOBValue;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblDepartmentValue;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblEmailAddressValue;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGenderValue;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordValue;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblRoleValue;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JLabel lblUserIDValue;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserNameValue;
    private javax.swing.JLabel profileIcon;
    private javax.swing.JPanel profileIconPanel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
