/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.AcademicLeader;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author xinyun
 */
public class ProgressCirclePanel extends javax.swing.JPanel {
    
    private int percentage = 60;

    public void setPercentage(int p) {
        percentage = p;
        repaint();
    }

    /**
     * Creates new form ProgressCirclePanel
     */
    public ProgressCirclePanel() {
        initComponents();
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        int size = Math.min(getWidth(), getHeight()) - 20;
        int x = (getWidth() - size) / 2;
        int y = (getHeight() - size) / 2;

        // background circle
        g2.setStroke(new BasicStroke(8));
//        g2.setColor(new Color(230, 230, 230));
        g2.setColor(new Color(226, 232, 240));
        g2.drawOval(x, y, size, size);

        // progress arc
//        g2.setColor(new Color(88, 101, 242)); 
//        g2.setColor(new Color(220, 38, 38)); 
        g2.setColor(new Color(37, 99, 235)); 
        g2.drawArc(x, y, size, size, 90, -percentage * 360 / 100);

        // percentage text
        g2.setColor(new Color(30, 41, 59));
        g2.setFont(new Font("Helvetica Neue", Font.BOLD, 18));
        String txt = percentage + "%";
        FontMetrics fm = g2.getFontMetrics();
        g2.drawString(txt, getWidth()/2 - fm.stringWidth(txt)/2, getHeight()/2 + 6);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
