/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.AcademicLeader;

import assessmentfeedbacksystem.AcademicLeader;

/**
 *
 * @author xinyun
 */
public class ReportManagementPanel extends javax.swing.JPanel {
    
    private AcademicLeader logged_in_al;

    /**
     * Creates new form ReportMainPanel
     */
    public ReportManagementPanel() {
        initComponents();
    }
    
    public ReportManagementPanel(AcademicLeader al) {
        this.logged_in_al = al;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerMain = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tabMain = new javax.swing.JTabbedPane();
        pnlModulePerformanceReport = new javax.swing.JPanel();
        modulePerformanceReportPanel1 = new assessmentfeedbacksystem.GUI.AcademicLeader.ModulePerformanceReportPanel(logged_in_al);
        pnlLecturerPerformanceReport = new javax.swing.JPanel();
        lecturerPerformanceReportPanel1 = new assessmentfeedbacksystem.GUI.AcademicLeader.LecturerPerformanceReportPanel(logged_in_al);
        pnlLecturerAllocationReport = new javax.swing.JPanel();
        departmentLecturerAllocationReportPanel1 = new assessmentfeedbacksystem.GUI.AcademicLeader.DepartmentLecturerAllocationReportPanel(logged_in_al);
        pnlClassEnrolmentReport = new javax.swing.JPanel();
        classEnrolmentReportPanel1 = new assessmentfeedbacksystem.GUI.AcademicLeader.ClassEnrolmentReportPanel(logged_in_al);
        pnlGradeDistributionReport = new javax.swing.JPanel();
        gradeDistributionReportPanel1 = new assessmentfeedbacksystem.GUI.AcademicLeader.GradeDistributionReportPanel(logged_in_al);

        setBackground(new java.awt.Color(237, 241, 246));
        setLayout(new java.awt.BorderLayout(15, 5));

        headerMain.setBackground(new java.awt.Color(237, 241, 246));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5);
        flowLayout1.setAlignOnBaseline(true);
        headerMain.setLayout(flowLayout1);

        headerPanel.setBackground(new java.awt.Color(237, 241, 246));
        headerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 19, 0, 5));
        headerPanel.setLayout(new javax.swing.BoxLayout(headerPanel, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setBackground(new java.awt.Color(237, 241, 246));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Report Management");
        headerPanel.add(jLabel1);

        jPanel1.setBackground(new java.awt.Color(237, 241, 246));
        headerPanel.add(jPanel1);

        headerMain.add(headerPanel);

        add(headerMain, java.awt.BorderLayout.PAGE_START);

        tabMain.setBackground(new java.awt.Color(237, 241, 246));
        tabMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 35, 20, 35));
        tabMain.setFocusable(false);

        pnlModulePerformanceReport.setBackground(new java.awt.Color(237, 241, 246));
        pnlModulePerformanceReport.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 12, 12, 12));
        pnlModulePerformanceReport.setLayout(new java.awt.BorderLayout());
        pnlModulePerformanceReport.add(modulePerformanceReportPanel1, java.awt.BorderLayout.CENTER);

        tabMain.addTab("Module Performance", pnlModulePerformanceReport);

        pnlLecturerPerformanceReport.setBackground(new java.awt.Color(237, 241, 246));
        pnlLecturerPerformanceReport.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 12, 12, 12));
        pnlLecturerPerformanceReport.setLayout(new java.awt.BorderLayout());
        pnlLecturerPerformanceReport.add(lecturerPerformanceReportPanel1, java.awt.BorderLayout.CENTER);

        tabMain.addTab("Lecturer Performance", pnlLecturerPerformanceReport);

        pnlLecturerAllocationReport.setBackground(new java.awt.Color(237, 241, 246));
        pnlLecturerAllocationReport.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 12, 12, 12));
        pnlLecturerAllocationReport.setLayout(new java.awt.BorderLayout());
        pnlLecturerAllocationReport.add(departmentLecturerAllocationReportPanel1, java.awt.BorderLayout.CENTER);

        tabMain.addTab("Lecturer Allocation ", pnlLecturerAllocationReport);

        pnlClassEnrolmentReport.setBackground(new java.awt.Color(237, 241, 246));
        pnlClassEnrolmentReport.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 12, 12, 12));
        pnlClassEnrolmentReport.setLayout(new java.awt.BorderLayout());
        pnlClassEnrolmentReport.add(classEnrolmentReportPanel1, java.awt.BorderLayout.CENTER);

        tabMain.addTab("Class Enrolment", pnlClassEnrolmentReport);

        pnlGradeDistributionReport.setBackground(new java.awt.Color(237, 241, 246));
        pnlGradeDistributionReport.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 12, 12, 12));
        pnlGradeDistributionReport.setLayout(new java.awt.BorderLayout());
        pnlGradeDistributionReport.add(gradeDistributionReportPanel1, java.awt.BorderLayout.CENTER);

        tabMain.addTab("Grade Distribution", pnlGradeDistributionReport);

        add(tabMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private assessmentfeedbacksystem.GUI.AcademicLeader.ClassEnrolmentReportPanel classEnrolmentReportPanel1;
    private assessmentfeedbacksystem.GUI.AcademicLeader.DepartmentLecturerAllocationReportPanel departmentLecturerAllocationReportPanel1;
    private assessmentfeedbacksystem.GUI.AcademicLeader.GradeDistributionReportPanel gradeDistributionReportPanel1;
    private javax.swing.JPanel headerMain;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private assessmentfeedbacksystem.GUI.AcademicLeader.LecturerPerformanceReportPanel lecturerPerformanceReportPanel1;
    private assessmentfeedbacksystem.GUI.AcademicLeader.ModulePerformanceReportPanel modulePerformanceReportPanel1;
    private javax.swing.JPanel pnlClassEnrolmentReport;
    private javax.swing.JPanel pnlGradeDistributionReport;
    private javax.swing.JPanel pnlLecturerAllocationReport;
    private javax.swing.JPanel pnlLecturerPerformanceReport;
    private javax.swing.JPanel pnlModulePerformanceReport;
    private javax.swing.JTabbedPane tabMain;
    // End of variables declaration//GEN-END:variables
}
