/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assessmentfeedbacksystem.GUI.AdminStaff;

import assessmentfeedbacksystem.AdminStaff;
import assessmentfeedbacksystem.ClassModel;
import assessmentfeedbacksystem.Module;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.stream.Collectors;
import javax.swing.event.*;
import javax.swing.*;

/**
 *
 * @author samanthawoo
 */
public class CreateClassFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateClassFrame.class.getName());
    private AdminStaff logged_in_admin;
    private int[] duration_in_minutes = {30, 60, 90, 120};

    
    /**
     * Creates new form CreateClassFrame
     */
    public CreateClassFrame(AdminStaff admin) {
  
        initComponents();
        
        this.logged_in_admin = admin;
        
        // Display Module ID
        List<Module> allModules = Module.getAllModules();
        List<ClassModel> allClasses = ClassModel.readAllClasses();
        Set<String> usedModuleIds = allClasses.stream() // loop one by one
                                              .map(c -> c.getModule().getModuleId()) // return module id
                                              .collect(Collectors.toSet()); // put into set
        moduleIdComboBox.removeAllItems();
        for(Module module: allModules){
            if(!usedModuleIds.contains(module.getModuleId())){
                moduleIdComboBox.addItem(module.getModuleId());
            }
        }
        
        // Initial display
        updateModuleName(allModules);

        // Switch module name text
        moduleIdComboBox.addActionListener(e -> updateModuleName(allModules));
        
        // If no module available disabled all input
        if (moduleIdComboBox.getItemCount() == 0) {
            moduleIdComboBox.setEnabled(false);
            className_field.setEnabled(false);
            dayComboBox.setEnabled(false);
            durationComboBox.setEnabled(false);
            startTimeSpinner.setEnabled(false);
            endTimeSpinner.setEnabled(false);
            createButton.setEnabled(false);
            JOptionPane.showMessageDialog(this, "All modules already have classes. Cannot create new class.");
        }
        
        // Identify Class ID
        classId_field.setText(generateClassId());
        classId_field.setEditable(false);
        
        // Set up duration
        durationComboBox.removeAllItems();
        for (int mins : duration_in_minutes) {
            String text = (mins >= 60) ? (mins / 60) + "h " + (mins % 60) + "m" : mins + " mins";
            durationComboBox.addItem(text);
        }
        
        setUpStartTimeSpinner();
        setUpEndTimeSpinner();

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        moduleIdComboBox = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        classId_field = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        className_field = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dayComboBox = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        durationComboBox = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        startTimeSpinner = new javax.swing.JSpinner();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        endTimeSpinner = new javax.swing.JSpinner();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        moduleNameLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        previousButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        createButton.setOpaque(true);
        createButton.setContentAreaFilled(true);
        createButton.setBackground(new java.awt.Color(85, 128, 176));
        createButton.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        createButton.setForeground(new java.awt.Color(255, 255, 255));
        createButton.setText("Create Class");
        createButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        createButton.addActionListener(this::createButtonActionPerformed);

        jPanel1.setBackground(new java.awt.Color(85, 128, 176));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Class Administration");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(80, 158, 78), 2));
        jPanel2.setMaximumSize(new java.awt.Dimension(778, 322));
        jPanel2.setMinimumSize(new java.awt.Dimension(778, 322));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(341, 26));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel7.setText("Module ID:");

        moduleIdComboBox.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        moduleIdComboBox.setPreferredSize(new java.awt.Dimension(63, 26));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(moduleIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(moduleIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(341, 26));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel1.setText("Class ID:");

        classId_field.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(classId_field, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addComponent(classId_field)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(341, 26));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel2.setText("Class Name:");

        className_field.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        className_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(className_field, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2))
            .addComponent(className_field, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(341, 26));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel3.setText("Day:");

        dayComboBox.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        dayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(dayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3))
            .addComponent(dayComboBox)
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(341, 26));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel4.setText("Duration:");

        durationComboBox.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        durationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(durationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4))
            .addComponent(durationComboBox)
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(341, 26));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel5.setText("Start Time:");

        startTimeSpinner.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(startTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5))
            .addComponent(startTimeSpinner)
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(341, 26));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel6.setText("End Time:");

        endTimeSpinner.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(endTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(endTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel9.setText("Module Name:");

        moduleNameLabel.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 97, Short.MAX_VALUE))
                    .addComponent(moduleNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(moduleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        previousButton.setOpaque(true);
        previousButton.setContentAreaFilled(true);
        previousButton.setBackground(new java.awt.Color(85, 128, 176));
        previousButton.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        previousButton.setForeground(new java.awt.Color(255, 255, 255));
        previousButton.setText("Previous");
        previousButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        previousButton.addActionListener(this::previousButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(previousButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(503, 503, 503)
                        .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previousButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        
        if (!checkValidation()) {
            return;
        }
        
        String module_id = moduleIdComboBox.getSelectedItem().toString();
        String class_id = classId_field.getText();
        String class_name = className_field.getText();
        DayOfWeek day = DayOfWeek.valueOf(dayComboBox.getSelectedItem().toString().toUpperCase());
        String durationText = durationComboBox.getSelectedItem().toString();
        String startTimeText = startTimeSpinner.getValue().toString();
        String endTimeText = endTimeSpinner.getValue().toString();
        
        // Module Object
        Module selected_module = new Module(module_id);
        
        // Convertion (Duration)
        int totalMinutes = 0;

        if (durationText.contains("h")) {
            String[] parts = durationText.split("h");
            int hours = Integer.parseInt(parts[0].trim());
            int minutes = Integer.parseInt(parts[1].replace("m", "").trim());
            totalMinutes = hours * 60 + minutes;
        } else {
            totalMinutes = Integer.parseInt(durationText.replace("mins", "").trim());
        }

        Duration duration = Duration.ofMinutes(totalMinutes);
        
        // Convertion (Start Time/End Time)
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("E MMM dd HH:mm:ss O yyyy", Locale.ENGLISH);
        LocalTime startTime = LocalTime.parse(startTimeText, formatter);
        LocalTime endTime = LocalTime.parse(endTimeText, formatter);
        
        String created_by = logged_in_admin.getUser_id();

        LocalDate date = LocalDate.now(); 
        
        ClassModel cm = new ClassModel(
            class_id, 
            class_name, 
            day, 
//            duration, s
            startTime, 
            endTime, 
            created_by, 
            date,
            selected_module
        );

        String[] create_class_status = logged_in_admin.createClassGroup(cm);

        boolean status = Boolean.parseBoolean(create_class_status[0]);
        String status_message = create_class_status[1];
        
        if(status){
            
            // Clear input
            moduleIdComboBox.setSelectedIndex(0);
//            classId_field.setText(generateClassId());
            dayComboBox.setSelectedIndex(0);
            durationComboBox.setSelectedIndex(0);
            setUpStartTimeSpinner();
            setUpEndTimeSpinner();
            
            JOptionPane.showMessageDialog(this, 
                "Class created successfully!\nClass ID: " + class_id + 
                "\nModule: " + selected_module.getModuleId() + 
                "\nDate Created: " + date, 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE
            );

            AdminDashboardFrame adf = new AdminDashboardFrame(logged_in_admin);
            adf.setVisible(true);
            this.dispose();
            
        }else{
            
            JOptionPane.showMessageDialog(this, 
                "Failed to create class.\nReason: " + status_message, 
                "Error", 
                JOptionPane.ERROR_MESSAGE
            );
            
        }
        
    }//GEN-LAST:event_createButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        AdminDashboardFrame adf = new AdminDashboardFrame(logged_in_admin);
        adf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_previousButtonActionPerformed

    public boolean checkValidation() {

        if (moduleIdComboBox.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select a module.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            moduleIdComboBox.requestFocus();
            return false;
        }

        String className = className_field.getText().trim();
        if (className.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Class name cannot be empty.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            className_field.requestFocus();
            return false;
        }
        if (className.length() < 2 || className.length() > 50) {
            JOptionPane.showMessageDialog(this, "Class name must be between 2 and 50 characters.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            className_field.requestFocus();
            return false;
        }

        if (dayComboBox.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select a day.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            dayComboBox.requestFocus();
            return false;
        }

        if (durationComboBox.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select a duration.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            durationComboBox.requestFocus();
            return false;
        }

        Date startTime = (Date) startTimeSpinner.getValue();
        if (startTime == null) {
            JOptionPane.showMessageDialog(this, "Please select a valid start time.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            startTimeSpinner.requestFocus();
            return false;
        }

        Date endTime = (Date) endTimeSpinner.getValue();
        if (endTime == null) {
            JOptionPane.showMessageDialog(this, "End time cannot be empty.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            endTimeSpinner.requestFocus();
            return false;
        }

        return true;
    }

    
    public String generateClassId(){
        
        String prefix = "C";
        int max_number = 0;
        
        List<ClassModel> allClasses = ClassModel.readAllClasses();
        for(ClassModel c: allClasses){
            String class_id = c.getClassId();
            System.out.println("Class ID: " + class_id);
            
            if(class_id.startsWith(prefix)){
                
                // cut off part
                String numeric_part = class_id.substring(prefix.length());
                try{
                    int num = Integer.parseInt(numeric_part);
                    if(num > max_number){
                        max_number = num;
                    }
                }catch(NumberFormatException e){
                    System.out.println("Skipping invalid class ID: " + class_id);
                }
                
            }
        }
        
        int new_number = max_number + 1;
        return prefix + String.format("%03d", new_number);
    }
    
    public void setUpStartTimeSpinner(){
        
        // Set start time picker
        String minStr = "08:00";
        String maxStr = "18:00";

        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");

        try {
            Date minTime = sdf.parse(minStr);
            Date maxTime = sdf.parse(maxStr);
            Date initial = minTime;

            startTimeSpinner.setModel(new SpinnerDateModel(initial, minTime, maxTime, Calendar.MINUTE){
                @Override
                public Object getNextValue() {
                    return adjust((Date) super.getNextValue(), true);
                }

                @Override
                public Object getPreviousValue() {
                    return adjust((Date) super.getPreviousValue(), false);
                }

                private Date adjust(Date date, boolean next) {
                    Calendar cal = Calendar.getInstance();
                    cal.setTime(date);
                    int minutes = cal.get(Calendar.MINUTE);

                    if (next) {
                        minutes = ((minutes + 14) / 15) * 15; // round up
                        if (minutes >= 60) {
                            cal.add(Calendar.HOUR_OF_DAY, 1);
                            minutes = 0;
                        }
                    } else {
                        minutes = (minutes / 15) * 15; // round down
                    }

                    cal.set(Calendar.MINUTE, minutes);
                    cal.set(Calendar.SECOND, 0);
                    cal.set(Calendar.MILLISECOND, 0);

                    // Clamp to min/max
                    if (cal.getTime().before((Date) getStart())) cal.setTime((Date) getStart());
                    if (cal.getTime().after((Date) getEnd())) cal.setTime((Date) getEnd());

                    return cal.getTime();
                }
            });

        } catch (ParseException e) {
            e.printStackTrace();
        }
        
        // Editor to display HH:mm
        JSpinner.DateEditor editor = new JSpinner.DateEditor(startTimeSpinner, "HH:mm");
        startTimeSpinner.setEditor(editor);
        
        startTimeSpinner.addChangeListener(e -> {
            Date value = (Date) startTimeSpinner.getValue();
            Calendar cal = Calendar.getInstance();
            cal.setTime(value);

            int minutes = cal.get(Calendar.MINUTE);
            // Round to nearest 15
            minutes = (int) (Math.round(minutes / 15.0) * 15);
            if (minutes >= 60) {
                cal.add(Calendar.HOUR_OF_DAY, 1);
                minutes = 0;
            }
            cal.set(Calendar.MINUTE, minutes);
            cal.set(Calendar.SECOND, 0);
            cal.set(Calendar.MILLISECOND, 0);

            Date adjusted = cal.getTime();

            // Update spinner if changed
            if (!value.equals(adjusted)) {
                startTimeSpinner.setValue(adjusted);
            }
        });
        
    }
    
    public void setUpEndTimeSpinner(){
        
        Calendar cal = Calendar.getInstance();
        cal.setTime((Date) startTimeSpinner.getValue()); // initial start time
        int initialDuration = duration_in_minutes[0]; // first item in duration array
        cal.add(Calendar.MINUTE, initialDuration);
        Date initialEndTime = cal.getTime();

        SpinnerDateModel endTimeModel = new SpinnerDateModel(initialEndTime, null, null, Calendar.MINUTE);
        endTimeSpinner.setModel(endTimeModel);

        // Make endTimeSpinner read-only
        JFormattedTextField endEditor = ((JSpinner.DefaultEditor) endTimeSpinner.getEditor()).getTextField();
        endEditor.setEditable(false);
        endTimeSpinner.setEditor(new JSpinner.DateEditor(endTimeSpinner, "HH:mm"));

        // --- Update endTimeSpinner whenever startTime or duration changes ---
        ChangeListener updateEndTime = e -> {
            Date start = (Date) startTimeSpinner.getValue();

            int selectedIndex = durationComboBox.getSelectedIndex();
            int duration = duration_in_minutes[Math.max(selectedIndex, 0)]; // fallback to first if none selected

            Calendar c = Calendar.getInstance();
            c.setTime(start);
            c.add(Calendar.MINUTE, duration);

            endTimeSpinner.setValue(c.getTime());
        };
        
        // Attach listener to startTimeSpinner
        startTimeSpinner.addChangeListener(updateEndTime);

        // Attach listener to durationComboBox
        durationComboBox.addActionListener(e -> updateEndTime.stateChanged(null));
        
        endTimeSpinner.setEnabled(false);
        
    }
    
    // switch module name
    private void updateModuleName(List<Module> allModules) {
        String selectedModuleId = (String) moduleIdComboBox.getSelectedItem();

        if (selectedModuleId == null) {
            moduleNameLabel.setText("");
            return;
        }

        for (Module module : allModules) {
            if (module.getModuleId().equals(selectedModuleId)) {
                moduleNameLabel.setText(module.getModuleName());

                return;
            }
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new CreateClassFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField classId_field;
    private javax.swing.JTextField className_field;
    private javax.swing.JButton createButton;
    private javax.swing.JComboBox<String> dayComboBox;
    private javax.swing.JComboBox<String> durationComboBox;
    private javax.swing.JSpinner endTimeSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> moduleIdComboBox;
    private javax.swing.JLabel moduleNameLabel;
    private javax.swing.JButton previousButton;
    private javax.swing.JSpinner startTimeSpinner;
    // End of variables declaration//GEN-END:variables
}
