/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assessmentfeedbacksystem.GUI.AdminStaff;

import assessmentfeedbacksystem.AcademicLeader;
import assessmentfeedbacksystem.AdminStaff;
import assessmentfeedbacksystem.User;
import java.util.*;
import javax.swing.*;
import javax.swing.event.*;
import java.time.*;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

// Future Improvement:
// 1. Change age to dob
// 2. relationship between AL and L must under same dept

/**
 *
 * @author samanthawoo
 */
public class CreateUserFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateUserFrame.class.getName());
    private AdminStaff logged_in_admin;
    
    // Not sure whether should department list put at here
    private String[] departments = {
        "Computing",
        "Psychology",
        "Business"
    };
    DefaultComboBoxModel<String> leaderModel = new DefaultComboBoxModel<>();

    /**
     * Creates new form CreateUserFrame
     * @param admin
     */
    public CreateUserFrame(AdminStaff admin) {
        initComponents();
        
        this.logged_in_admin = admin;
        
        departmentPanel.setVisible(false);
        leaderPanel.setVisible(false);
        createUserButton.setEnabled(false);
        
        List<User> allUsers = logged_in_admin.readUser();
        for(User u: allUsers){
            if(u instanceof AcademicLeader){
                leaderModel.addElement(u.getUser_id());
            }
        }
        
        // Set Id field
        id_field.setEditable(false);
        
        addFieldListeners();
        
        // Capitalize letter
        ((AbstractDocument) name_field.getDocument()).setDocumentFilter(new CapitalizeFilter());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        createUserButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        roleComboBox = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        password_field = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        id_field = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        name_field = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        email_field = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        dobChooser = new com.toedter.calendar.JDateChooser();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        contact_no_field = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        departmentPanel = new javax.swing.JPanel();
        departmentComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        leaderPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        leaderComboBox = new javax.swing.JComboBox<>();
        previousButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create User Panel");
        setResizable(false);

        createUserButton.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        createUserButton.setText("Create User");
        createUserButton.addActionListener(this::createUserButtonActionPerformed);

        jPanel1.setBackground(new java.awt.Color(70, 130, 180));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Create User – Admin Dashboard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(272, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(272, 272, 272))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel14)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(80, 158, 78), 2));

        jLabel2.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Create User");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel7.setText("Role:");

        roleComboBox.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        roleComboBox.setForeground(new java.awt.Color(102, 102, 102));
        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Role", "Academic Leader", "Lecturer", "Student" }));
        roleComboBox.addActionListener(this::roleComboBoxActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel13.setText("Password:");

        password_field.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        password_field.setForeground(new java.awt.Color(102, 102, 102));
        password_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(password_field)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(80, 158, 78), 2));

        jLabel3.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Common Information");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(341, 26));

        id_field.setBackground(new java.awt.Color(230, 230, 230));
        id_field.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        id_field.setPreferredSize(new java.awt.Dimension(72, 26));

        jLabel4.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel4.setText("ID:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(id_field, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(id_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(341, 26));

        jLabel5.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel5.setText("Name:");

        name_field.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        name_field.setForeground(new java.awt.Color(51, 51, 51));
        name_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        name_field.setPreferredSize(new java.awt.Dimension(72, 26));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(341, 26));
        jPanel8.setSize(new java.awt.Dimension(341, 26));

        jLabel6.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel6.setText("Email:");

        email_field.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        email_field.setForeground(new java.awt.Color(51, 51, 51));
        email_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6))
            .addComponent(email_field, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(341, 26));
        jPanel9.setSize(new java.awt.Dimension(341, 26));

        jLabel1.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel1.setText("Gender:");

        genderComboBox.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        genderComboBox.setForeground(new java.awt.Color(102, 102, 102));
        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        genderComboBox.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addComponent(genderComboBox)
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(341, 26));
        jPanel10.setSize(new java.awt.Dimension(341, 26));

        jLabel8.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel8.setText("Date of Birth:");

        dobChooser.setBackground(new java.awt.Color(255, 255, 255));
        dobChooser.setForeground(new java.awt.Color(51, 51, 51));
        dobChooser.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(dobChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8))
            .addComponent(dobChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(341, 26));
        jPanel11.setSize(new java.awt.Dimension(341, 26));

        jLabel9.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel9.setText("Phone Number:");

        contact_no_field.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        contact_no_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(contact_no_field, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9))
            .addComponent(contact_no_field, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(80, 158, 78), 2));

        jLabel10.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel10.setText("Role-Specific Information");

        departmentPanel.setBackground(new java.awt.Color(255, 255, 255));
        departmentPanel.setPreferredSize(new java.awt.Dimension(341, 26));
        departmentPanel.setSize(new java.awt.Dimension(341, 26));

        departmentComboBox.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        departmentComboBox.setForeground(new java.awt.Color(102, 102, 102));
        departmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(departments));
        departmentComboBox.setPreferredSize(new java.awt.Dimension(78, 23));
        departmentComboBox.setSize(new java.awt.Dimension(78, 23));

        jLabel11.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel11.setText("Department:");

        javax.swing.GroupLayout departmentPanelLayout = new javax.swing.GroupLayout(departmentPanel);
        departmentPanel.setLayout(departmentPanelLayout);
        departmentPanelLayout.setHorizontalGroup(
            departmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departmentPanelLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(departmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        departmentPanelLayout.setVerticalGroup(
            departmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(departmentComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
            .addGroup(departmentPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11))
        );

        leaderPanel.setBackground(new java.awt.Color(255, 255, 255));
        leaderPanel.setPreferredSize(new java.awt.Dimension(341, 26));
        leaderPanel.setSize(new java.awt.Dimension(341, 26));

        jLabel12.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel12.setText("Leader ID:");

        leaderComboBox.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        leaderComboBox.setForeground(new java.awt.Color(102, 102, 102));
        leaderComboBox.setModel(leaderModel);
        leaderComboBox.setPreferredSize(new java.awt.Dimension(78, 23));
        leaderComboBox.setSize(new java.awt.Dimension(78, 23));

        javax.swing.GroupLayout leaderPanelLayout = new javax.swing.GroupLayout(leaderPanel);
        leaderPanel.setLayout(leaderPanelLayout);
        leaderPanelLayout.setHorizontalGroup(
            leaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leaderPanelLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(leaderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        leaderPanelLayout.setVerticalGroup(
            leaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leaderComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
            .addGroup(leaderPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(departmentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(leaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(leaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(departmentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        previousButton.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        previousButton.setText("Previous");
        previousButton.addActionListener(this::previousButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(previousButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(previousButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void roleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleComboBoxActionPerformed
        String role = (String) roleComboBox.getSelectedItem();
        
        switch(role){
            case "Academic Leader":
                departmentPanel.setVisible(true);
                leaderPanel.setVisible(false);
                break;
            case "Lecturer":
                departmentPanel.setVisible(true);
                leaderPanel.setVisible(true);
                break;
            case "Student":
                departmentPanel.setVisible(false);
                leaderPanel.setVisible(false);
                break;
            case "Select Role":
                departmentPanel.setVisible(false);
                leaderPanel.setVisible(false);
                id_field.setText("");
                break;
        }
        
        departmentPanel.revalidate();
        departmentPanel.repaint();
        leaderPanel.revalidate();
        leaderPanel.repaint();
        
        id_field.setText(generateNewUserId(role));
    }//GEN-LAST:event_roleComboBoxActionPerformed

    private void createUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserButtonActionPerformed
        
        String role = (String) roleComboBox.getSelectedItem();
        String id = id_field.getText().trim();
        String admin_id = logged_in_admin.getUser_id();
        String department = "";
        String leader_id = "";
        
        // Name validation
        String name = name_field.getText().trim();
        if (!name.matches("[a-zA-Z./]+( [a-zA-Z./]+)*")) {
            JOptionPane.showMessageDialog(this, 
                "Name can only contain letters, spaces, periods, and slashes.", 
                "Validation Error", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (name.length() < 2 || name.length() > 50) {
            JOptionPane.showMessageDialog(this, "Name must be between 2 and 50 characters", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Email validation
        String email = email_field.getText().trim();
        String email_pattern = "^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$";
        if (!email.matches(email_pattern)) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Check if email unique
        boolean emailExists = false;
        List<User> allUsers = logged_in_admin.readUser();
        for(User u: allUsers){
            String email_file = u.getEmail();
            
            if (email_file.equalsIgnoreCase(email)) {
                emailExists = true;
                break;
            }

        }
        
        if (emailExists) {
            JOptionPane.showMessageDialog(this, "Email already exists. Please use another email.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Validate password
        char[] passwordChars = password_field.getPassword();
        String password = new String(passwordChars).trim();

        java.util.Arrays.fill(passwordChars, '\0');
        
        if (password.length() < 8) {
            JOptionPane.showMessageDialog(this,
                "Password must be at least 8 characters long",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!password.matches("^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]+$")) {
            JOptionPane.showMessageDialog(this,
                "Password must contain at least one letter and one number, and no spaces",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Extract gender
        String genderStr = (String) genderComboBox.getSelectedItem();
        String gender = "";
        if(genderStr.equals("Female")){
            gender = "F";
        }else if(genderStr.equals("Male")){
            gender = "M";
        }
        

        // DOB validation
        Date selected_date = dobChooser.getDate();
        if(selected_date == null){
            JOptionPane.showMessageDialog(this, "Please select a date of birth.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // convert to LocalDate
        LocalDate dob = selected_date.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate(); // output will be yyyy:mm:dd
        
        int min_age;
        int max_age = 100;
        switch(role){
            case "Academic Leader":
                min_age = 30;
                break;
            case "Lecturer":
                min_age = 25;
                break;
            case "Student":
                min_age = 18;
                break;
            default:
                JOptionPane.showMessageDialog(this, "Please select a valid role before entering date of birth", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
        }
        
        // calculate difference
        LocalDate today = LocalDate.now();
        LocalDate earliestAllowedDate = today.minusYears(max_age);
        LocalDate latestAllowedDate = today.minusYears(min_age);
        
        
        if(dob.isAfter(latestAllowedDate)){
            JOptionPane.showMessageDialog(this, 
                    String.format("Selected date of birth does not meet the minimum age requirement of %d for %s", min_age, role),
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(dob.isBefore(earliestAllowedDate)){
            JOptionPane.showMessageDialog(this, 
                String.format("Selected date of birth exceeds the maximum age limit of %d for %s", max_age, role),
                "Validation Error",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Phone number validation
        String contact_no = contact_no_field.getText().trim();

        if (!contact_no.matches("\\d{10}")) {
            JOptionPane.showMessageDialog(this, 
                "Phone number must be exactly 10 digits (e.g., 0123456789)", 
                "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        boolean phoneExists = false;
        for(User u: allUsers){
            String contact_no_file = u.getContact_no();
            
            if (contact_no_file.equals(contact_no)) {
                phoneExists = true;
                break;
            }

        }
        
        if (phoneExists) {
            JOptionPane.showMessageDialog(this, "Phone number already exists. Please use another phone number.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
                
        if(role.equals("Academic Leader") || role.equals("Lecturer")){
            department = (String) departmentComboBox.getSelectedItem();
        }
        
        if(role.equals("Lecturer")){
            leader_id = (String) leaderComboBox.getSelectedItem();
        }
        
        // add created_at
        String data = String.join(";",
            id,
            name,
            email,
            password,
            gender,
            dob.toString(),
            contact_no,
            role,
            admin_id,
            today.toString(),
            department,
            leader_id
        );
        
        String[] create_user_status = logged_in_admin.createUser(data);
        boolean status = Boolean.parseBoolean(create_user_status[0]);
        String status_message = create_user_status[1];
        
        if(status){
            JOptionPane.showMessageDialog(this, status_message, "Success", JOptionPane.INFORMATION_MESSAGE);
            
            roleComboBox.setSelectedIndex(0);
            id_field.setText("");
            name_field.setText("");
            email_field.setText("");
            password_field.setText("");
            contact_no_field.setText("");

            genderComboBox.setSelectedIndex(0);
            roleComboBox.setSelectedIndex(0);
            departmentComboBox.setSelectedIndex(0);
            leaderComboBox.setSelectedIndex(0);
            
            dobChooser.setDate(null);

            departmentPanel.setVisible(false);
            leaderPanel.setVisible(false);
            
        }else{
            JOptionPane.showMessageDialog(this, status_message, "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_createUserButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        UserManagementFrame umf = new UserManagementFrame(logged_in_admin);
        this.dispose();
        umf.setVisible(true);
    }//GEN-LAST:event_previousButtonActionPerformed

    public String generateNewUserId(String role){
        
        if (role == null || role.equals("Select Role")) {
            return ""; 
        }
        
        String prefix;
        int max_number = 0;
        
        switch(role){
            case "Academic Leader":
                prefix = "AL";
                break;
            case "Lecturer":
                prefix = "L";
                break;
            case "Student":
                prefix = "TP";
                break;
            default: 
                throw new IllegalArgumentException("Unknown role: " + role);
        }
        
        List<User> allUsers = logged_in_admin.readUser();
        for(User u: allUsers){
            
            String id = u.getUser_id();
            
            if(id.startsWith(prefix)){
                // cut prefix part, get id number
                String numeric_part = id.substring(prefix.length());
                
                try{
                    int num = Integer.parseInt(numeric_part);
                    if(num > max_number){
                        max_number = num;
                    }
                }catch(NumberFormatException e){
                    System.out.println("Skipping invalid ID: " + id);
                }
            }
        }
        
        int new_number = max_number + 1;
        return prefix + String.format("%03d", new_number);
        
    }
    
    
    @FunctionalInterface
    interface SimpleDocumentListener extends DocumentListener {
        
        void update();

        @Override
        default void insertUpdate(DocumentEvent e) { update(); }

        @Override
        default void removeUpdate(DocumentEvent e) { update(); }

        @Override
        default void changedUpdate(DocumentEvent e) { update(); }
    }
    
    private void addFieldListeners() {
        
        // For text fields - detect text changes
        id_field.getDocument().addDocumentListener((SimpleDocumentListener) () -> checkFields());
        name_field.getDocument().addDocumentListener((SimpleDocumentListener) () -> checkFields());
        email_field.getDocument().addDocumentListener((SimpleDocumentListener) () -> checkFields());
        password_field.getDocument().addDocumentListener((SimpleDocumentListener) () -> checkFields());
        contact_no_field.getDocument().addDocumentListener((SimpleDocumentListener) () -> checkFields());

        // For combo boxes - detect selection changes
        genderComboBox.addActionListener(e -> checkFields());
        roleComboBox.addActionListener(e -> checkFields());
        
        dobChooser.getDateEditor().addPropertyChangeListener(evt -> {
            if ("date".equals(evt.getPropertyName())) {
                checkFields();
            }
        });
        
    }

    private void checkFields() {

        String id = id_field.getText().trim();
        String name = name_field.getText().trim();
        String email = email_field.getText().trim();
        char[] passwordChars = password_field.getPassword();
        boolean hasPassword = passwordChars.length > 0;
        String contact = contact_no_field.getText().trim();

        // Get selected items from combo boxes
        String gender = (String) genderComboBox.getSelectedItem();
        String role = (String) roleComboBox.getSelectedItem();
        
        Date selectedDate = dobChooser.getDate();
        boolean hasDOB = selectedDate != null;

        boolean allFilled = !id.isEmpty() &&
                            !name.isEmpty() &&
                            !email.isEmpty() &&
                            hasPassword &&
                            hasDOB &&
                            !contact.isEmpty() &&
                            gender != null &&
                            !gender.isEmpty() &&
                            role != null &&
                            !role.isEmpty() &&
                            !role.equals("Select Role");

        // Enable or disable the button
        createUserButton.setEnabled(allFilled);
    }
    
    // UI improvement capitalize letter
    private class CapitalizeFilter extends DocumentFilter {

        private String capitalizeWords(String text) {
            StringBuilder sb = new StringBuilder();
            boolean capitalizeNext = true;

            for (char c : text.toCharArray()) {
                if (Character.isWhitespace(c)) {
                    sb.append(c);
                    capitalizeNext = true;   // next letter after space is capitalized
                } else {
                    if (capitalizeNext && Character.isLetter(c)) {
                        sb.append(Character.toUpperCase(c));
                        capitalizeNext = false;
                    } else {
                        sb.append(Character.toLowerCase(c));
                        capitalizeNext = false;
                    }
                }
            }
            return sb.toString();
        }


        @Override
        public void insertString(FilterBypass fb, int offset, String string, AttributeSet attr)
                throws BadLocationException {

            String current = fb.getDocument().getText(0, fb.getDocument().getLength());
            String result = capitalizeWords(
                    current.substring(0, offset) + string + current.substring(offset)
            );
            fb.replace(0, fb.getDocument().getLength(), result, attr);
        }

        @Override
        public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs)
                throws BadLocationException {

            String current = fb.getDocument().getText(0, fb.getDocument().getLength());
            String result = capitalizeWords(
                    current.substring(0, offset) + text + current.substring(offset + length)
            );
            fb.replace(0, fb.getDocument().getLength(), result, attrs);
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new CreateUserFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contact_no_field;
    private javax.swing.JButton createUserButton;
    private javax.swing.JComboBox<String> departmentComboBox;
    private javax.swing.JPanel departmentPanel;
    private com.toedter.calendar.JDateChooser dobChooser;
    private javax.swing.JTextField email_field;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JTextField id_field;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JComboBox<String> leaderComboBox;
    private javax.swing.JPanel leaderPanel;
    private javax.swing.JTextField name_field;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JButton previousButton;
    private javax.swing.JComboBox<String> roleComboBox;
    // End of variables declaration//GEN-END:variables
}
