/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.Student;

import javax.swing.JPanel;
import java.awt.*;
import java.awt.geom.Arc2D;

/**
 *
 * @author student
 */
public class ProgressCirclePanel extends javax.swing.JPanel {
    
    private int percentage = 0;
    private Color progressColor = new Color(37, 99, 235); // Blue
    private Color backgroundColor = new Color(229, 231, 235); // Light gray
    
    /**
     * Creates new form ProgressCirclePanel
     */
    public ProgressCirclePanel() {
        initComponents();
        setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    public void setPercentage(int percentage) {
        this.percentage = Math.max(0, Math.min(100, percentage));
        repaint();
    }
    
    public void setProgressColor(Color color) {
        this.progressColor = color;
        repaint();
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        Graphics2D g2d = (Graphics2D) g.create();
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        
        int width = getWidth();
        int height = getHeight();
        int size = Math.min(width, height) - 40; // Leave margin
        int x = (width - size) / 2;
        int y = (height - size) / 2;
        int strokeWidth = 12;
        
        // Draw background circle
        g2d.setStroke(new BasicStroke(strokeWidth, BasicStroke.CAP_ROUND, BasicStroke.JOIN_ROUND));
        g2d.setColor(backgroundColor);
        g2d.drawArc(x, y, size, size, 0, 360);
        
        // Draw progress arc
        if (percentage > 0) {
            g2d.setColor(progressColor);
            int angle = (int) (360.0 * percentage / 100.0);
            g2d.drawArc(x, y, size, size, 90, -angle);
        }
        
        // Draw percentage text in center
        g2d.setColor(new Color(30, 41, 59));
        Font percentFont = new Font("Helvetica Neue", Font.BOLD, 32);
        g2d.setFont(percentFont);
        String percentText = percentage + "%";
        FontMetrics fm = g2d.getFontMetrics();
        int textWidth = fm.stringWidth(percentText);
        int textHeight = fm.getAscent();
        g2d.drawString(percentText, x + (size - textWidth) / 2, y + (size + textHeight) / 2 - 5);
        
        g2d.dispose();
    }
    
    @Override
    public Dimension getPreferredSize() {
        return new Dimension(150, 150);
    }
}