/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.Student;

import assessmentfeedbacksystem.*;
import javax.swing.*;
import java.awt.*;
import java.util.List;
import java.util.ArrayList;
import java.util.stream.Collectors;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author student
 */
public class StudentClassesPanel extends javax.swing.JPanel {

    private String currentUsername;
    private final StudentManager dataService;
    private final DefaultTableModel availableTableModel = new DefaultTableModel(
            new Object[]{"Class", "Module", "Lecturer", "Day", "Time", "Credits"}, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    private List<ClassModel> availableClassCache = new ArrayList<>();
    private List<ClassModel> enrolledClassCache = new ArrayList<>();

    /**
     * Creates new form StudentClassesPanel
     */
    public StudentClassesPanel() {
        this.dataService = new StudentManager();
        initComponents();
        configureTables();
        configureListeners();
    }
    
    public StudentClassesPanel(String username) {
        this(username, new StudentManager());
    }

    public StudentClassesPanel(String username, StudentManager dataService) {
        this.currentUsername = username;
        this.dataService = dataService != null ? dataService : new StudentManager();
        initComponents();
        configureTables();
        configureListeners();
        loadClassesData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlBody = new javax.swing.JPanel();
        pnlBodyHeader = new javax.swing.JPanel();
        lblAvailableTitle = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        tblAvailable = new javax.swing.JTable();
        pnlDetails = new javax.swing.JPanel();
        pnlDetailsHeader = new javax.swing.JPanel();
        pnlDetailsActions = new javax.swing.JPanel();
        btnEnrollInline = new javax.swing.JButton();
        lblInlineStatus = new javax.swing.JLabel();
        pnlDetailsSelector = new javax.swing.JPanel();
        lblEnrolled = new javax.swing.JLabel();
        cmbEnrolledClasses = new javax.swing.JComboBox<>();
        pnlDetailsGrid = new javax.swing.JPanel();
        lblModuleTitle = new javax.swing.JLabel();
        lblModuleValue = new javax.swing.JLabel();
        lblLecturerTitle = new javax.swing.JLabel();
        lblLecturerValue = new javax.swing.JLabel();
        lblTimeTitle = new javax.swing.JLabel();
        lblTimeValue = new javax.swing.JLabel();
        lblCreditsTitle = new javax.swing.JLabel();
        lblCreditsValue = new javax.swing.JLabel();

        setBackground(new java.awt.Color(237, 241, 246));
        setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(new java.awt.Color(237, 241, 246));
        pnlHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 35, 10, 35));
        pnlHeader.setLayout(new java.awt.BorderLayout(10, 6));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Classes");
        pnlHeader.add(lblTitle, java.awt.BorderLayout.WEST);

        add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlBody.setBackground(new java.awt.Color(237, 241, 246));
        pnlBody.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 35, 30, 35));
        pnlBody.setLayout(new java.awt.BorderLayout());

        pnlBodyHeader.setBackground(new java.awt.Color(237, 241, 246));
        pnlBodyHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));
        pnlBodyHeader.setLayout(new java.awt.BorderLayout());

        lblAvailableTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblAvailableTitle.setText("Available Classes");
        pnlBodyHeader.add(lblAvailableTitle, java.awt.BorderLayout.WEST);

        pnlBody.add(pnlBodyHeader, java.awt.BorderLayout.PAGE_START);

        scrollPane.setBorder(null);
        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tblAvailable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrollPane.setViewportView(tblAvailable);

        pnlBody.add(scrollPane, java.awt.BorderLayout.CENTER);

        pnlDetails.setBackground(new java.awt.Color(237, 241, 246));
        pnlDetails.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 0, 0, 0));
        pnlDetails.setLayout(new java.awt.BorderLayout());

        pnlDetailsHeader.setBackground(new java.awt.Color(237, 241, 246));
        pnlDetailsHeader.setLayout(new javax.swing.BoxLayout(pnlDetailsHeader, javax.swing.BoxLayout.Y_AXIS));

        pnlDetailsActions.setBackground(new java.awt.Color(237, 241, 246));
        pnlDetailsActions.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 0));

        btnEnrollInline.setBackground(new java.awt.Color(37, 99, 235));
        btnEnrollInline.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnEnrollInline.setForeground(new java.awt.Color(255, 255, 255));
        btnEnrollInline.setText("Select your class");
        btnEnrollInline.setFocusPainted(false);
        pnlDetailsActions.add(btnEnrollInline);

        lblInlineStatus.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblInlineStatus.setText(" ");
        pnlDetailsActions.add(lblInlineStatus);

        pnlDetailsHeader.add(pnlDetailsActions);

        pnlDetailsSelector.setBackground(new java.awt.Color(237, 241, 246));
        pnlDetailsSelector.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 0, 0, 0));
        pnlDetailsSelector.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 0));

        lblEnrolled.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblEnrolled.setText("Enrolled Class");
        pnlDetailsSelector.add(lblEnrolled);

        cmbEnrolledClasses.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        cmbEnrolledClasses.setPreferredSize(new java.awt.Dimension(220, 28));
        pnlDetailsSelector.add(cmbEnrolledClasses);

        pnlDetailsHeader.add(pnlDetailsSelector);

        pnlDetails.add(pnlDetailsHeader, java.awt.BorderLayout.PAGE_START);

        pnlDetailsGrid.setBackground(new java.awt.Color(255, 255, 255));
        pnlDetailsGrid.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        pnlDetailsGrid.setLayout(new java.awt.GridLayout(0, 2, 12, 8));

        lblModuleTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblModuleTitle.setText("Module");
        pnlDetailsGrid.add(lblModuleTitle);

        lblModuleValue.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pnlDetailsGrid.add(lblModuleValue);

        lblLecturerTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblLecturerTitle.setText("Lecturer");
        pnlDetailsGrid.add(lblLecturerTitle);

        lblLecturerValue.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pnlDetailsGrid.add(lblLecturerValue);

        lblTimeTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblTimeTitle.setText("Time");
        pnlDetailsGrid.add(lblTimeTitle);

        lblTimeValue.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pnlDetailsGrid.add(lblTimeValue);

        lblCreditsTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblCreditsTitle.setText("Credits");
        pnlDetailsGrid.add(lblCreditsTitle);

        lblCreditsValue.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pnlDetailsGrid.add(lblCreditsValue);

        pnlDetails.add(pnlDetailsGrid, java.awt.BorderLayout.CENTER);

        pnlBody.add(pnlDetails, java.awt.BorderLayout.SOUTH);

        add(pnlBody, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnrollInline;
    private javax.swing.JComboBox<ClassOption> cmbEnrolledClasses;
    private javax.swing.JLabel lblAvailableTitle;
    private javax.swing.JLabel lblCreditsTitle;
    private javax.swing.JLabel lblCreditsValue;
    private javax.swing.JLabel lblEnrolled;
    private javax.swing.JLabel lblInlineStatus;
    private javax.swing.JLabel lblLecturerTitle;
    private javax.swing.JLabel lblLecturerValue;
    private javax.swing.JLabel lblModuleTitle;
    private javax.swing.JLabel lblModuleValue;
    private javax.swing.JLabel lblTimeTitle;
    private javax.swing.JLabel lblTimeValue;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlBodyHeader;
    private javax.swing.JPanel pnlDetails;
    private javax.swing.JPanel pnlDetailsActions;
    private javax.swing.JPanel pnlDetailsGrid;
    private javax.swing.JPanel pnlDetailsHeader;
    private javax.swing.JPanel pnlDetailsSelector;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tblAvailable;
    // End of variables declaration//GEN-END:variables

    private void loadClassesData() {
        refreshClassSelectors();
        refreshAvailableTable();
        updateEnrolledDetails();
    }
    
    private void refreshClassSelectors() {
        if (currentUsername == null || currentUsername.isEmpty()) {
            availableClassCache = new ArrayList<>();
            cmbEnrolledClasses.setModel(new DefaultComboBoxModel<>());
            return;
        }

        List<ClassModel> allClasses = dataService.getAllClasses();
        enrolledClassCache = dataService.getEnrolledClasses(currentUsername);

        List<String> enrolledIds = enrolledClassCache.stream()
            .map(ClassModel::getClassId)
            .collect(Collectors.toList());

        availableClassCache = allClasses.stream()
            .filter(c -> !enrolledIds.contains(c.getClassId()))
            .collect(Collectors.toList());

        DefaultComboBoxModel<ClassOption> enrolledModel = new DefaultComboBoxModel<>();
        enrolledModel.addElement(new ClassOption(null, "Select enrolled class"));
        for (ClassModel c : enrolledClassCache) {
            enrolledModel.addElement(new ClassOption(c.getClassId(), formatClassOption(c)));
        }
        cmbEnrolledClasses.setModel(enrolledModel);
    }

    private void refreshAvailableTable() {
        availableTableModel.setRowCount(0);
        for (ClassModel c : availableClassCache) {
            String time = c.getStartTime() + " - " + c.getEndTime();
            availableTableModel.addRow(new Object[]{
                c.getClassName(),
                getModuleCode(c) + " - " + getModuleName(c),
                getLecturerName(c),
                c.getDay().toString(),
                time,
                getCreditHours(c)
            });
        }
    }

    private void updateEnrolledDetails() {
        ClassOption selected = (ClassOption) cmbEnrolledClasses.getSelectedItem();
        if (selected == null || selected.classId == null) {
            lblModuleValue.setText("-");
            lblLecturerValue.setText("-");
            lblTimeValue.setText("-");
            lblCreditsValue.setText("-");
            return;
        }

        ClassModel c = dataService.getClassById(selected.classId);
        if (c == null) {
            lblModuleValue.setText("-");
            lblLecturerValue.setText("-");
            lblTimeValue.setText("-");
            lblCreditsValue.setText("-");
            return;
        }

        lblModuleValue.setText(getModuleCode(c) + " - " + getModuleName(c));
        lblLecturerValue.setText(getLecturerName(c));
        lblTimeValue.setText(c.getDay().toString() + " " + c.getStartTime() + " - " + c.getEndTime());
        lblCreditsValue.setText(String.valueOf(getCreditHours(c)));
    }

    private String formatClassOption(ClassModel classInfo) {
        return classInfo.getClassName() + " (" + getModuleCode(classInfo) + ")";
    }

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {
        lblInlineStatus.setText(" ");
        int row = tblAvailable.getSelectedRow();
        if (row < 0 || row >= availableClassCache.size()) {
            setStatusMessage("Please select a class in the table to enroll.", false);
            return;
        }

        ClassModel selectedClass = availableClassCache.get(row);
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Once enrolled, you cannot change this class. Continue?",
                "Confirm Enrollment",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );
        if (confirm != JOptionPane.YES_OPTION) {
            setStatusMessage("Selection cancelled.", false);
            return;
        }

        boolean enrolled = dataService.enrollInClass(currentUsername, selectedClass.getClassId());
        if (enrolled) {
            setStatusMessage("Enrollment successful: " + selectedClass.getClassName() + ".", true);
            assessmentfeedbacksystem.EnrollmentBus.notifyStudent(currentUsername);
        } else {
            setStatusMessage("Enrollment failed: already enrolled or timetable conflict.", false);
        }

        refreshClassSelectors();
        refreshAvailableTable();
        updateEnrolledDetails();
    }

    private void cmbEnrolledClassesActionPerformed(java.awt.event.ActionEvent evt) {
        updateEnrolledDetails();
    }

    private void setStatusMessage(String message, boolean success) {
        lblInlineStatus.setText(message);
        if (success) {
            lblInlineStatus.setForeground(new java.awt.Color(22, 163, 74));
        } else {
            lblInlineStatus.setForeground(new java.awt.Color(220, 38, 38));
        }
    }

    private void configureTables() {
        tblAvailable.setModel(availableTableModel);
        tblAvailable.setRowHeight(28);
        tblAvailable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblAvailable.getTableHeader().setReorderingAllowed(false);
    }

    private void configureListeners() {
        cmbEnrolledClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEnrolledClassesActionPerformed(evt);
            }
        });
        btnEnrollInline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });
    }
    
    private String getModuleCode(ClassModel classModel) {
        assessmentfeedbacksystem.Module module = classModel.getModule();
        return module != null ? module.getModuleCode() : "UNKNOWN";
    }
    
    private String getModuleName(ClassModel classModel) {
        assessmentfeedbacksystem.Module module = classModel.getModule();
        return module != null ? module.getModuleName() : "Unknown Module";
    }
    
    private String getLecturerName(ClassModel classModel) {
        assessmentfeedbacksystem.Module module = classModel.getModule();
        if (module != null && module.getLecturer().getUser_id() != null) {
            return Lecturer.getLecturerNameById(module.getLecturer().getUser_id());
        }
        return "Unknown";
    }
    
    private double getCreditHours(ClassModel classModel) {
        assessmentfeedbacksystem.Module module = classModel.getModule();
        return module != null ? module.getCreditHour() : 0.0;
    }

    private static class ClassOption {
        private final String classId;
        private final String label;

        ClassOption(String classId, String label) {
            this.classId = classId;
            this.label = label;
        }

        @Override
        public String toString() {
            return label;
        }
    }

}
