/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.Student;

import assessmentfeedbacksystem.*;
import javax.swing.*;
import java.awt.*;
import java.util.List;

/**
 *
 * @author student
 */
public class StudentResultsPanel extends javax.swing.JPanel {

    private String currentUsername;
    private final StudentManager dataService;
    private final DefaultListModel<Result> resultListModel = new DefaultListModel<>();

    /**
     * Creates new form StudentResultsPanel
     */
    public StudentResultsPanel() {
        this.dataService = new StudentManager();
        initComponents();
    }

    public StudentResultsPanel(String username) {
        this(username, new StudentManager());
    }

    public StudentResultsPanel(String username, StudentManager dataService) {
        this.currentUsername = username;
        this.dataService = dataService != null ? dataService : new StudentManager();
        initComponents();
        loadResultsData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblGPA = new javax.swing.JLabel();
        pnlBody = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        lstResults = new javax.swing.JList<>();

        setBackground(new java.awt.Color(237, 241, 246));
        setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(new java.awt.Color(237, 241, 246));
        pnlHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 35, 10, 35));
        pnlHeader.setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("My Results");
        pnlHeader.add(lblTitle, java.awt.BorderLayout.WEST);

        lblGPA.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblGPA.setForeground(new java.awt.Color(46, 204, 113));
        lblGPA.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGPA.setText("GPA: 0.00");
        pnlHeader.add(lblGPA, java.awt.BorderLayout.EAST);

        add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlBody.setBackground(new java.awt.Color(237, 241, 246));
        pnlBody.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 35, 30, 35));
        pnlBody.setLayout(new java.awt.BorderLayout());

        scrollPane.setBorder(null);
        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        lstResults.setBackground(new java.awt.Color(237, 241, 246));
        lstResults.setFixedCellHeight(120);
        lstResults.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstResults.setVisibleRowCount(-1);
        scrollPane.setViewportView(lstResults);

        pnlBody.add(scrollPane, java.awt.BorderLayout.CENTER);

        add(pnlBody, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblGPA;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<Result> lstResults;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables

    private void loadResultsData() {
        if (currentUsername == null || currentUsername.isEmpty()) {
            return;
        }

        // Update GPA
        double gpa = dataService.calculateGpa(currentUsername);
        lblGPA.setText(String.format("GPA: %.2f", gpa));

        // Get results
        List<Result> results = dataService.getResults(currentUsername);

        resultListModel.clear();
        if (results == null || results.isEmpty()) {
            return;
        }
        for (Result result : results) {
            resultListModel.addElement(result);
        }
        
        lstResults.setModel(resultListModel);
        lstResults.setCellRenderer(new ResultCardRenderer());
    }

    private static class ResultCardRenderer implements ListCellRenderer<Result> {
        @Override
        public Component getListCellRendererComponent(
                JList<? extends Result> list, Result value, int index, boolean isSelected, boolean cellHasFocus) {
            JPanel card = new JPanel(new BorderLayout(15, 6));
            card.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(new Color(226, 232, 240)),
                    BorderFactory.createEmptyBorder(12, 14, 12, 14)
            ));
            card.setBackground(isSelected ? new Color(230, 239, 255) : Color.WHITE);

            // Left section
            JPanel left = new JPanel();
            left.setBackground(card.getBackground());
            left.setLayout(new BoxLayout(left, BoxLayout.Y_AXIS));

            Assessment assessment = value != null ? value.getAssessment() : null;
            String title = assessment != null ? assessment.getAssessmentName() : "Assessment";
            String type = assessment != null ? assessment.getAssessmentType().toString() : "Type";

            JLabel lblTitle = new JLabel(title);
            lblTitle.setFont(new Font("Helvetica Neue", Font.BOLD, 15));
            lblTitle.setForeground(new Color(15, 23, 42));

            JLabel lblType = new JLabel(type);
            lblType.setFont(new Font("Helvetica Neue", Font.PLAIN, 12));
            lblType.setForeground(new Color(100, 116, 139));

            left.add(lblTitle);
            left.add(Box.createVerticalStrut(4));
            left.add(lblType);

            // Right section
            JPanel right = new JPanel();
            right.setBackground(card.getBackground());
            right.setLayout(new BoxLayout(right, BoxLayout.Y_AXIS));

            int totalMarks = assessment != null ? assessment.getTotalMarks() : 100;
            int score = value != null ? value.getScore() : 0;
            double percentage = totalMarks > 0 ? (score * 100.0) / totalMarks : 0.0;
            String grade = value != null && value.getGrade() != null ? value.getGrade() : "-";
            Color gradeColor = gradeColor(grade);

            JLabel lblScore = new JLabel(score + " / " + totalMarks);
            lblScore.setFont(new Font("Helvetica Neue", Font.BOLD, 16));
            lblScore.setForeground(gradeColor);
            lblScore.setAlignmentX(Component.RIGHT_ALIGNMENT);

            JLabel lblGrade = new JLabel("Grade: " + grade);
            lblGrade.setFont(new Font("Helvetica Neue", Font.PLAIN, 12));
            lblGrade.setForeground(gradeColor);
            lblGrade.setAlignmentX(Component.RIGHT_ALIGNMENT);

            JLabel lblPercent = new JLabel(String.format("%.1f%%", percentage));
            lblPercent.setFont(new Font("Helvetica Neue", Font.PLAIN, 11));
            lblPercent.setForeground(new Color(100, 116, 139));
            lblPercent.setAlignmentX(Component.RIGHT_ALIGNMENT);

            right.add(lblScore);
            right.add(Box.createVerticalStrut(4));
            right.add(lblGrade);
            right.add(Box.createVerticalStrut(2));
            right.add(lblPercent);

            card.add(left, BorderLayout.CENTER);
            card.add(right, BorderLayout.EAST);

            return card;
        }

    }

    private static Color gradeColor(String grade) {
        if (grade == null) return new Color(100, 116, 139);
        switch (grade.toUpperCase()) {
            case "A":
            case "A+":
            case "A-":
                return new Color(34, 197, 94);
            case "B":
            case "B+":
            case "B-":
                return new Color(59, 130, 246);
            case "C":
            case "C+":
            case "C-":
                return new Color(234, 179, 8);
            case "D":
            case "D+":
                return new Color(249, 115, 22);
            default:
                return new Color(239, 68, 68);
        }
    }
}
