/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.Student;

import assessmentfeedbacksystem.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Component;
import java.time.LocalDate;
import java.time.format.TextStyle;
import java.util.List;
import java.util.Locale;
import javax.swing.*;

/**
 *
 * @author student
 */
public class StudentDashboardPanel extends javax.swing.JPanel {
    
    private String currentUsername;
    private StudentMainFrame mainFrame;
    private final StudentManager dataService;
    private final DefaultListModel<Object> todayScheduleModel = new DefaultListModel<>();
    private final assessmentfeedbacksystem.EnrollmentBus.Listener enrollmentListener = this::onEnrollmentChanged;

    /**
     * Creates new form StudentDashboardPanel
     */
    public StudentDashboardPanel() {
        this.dataService = new StudentManager();
        initComponents();
    }
    
    public StudentDashboardPanel(StudentMainFrame mainFrame, String username) {
        this(mainFrame, username, new StudentManager());
    }

    public StudentDashboardPanel(StudentMainFrame mainFrame, String username, StudentManager dataService) {
        this.mainFrame = mainFrame;
        this.currentUsername = username;
        this.dataService = dataService != null ? dataService : new StudentManager();
        initComponents();
        loadDashboardData();
    }
    
    @Override
    public void addNotify() {
        super.addNotify();
        assessmentfeedbacksystem.EnrollmentBus.register(enrollmentListener);
    }

    @Override
    public void removeNotify() {
        assessmentfeedbacksystem.EnrollmentBus.unregister(enrollmentListener);
        super.removeNotify();
    }

    private void onEnrollmentChanged(String studentId) {
        if (currentUsername == null || !currentUsername.equals(studentId)) return;
        javax.swing.SwingUtilities.invokeLater(this::loadDashboardData);
    }
    
    private void loadDashboardData() {
        // Load student data
        String[] userData = dataService.loadStudentData(currentUsername);
        
        // welcome
        if (userData != null && userData.length >= 2) {
            lblWelcome.setText("Welcome back, " + userData[1] + "!");
        } else {
            lblWelcome.setText("Welcome back, Student!");
        }
        
        // today
        LocalDate today = LocalDate.now();

        String formattedDate =
                today.getDayOfMonth() + " " +
                today.getMonth().getDisplayName(TextStyle.FULL, Locale.ENGLISH) + " " +
                today.getYear() + ", " +
                today.getDayOfWeek().getDisplayName(TextStyle.FULL, Locale.ENGLISH);

        lblTodayDate.setText(formattedDate);

        // Get enrolled classes
        List<ClassModel> enrolledClasses = dataService.getEnrolledClasses(currentUsername);
        int enrolledCount = enrolledClasses.size();
        
        // Calculate GPA
        double cgpa = dataService.calculateCgpa(currentUsername);
        
        // Get today's classes
        String todayDayName = today.getDayOfWeek().toString();
        List<ClassModel> todaysClasses = enrolledClasses.stream()
            .filter(c -> c.getDay().toString().equalsIgnoreCase(todayDayName))
            .toList();
        int todaysClassCount = todaysClasses.size();

        // Update widget values
        lblEnrolledValue.setText(String.valueOf(enrolledCount));
        lblGPAValue.setText(String.format("%.2f", cgpa));

        // Schedule list under chart placeholder
        todayScheduleModel.clear();
        if (todaysClasses.isEmpty()) {
            todayScheduleModel.addElement("No classes today!");
        } else {
            for (ClassModel c : todaysClasses) {
                todayScheduleModel.addElement(c);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblTodayDate = new javax.swing.JLabel();
        pnlBody = new javax.swing.JPanel();
        pnlLeft = new javax.swing.JPanel();
        pnlWidgetRow = new javax.swing.JPanel();
        widgetEnrolled = new javax.swing.JPanel();
        lblEnrolledTitle = new javax.swing.JLabel();
        lblEnrolledValue = new javax.swing.JLabel();
        widgetGPA = new javax.swing.JPanel();
        lblGPATitle = new javax.swing.JLabel();
        lblGPAValue = new javax.swing.JLabel();
        pnlChartHolder = new javax.swing.JPanel();
        lblScheduleTitle = new javax.swing.JLabel();
        scrollSchedule = new javax.swing.JScrollPane();
        lstSchedule = new javax.swing.JList<>();
        lstSchedule.setModel(todayScheduleModel);
        lstSchedule.setCellRenderer(new ScheduleListRenderer());

        setBackground(new java.awt.Color(237, 241, 246));
        setPreferredSize(new java.awt.Dimension(770, 540));
        setLayout(new java.awt.BorderLayout(15, 5));

        pnlHeader.setBackground(new java.awt.Color(237, 241, 246));
        pnlHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 35, 10, 35));
        pnlHeader.setLayout(new java.awt.BorderLayout(12, 0));

        lblWelcome.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        lblWelcome.setText("Welcome back, Student!");
        pnlHeader.add(lblWelcome, java.awt.BorderLayout.CENTER);

        lblTodayDate.setForeground(new java.awt.Color(100, 116, 139));
        pnlHeader.add(lblTodayDate, java.awt.BorderLayout.SOUTH);

        add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlBody.setBackground(new java.awt.Color(237, 241, 246));
        pnlBody.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 35, 30, 35));
        pnlBody.setLayout(new java.awt.BorderLayout(20, 5));

        pnlLeft.setBackground(new java.awt.Color(237, 241, 246));
        pnlLeft.setLayout(new java.awt.BorderLayout());

        pnlWidgetRow.setBackground(new java.awt.Color(237, 241, 246));
        pnlWidgetRow.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 15, 0));
        pnlWidgetRow.setPreferredSize(new java.awt.Dimension(0, 120));
        pnlWidgetRow.setLayout(new java.awt.GridLayout(1, 2, 15, 0));

        widgetEnrolled.setBackground(new java.awt.Color(255, 255, 255));
        widgetEnrolled.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        widgetEnrolled.setLayout(new java.awt.BorderLayout());

        lblEnrolledTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblEnrolledTitle.setForeground(new java.awt.Color(100, 116, 139));
        lblEnrolledTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnrolledTitle.setText("Enrolled Classes");
        widgetEnrolled.add(lblEnrolledTitle, java.awt.BorderLayout.SOUTH);

        lblEnrolledValue.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblEnrolledValue.setForeground(new java.awt.Color(52, 152, 219));
        lblEnrolledValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnrolledValue.setText("0");
        widgetEnrolled.add(lblEnrolledValue, java.awt.BorderLayout.CENTER);

        pnlWidgetRow.add(widgetEnrolled);

        widgetGPA.setBackground(new java.awt.Color(255, 255, 255));
        widgetGPA.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        widgetGPA.setLayout(new java.awt.BorderLayout());

        lblGPATitle.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblGPATitle.setForeground(new java.awt.Color(100, 116, 139));
        lblGPATitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGPATitle.setText("Current GPA");
        widgetGPA.add(lblGPATitle, java.awt.BorderLayout.SOUTH);

        lblGPAValue.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblGPAValue.setForeground(new java.awt.Color(46, 204, 113));
        lblGPAValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGPAValue.setText("0.00");
        widgetGPA.add(lblGPAValue, java.awt.BorderLayout.CENTER);

        pnlWidgetRow.add(widgetGPA);

        pnlLeft.add(pnlWidgetRow, java.awt.BorderLayout.NORTH);

        pnlChartHolder.setBackground(new java.awt.Color(255, 255, 255));
        pnlChartHolder.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        pnlChartHolder.setLayout(new java.awt.BorderLayout());

        lblScheduleTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblScheduleTitle.setForeground(new java.awt.Color(30, 41, 59));
        lblScheduleTitle.setText("Today's Schedule");
        pnlChartHolder.add(lblScheduleTitle, java.awt.BorderLayout.NORTH);

        scrollSchedule.setBorder(null);
        scrollSchedule.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        lstSchedule.setVisibleRowCount(-1);
        scrollSchedule.setViewportView(lstSchedule);

        pnlChartHolder.add(scrollSchedule, java.awt.BorderLayout.CENTER);

        pnlLeft.add(pnlChartHolder, java.awt.BorderLayout.CENTER);

        pnlBody.add(pnlLeft, java.awt.BorderLayout.CENTER);

        add(pnlBody, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblEnrolledTitle;
    private javax.swing.JLabel lblEnrolledValue;
    private javax.swing.JLabel lblGPATitle;
    private javax.swing.JLabel lblGPAValue;
    private javax.swing.JLabel lblScheduleTitle;
    private javax.swing.JLabel lblTodayDate;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JList<Object> lstSchedule;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlChartHolder;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlWidgetRow;
    private javax.swing.JScrollPane scrollSchedule;
    private javax.swing.JPanel widgetEnrolled;
    private javax.swing.JPanel widgetGPA;
    // End of variables declaration//GEN-END:variables

    private static class ScheduleListRenderer extends DefaultListCellRenderer {
        @Override
        public Component getListCellRendererComponent(
                JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            if (value instanceof String) {
                JLabel label = (JLabel) super.getListCellRendererComponent(
                        list, value, index, isSelected, cellHasFocus
                );
                label.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 8, 12, 8));
                label.setForeground(new Color(100, 116, 139));
                label.setBackground(Color.WHITE);
                return label;
            }

            ClassModel c = (ClassModel) value;
            JPanel row = new JPanel(new BorderLayout(10, 4));
            row.setBackground(Color.WHITE);
            row.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                    javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(226, 232, 240)),
                    javax.swing.BorderFactory.createEmptyBorder(10, 8, 10, 8)
            ));

            JLabel code = new JLabel(c.getClassName());
            code.setFont(new Font("Helvetica Neue", Font.BOLD, 14));
            code.setForeground(new Color(15, 23, 42));

            JLabel time = new JLabel(c.getStartTime() + " - " + c.getEndTime());
            time.setFont(new Font("Helvetica Neue", Font.PLAIN, 12));
            time.setForeground(new Color(100, 116, 139));

            row.add(code, BorderLayout.NORTH);
            row.add(time, BorderLayout.SOUTH);
            return row;
        }
    }
}
