/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.Student;

import assessmentfeedbacksystem.Notification;
import assessmentfeedbacksystem.StudentManager;
import javax.swing.*;
import java.awt.*;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 *
 * @author student
 */
public class StudentNotificationsPanel extends javax.swing.JPanel {

    private String currentUsername;
    private final StudentManager dataService;
    private final DefaultListModel<Notification> notificationListModel = new DefaultListModel<>();
    private final assessmentfeedbacksystem.NotificationBus.Listener notifListener = this::onNotificationEvent;

    /**
     * Creates new form StudentNotificationsPanel
     */
    public StudentNotificationsPanel() {
        this.dataService = new StudentManager();
        initComponents();
    }

    public StudentNotificationsPanel(String username) {
        this(username, new StudentManager());
    }

    public StudentNotificationsPanel(String username, StudentManager dataService) {
        this.currentUsername = username;
        this.dataService = dataService != null ? dataService : new StudentManager();
        initComponents();
        loadNotifications();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlBody = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        lstNotifications = new javax.swing.JList<>();

        setBackground(new java.awt.Color(237, 241, 246));
        setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(new java.awt.Color(237, 241, 246));
        pnlHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 35, 10, 35));
        pnlHeader.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Notifications");
        pnlHeader.add(lblTitle);

        add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlBody.setBackground(new java.awt.Color(237, 241, 246));
        pnlBody.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 35, 30, 35));
        pnlBody.setLayout(new java.awt.BorderLayout());

        scrollPane.setBorder(null);
        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        lstNotifications.setBackground(new java.awt.Color(237, 241, 246));
        lstNotifications.setFixedCellHeight(90);
        lstNotifications.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstNotifications.setVisibleRowCount(-1);
        scrollPane.setViewportView(lstNotifications);

        pnlBody.add(scrollPane, java.awt.BorderLayout.CENTER);

        add(pnlBody, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<Notification> lstNotifications;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addNotify() {
        super.addNotify();
        assessmentfeedbacksystem.NotificationBus.register(notifListener);
    }

    @Override
    public void removeNotify() {
        assessmentfeedbacksystem.NotificationBus.unregister(notifListener);
        super.removeNotify();
    }

    private void onNotificationEvent(String studentId) {
        if (currentUsername == null || !currentUsername.equals(studentId)) return;
        javax.swing.SwingUtilities.invokeLater(this::loadNotifications);
    }

    private void loadNotifications() {
        notificationListModel.clear();
        if (currentUsername == null || currentUsername.isEmpty()) return;

        List<Notification> notifications = dataService.getNotifications(currentUsername);
        notifications.sort((a, b) -> b.getTimestamp().compareTo(a.getTimestamp()));

        for (Notification n : notifications) {
            notificationListModel.addElement(n);
        }
        
        lstNotifications.setModel(notificationListModel);
        lstNotifications.setCellRenderer(new NotificationRenderer());
    }

    private static class NotificationRenderer extends DefaultListCellRenderer {
        private final DateTimeFormatter fmt = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

        @Override
        public Component getListCellRendererComponent(
                JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            if (!(value instanceof Notification)) {
                return super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            }

            Notification n = (Notification) value;
            JPanel card = new JPanel(new BorderLayout(10, 4));
            card.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(new Color(226, 232, 240)),
                    BorderFactory.createEmptyBorder(10, 12, 10, 12)
            ));
            card.setBackground(isSelected ? new Color(230, 239, 255) : Color.WHITE);

            JLabel icon = new JLabel("•");
            icon.setFont(new Font("Segoe UI", Font.PLAIN, 18));

            JPanel center = new JPanel();
            center.setBackground(card.getBackground());
            center.setLayout(new BoxLayout(center, BoxLayout.Y_AXIS));

            JLabel title = new JLabel(n.getTitle());
            title.setFont(new Font("Helvetica Neue", Font.BOLD, 13));
            JLabel message = new JLabel(n.getMessage());
            message.setFont(new Font("Helvetica Neue", Font.PLAIN, 12));
            message.setForeground(new Color(100, 116, 139));

            center.add(title);
            center.add(Box.createVerticalStrut(2));
            center.add(message);

            JLabel time = new JLabel(n.getTimestamp().format(fmt));
            time.setFont(new Font("Helvetica Neue", Font.PLAIN, 11));
            time.setForeground(new Color(100, 116, 139));

            card.add(icon, BorderLayout.WEST);
            card.add(center, BorderLayout.CENTER);
            card.add(time, BorderLayout.EAST);
            return card;
        }
    }
}
