/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assessmentfeedbacksystem.GUI.Student;

import assessmentfeedbacksystem.StudentManager;
import assessmentfeedbacksystem.ToastUtil;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author student
 */
public class StudentMainFrame extends javax.swing.JFrame {
    
    private String currentUsername;
    private CardLayout cardLayout;
    private final StudentManager dataService;
    private final assessmentfeedbacksystem.NotificationBus.Listener notifListener = this::onNotificationEvent;

    /**
     * Creates new form StudentMainFrame
     */
    public StudentMainFrame() {
        this.dataService = new StudentManager();
        initComponents();
    }
    
    public StudentMainFrame(String username) {
        this.dataService = new StudentManager();
        this.currentUsername = username;
        initComponents();
        
        setTitle("Student Portal - " + username);
        setSize(1050, 600);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        assessmentfeedbacksystem.NotificationBus.register(notifListener);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                assessmentfeedbacksystem.NotificationBus.unregister(notifListener);
            }
        });
        javax.swing.SwingUtilities.invokeLater(this::showLatestToast);
    }
    
    public void showPage(String pageName) {
        cardLayout.show(contentPanel, pageName);
    }

    private void onNotificationEvent(String studentId) {
        if (currentUsername == null || !currentUsername.equals(studentId)) return;
        javax.swing.SwingUtilities.invokeLater(() -> {
            // allow file write to complete before reading latest notification
            javax.swing.Timer timer = new javax.swing.Timer(150, e -> showLatestToast());
            timer.setRepeats(false);
            timer.start();
        });
    }

    private void showLatestToast() {
        if (!isShowing()) return;
        java.util.List<assessmentfeedbacksystem.Notification> notifications =
                dataService.getNotifications(currentUsername);
        if (notifications.isEmpty()) return;
        notifications.sort((a, b) -> b.getTimestamp().compareTo(a.getTimestamp()));
        assessmentfeedbacksystem.Notification latest = notifications.get(0);
        ToastUtil.showToast(
                this,
                latest.getTitle(),
                latest.getMessage(),
                ToastUtil.colorForType(latest.getType())
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sideNavBar = new StudentSideNavBar(this);

        cardLayout = new CardLayout();
        contentPanel = new JPanel(cardLayout);

        String usernameSafe = currentUsername == null ? "" : currentUsername;
        dashboardPanel = new StudentDashboardPanel(this, usernameSafe, dataService);
        classesPanel = new StudentClassesPanel(usernameSafe, dataService);
        resultsPanel = new StudentResultsPanel(usernameSafe, dataService);
        feedbackPanel = new StudentFeedbackPanel(usernameSafe, dataService);
        notificationsPanel = new StudentNotificationsPanel(usernameSafe, dataService);
        timetablePanel = new StudentTimetablePanel(usernameSafe, dataService);
        profilePanel = new StudentProfilePanel(usernameSafe, dataService);

        contentPanel.add(dashboardPanel, "DASHBOARD");
        contentPanel.add(classesPanel, "CLASSES");
        contentPanel.add(resultsPanel, "RESULTS");
        contentPanel.add(feedbackPanel, "FEEDBACK");
        contentPanel.add(notificationsPanel, "NOTIFICATIONS");
        contentPanel.add(timetablePanel, "TIMETABLE");
        contentPanel.add(profilePanel, "PROFILE");

        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(sideNavBar, BorderLayout.WEST);
        getContentPane().add(contentPanel, BorderLayout.CENTER);

        showPage("DASHBOARD");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StudentMainFrame("testStudent").setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private StudentDashboardPanel dashboardPanel;
    private StudentClassesPanel classesPanel;
    private StudentResultsPanel resultsPanel;
    private StudentFeedbackPanel feedbackPanel;
    private StudentNotificationsPanel notificationsPanel;
    private StudentTimetablePanel timetablePanel;
    private StudentProfilePanel profilePanel;
    private StudentSideNavBar sideNavBar;
    private JPanel contentPanel;
    // End of variables declaration//GEN-END:variables
}
