/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.Student;

import javax.swing.*;
import java.awt.*;

/**
 * Custom widget panel for displaying student statistics
 * Can handle both integer counts and decimal values like GPA
 * 
 * @author student
 */
public class StudentStatWidgetPanel extends javax.swing.JPanel {
    
    private Color themeColor = new Color(37, 99, 235); // Default blue
    
    /**
     * Creates new form StudentStatWidgetPanel
     */
    public StudentStatWidgetPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);
        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setLayout(new java.awt.BorderLayout());

        valueLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(37, 99, 235));
        valueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valueLabel.setText("0");
        add(valueLabel, java.awt.BorderLayout.CENTER);

        titleLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(100, 116, 139));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Statistic");
        add(titleLabel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Set data with integer value
     */
    public void setData(String title, int value) {
        titleLabel.setText(title);
        valueLabel.setText(String.valueOf(value));
        revalidate();
        repaint();
    }
    
    /**
     * Set data with string value (for formatted numbers like GPA)
     */
    public void setData(String title, String value) {
        titleLabel.setText(title);
        valueLabel.setText(value);
        revalidate();
        repaint();
    }
    
    /**
     * Set data with double value (automatically formats to 2 decimal places)
     */
    public void setData(String title, double value) {
        titleLabel.setText(title);
        valueLabel.setText(String.format("%.2f", value));
        revalidate();
        repaint();
    }
    
    /**
     * Set the theme color for the value
     */
    public void setTheme(Color color) {
        this.themeColor = color;
        valueLabel.setForeground(color);
    }
}
