/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.Student;

import assessmentfeedbacksystem.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.*;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;

/**
 *
 * @author student
 */
public class StudentTimetablePanel extends javax.swing.JPanel {

    private String currentUsername;
    private final DefaultTableModel timetableTableModel = new DefaultTableModel();
    private final StudentManager dataService;
    private static final String[] DAYS = {
        "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"
    };
    private final assessmentfeedbacksystem.EnrollmentBus.Listener enrollmentListener = this::onEnrollmentChanged;

    /**
     * Creates new form StudentTimetablePanel
     */
    public StudentTimetablePanel() {
        this.dataService = new StudentManager();
        initComponents();
    }
    
    public StudentTimetablePanel(String username) {
        this(username, new StudentManager());
    }

    public StudentTimetablePanel(String username, StudentManager dataService) {
        this.currentUsername = username;
        this.dataService = dataService != null ? dataService : new StudentManager();
        initComponents();
        loadTimetableData();
    }
    
    @Override
    public void addNotify() {
        super.addNotify();
        assessmentfeedbacksystem.EnrollmentBus.register(enrollmentListener);
    }

    @Override
    public void removeNotify() {
        assessmentfeedbacksystem.EnrollmentBus.unregister(enrollmentListener);
        super.removeNotify();
    }

    private void onEnrollmentChanged(String studentId) {
        if (currentUsername == null || !currentUsername.equals(studentId)) return;
        javax.swing.SwingUtilities.invokeLater(this::loadTimetableData);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlBody = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        tblTimetable = new javax.swing.JTable();

        setBackground(new java.awt.Color(237, 241, 246));
        setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(new java.awt.Color(237, 241, 246));
        pnlHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 35, 10, 35));
        pnlHeader.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Weekly Timetable");
        pnlHeader.add(lblTitle);

        add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlBody.setBackground(new java.awt.Color(237, 241, 246));
        pnlBody.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 35, 30, 35));
        pnlBody.setLayout(new java.awt.BorderLayout());

        scrollPane.setBorder(null);
        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tblTimetable.setModel(timetableTableModel);
        tblTimetable.setRowHeight(64);
        tblTimetable.setShowGrid(true);
        tblTimetable.setGridColor(new java.awt.Color(226, 232, 240));
        tblTimetable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblTimetable.setRowSelectionAllowed(false);
        tblTimetable.setCellSelectionEnabled(false);
        tblTimetable.setFocusable(false);
        tblTimetable.getTableHeader().setReorderingAllowed(false);
        tblTimetable.getTableHeader().setFont(new java.awt.Font("Helvetica Neue", 1, 12));
        tblTimetable.getTableHeader().setBackground(new java.awt.Color(226, 232, 240));
        tblTimetable.setDefaultRenderer(Object.class, new TimetableCellRenderer());
        scrollPane.setViewportView(tblTimetable);

        pnlBody.add(scrollPane, java.awt.BorderLayout.CENTER);

        add(pnlBody, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tblTimetable;
    // End of variables declaration//GEN-END:variables

    private void loadTimetableData() {
        List<ClassModel> enrolledClasses = dataService.getEnrolledClasses(currentUsername);

        String[] columns = new String[DAYS.length + 1];
        columns[0] = "Time";
        for (int i = 0; i < DAYS.length; i++) {
            columns[i + 1] = titleCaseDay(DAYS[i]);
        }

        List<String> slots = buildTimeSlots(enrolledClasses);
        Object[][] data;

        if (slots.isEmpty()) {
            data = new Object[][]{{"", "No classes scheduled.", "", "", "", "", "", ""}};
            timetableTableModel.setDataVector(data, columns);
            tblTimetable.getColumnModel().getColumn(0).setPreferredWidth(90);
            return;
        }

        data = new Object[slots.size()][columns.length];
        Map<String, Integer> slotIndex = new HashMap<>();
        for (int r = 0; r < slots.size(); r++) {
            data[r][0] = slots.get(r);
            slotIndex.put(slots.get(r), r);
        }

        Map<String, Integer> dayToCol = new HashMap<>();
        for (int i = 0; i < DAYS.length; i++) {
            dayToCol.put(DAYS[i], i + 1);
        }

        for (ClassModel classInfo : enrolledClasses) {
            String day = classInfo.getDay().toString().toUpperCase();
            Integer col = dayToCol.get(day);
            if (col == null) continue;

            LocalTime start = parseTime(classInfo.getStartTime());
            LocalTime end = parseTime(classInfo.getEndTime());
            if (start == null || end == null || !start.isBefore(end)) continue;

            String cell = formatTimetableCell(classInfo);
            LocalTime cursor = start;
            boolean first = true;
            while (cursor.isBefore(end)) {
                LocalTime next = cursor.plusHours(1);
                String slotKey = slotKey(formatTime(cursor), formatTime(next));
                Integer row = slotIndex.get(slotKey);
                if (row != null) {
                    String content = first ? cell : formatContinuationCell(classInfo.getClassName());
                    String existing = (String) data[row][col];
                    data[row][col] = existing == null ? content : mergeCells(existing, content);
                }
                cursor = next;
                first = false;
            }
        }

        timetableTableModel.setDataVector(data, columns);
        tblTimetable.getColumnModel().getColumn(0).setPreferredWidth(90);
    }
    
    private List<String> buildTimeSlots(List<ClassModel> classes) {
        if (classes == null || classes.isEmpty()) return new ArrayList<>();
        LocalTime minStart = null;
        LocalTime maxEnd = null;
        for (ClassModel c : classes) {
            LocalTime start = parseTime(c.getStartTime());
            LocalTime end = parseTime(c.getEndTime());
            if (start == null || end == null) continue;
            if (minStart == null || start.isBefore(minStart)) minStart = start;
            if (maxEnd == null || end.isAfter(maxEnd)) maxEnd = end;
        }
        if (minStart == null || maxEnd == null) return new ArrayList<>();

        List<String> slots = new ArrayList<>();
        LocalTime cursor = minStart;
        while (cursor.isBefore(maxEnd)) {
            LocalTime next = cursor.plusHours(1);
            slots.add(slotKey(formatTime(cursor), formatTime(next)));
            cursor = next;
        }
        return slots;
    }

    private LocalTime parseTime(Object time) {
        if (time == null) return null;
        if (time instanceof LocalTime) return (LocalTime) time;
        try {
            return LocalTime.parse(time.toString(), DateTimeFormatter.ofPattern("H:mm"));
        } catch (Exception e) {
            return null;
        }
    }

    private String formatTime(LocalTime time) {
        return time.format(DateTimeFormatter.ofPattern("HH:mm"));
    }

    private String slotKey(Object start, Object end) {
        return String.valueOf(start) + " - " + String.valueOf(end);
    }

    private String titleCaseDay(String day) {
        return day.substring(0, 1).toUpperCase() + day.substring(1).toLowerCase();
    }

    private String formatTimetableCell(ClassModel classInfo) {
        return "<html>"
                + "<div style='font-size:12px; font-weight:700; color:#0f172a; text-align:center;'>"
                + classInfo.getClassName()
                + "</div>"
                + "</html>";
    }

    private String formatContinuationCell(String moduleCode) {
        return "<html><div style='color:#334155; font-size:12px; font-weight:600; text-align:center;'>"
                + moduleCode + "</div></html>";
    }

    private String mergeCells(String existing, String added) {
        if (existing.startsWith("<html>") && existing.endsWith("</html>")) {
            String base = existing.substring(6, existing.length() - 7);
            String next = added.substring(6, added.length() - 7);
            return "<html>" + base + "<br/><br/>" + next + "</html>";
        }
        return existing + " / " + added;
    }

    private static class TimetableCellRenderer extends DefaultTableCellRenderer {
        @Override
        public Component getTableCellRendererComponent(
                JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            JLabel label = (JLabel) super.getTableCellRendererComponent(
                    table, value, isSelected, hasFocus, row, column
            );
            label.setBorder(BorderFactory.createEmptyBorder(6, 8, 6, 8));
            label.setVerticalAlignment(SwingConstants.TOP);
            if (column == 0) {
                label.setBackground(new Color(226, 232, 240));
                label.setForeground(new Color(15, 23, 42));
                label.setFont(new Font("Helvetica Neue", Font.BOLD, 13));
                label.setHorizontalAlignment(SwingConstants.LEFT);
            } else {
                label.setBackground(Color.WHITE);
                label.setForeground(new Color(15, 23, 42));
                label.setFont(new Font("Helvetica Neue", Font.PLAIN, 13));
                label.setHorizontalAlignment(SwingConstants.CENTER);
            }
            return label;
        }
    }
}
