/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.Lecturer;

import assessmentfeedbacksystem.*;
import java.awt.Color;
import javax.swing.UIManager;
import javax.swing.plaf.basic.BasicProgressBarUI;

/**
 *
 * @author Jing Yi
 */
public class AssessmentCard extends javax.swing.JPanel {
    private MainFrame mainFrame;
    private Assessment selected_assessment;
    private String class_id;
    /**
     * Creates new form AssessmentCard
     */
    public AssessmentCard(Assessment assessment, MainFrame mainFrame, String class_id) {
        this.mainFrame = mainFrame;
        
        double average_marks = Result.getAverageMarksByAssessmentId(assessment.getAssessmentId());
        average_marks = Double.isNaN(average_marks) ? 0 : average_marks; 
        
        // Set Progress Bar Color
        UIManager.put("ProgressBar.selectionForeground", Color.GRAY); 
        UIManager.put("ProgressBar.selectionBackground", Color.GRAY);
        
        initComponents();
        
        if (average_marks >= 80 && average_marks <= 100){
            styleProgressBar(AverageMarks,new java.awt.Color(178, 217, 158));
        }else if (average_marks >= 40 && average_marks < 80){
            styleProgressBar(AverageMarks,new java.awt.Color(255,232,153));
        }else {
            styleProgressBar(AverageMarks,new java.awt.Color(250,159,169));
        }
        
        
        selected_assessment = assessment;
        this.class_id = class_id;
        
        // Style status label
        String status = assessment.getAssessmentStatus().toString();
        if ("Results Published".equalsIgnoreCase(status)){
            Status.setText("Results Published");
            Status.setForeground(new java.awt.Color(0,128,0));
            Status.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,128,0)));
        }else if ("Draft".equalsIgnoreCase(status)){
            Status.setText("Draft");
            Status.setForeground(new java.awt.Color(230,120,0));
            Status.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230,120,0)));
        }else if ("Published".equalsIgnoreCase(status)){
            Status.setText("Published");
            Status.setForeground(new java.awt.Color(0,75,196));
            Status.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,75,196)));
        }
        
        // Set value
        AssessmentName.setText(assessment.getAssessmentName());
        Type.setText(assessment.getAssessmentType().toString());
        
        TotalMarks.setText(Integer.toString(assessment.getTotalMarks()));
        PercentageOfFinalExam.setText(Integer.toString(assessment.getWeightPercentage()) + "%");
         
        AverageMarks.setValue((int) average_marks);
        AverageMarks.setString(average_marks == 0 ? "0%" : Double.toString(average_marks) + "%");
        AverageMarks.setStringPainted(true);
    }
    
    private void styleProgressBar(javax.swing.JProgressBar bar, Color color) {
        bar.setUI(new BasicProgressBarUI());
        bar.setForeground(color);
        bar.setBackground(Color.WHITE);
        bar.setBorderPainted(true);
        bar.setStringPainted(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AssessmentName = new javax.swing.JTextArea();
        Type = new javax.swing.JLabel();
        AverageMarks = new javax.swing.JProgressBar();
        Status = new javax.swing.JLabel();
        ViewAssessmentBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TotalMarks = new javax.swing.JLabel();
        PercentageOfFinalExam = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        AssessmentName.setEditable(false);
        AssessmentName.setBackground(new java.awt.Color(255, 255, 255));
        AssessmentName.setColumns(20);
        AssessmentName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AssessmentName.setLineWrap(true);
        AssessmentName.setRows(2);
        AssessmentName.setText("Assessment Name");
        AssessmentName.setWrapStyleWord(true);
        AssessmentName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        AssessmentName.setFocusable(false);
        jScrollPane1.setViewportView(AssessmentName);

        Type.setBackground(new java.awt.Color(255, 255, 255));
        Type.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Type.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Type.setText("Type");
        Type.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Type.setOpaque(true);

        AverageMarks.setBackground(new java.awt.Color(255, 255, 255));
        AverageMarks.setForeground(new java.awt.Color(185, 239, 191));
        AverageMarks.setToolTipText("Average Mark (in percentage)");
        AverageMarks.setValue(70);
        AverageMarks.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        AverageMarks.setMaximumSize(new java.awt.Dimension(148, 16));
        AverageMarks.setMinimumSize(new java.awt.Dimension(148, 16));
        AverageMarks.setStringPainted(true);

        Status.setBackground(new java.awt.Color(255, 255, 255));
        Status.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Status.setText("Status");
        Status.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        Status.setOpaque(true);

        ViewAssessmentBtn.setBackground(new java.awt.Color(30, 58, 138));
        ViewAssessmentBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        ViewAssessmentBtn.setForeground(new java.awt.Color(255, 255, 255));
        ViewAssessmentBtn.setText("View Assessment");
        ViewAssessmentBtn.setToolTipText("View Assessment ");
        ViewAssessmentBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 58, 138), 1, true));
        ViewAssessmentBtn.setContentAreaFilled(false);
        ViewAssessmentBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewAssessmentBtn.setFocusPainted(false);
        ViewAssessmentBtn.setFocusable(false);
        ViewAssessmentBtn.setOpaque(true);
        ViewAssessmentBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewAssessmentBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewAssessmentBtnMouseExited(evt);
            }
        });
        ViewAssessmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAssessmentBtnActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Total Marks ");

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Percentage of Final Exam");

        TotalMarks.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        TotalMarks.setText("jlabel3");

        PercentageOfFinalExam.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        PercentageOfFinalExam.setText("jLabel3");

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Assessment Type");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ViewAssessmentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AverageMarks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PercentageOfFinalExam)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(TotalMarks)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 9, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(TotalMarks)
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(PercentageOfFinalExam)
                .addGap(21, 21, 21)
                .addComponent(AverageMarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ViewAssessmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewAssessmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAssessmentBtnActionPerformed
        if ("DRAFT".equals(selected_assessment.getAssessmentStatus().name())){
            mainFrame.editAssessment(selected_assessment, class_id);
        }else{
            mainFrame.showAssessmentDetails(selected_assessment, class_id);
        }
    }//GEN-LAST:event_ViewAssessmentBtnActionPerformed

    private void ViewAssessmentBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewAssessmentBtnMouseEntered
        ViewAssessmentBtn.setForeground(new java.awt.Color(30, 58, 138));
        ViewAssessmentBtn.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_ViewAssessmentBtnMouseEntered

    private void ViewAssessmentBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewAssessmentBtnMouseExited
        ViewAssessmentBtn.setForeground(new java.awt.Color(255, 255, 255));
        ViewAssessmentBtn.setBackground(new java.awt.Color(30, 58, 138));
    }//GEN-LAST:event_ViewAssessmentBtnMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AssessmentName;
    private javax.swing.JProgressBar AverageMarks;
    private javax.swing.JLabel PercentageOfFinalExam;
    private javax.swing.JLabel Status;
    private javax.swing.JLabel TotalMarks;
    private javax.swing.JLabel Type;
    private javax.swing.JButton ViewAssessmentBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
