/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.Lecturer;


import assessmentfeedbacksystem.ClassModel;
import assessmentfeedbacksystem.Lecturer;
import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JPanel;


public class ClassPanel extends javax.swing.JPanel { 
    private MainFrame mainFrame; 
    private Lecturer lecturer;
    
    public ClassPanel(){} 
    
    public ClassPanel(MainFrame mainFrame, Lecturer lecturer) { 
        this.lecturer = lecturer;
        this.mainFrame = mainFrame; 
        initComponents(); 
        
        List<ClassModel> classes = Lecturer.getClassByLecturerId(lecturer);

        populateClassContainer(ActiveClassCardContainer, classes, true);
        populateClassContainer(InactiveClassCardContainer, classes, false);

    }
    
    private JPanel createEmptyCardPlaceholder(ClassCard referenceCard) {
        JPanel placeholder = new JPanel();
        placeholder.setOpaque(false);
        placeholder.setPreferredSize(referenceCard.getPreferredSize());
        placeholder.setMinimumSize(referenceCard.getPreferredSize());
        placeholder.setMaximumSize(referenceCard.getPreferredSize());
        return placeholder;
    }

    private void populateClassContainer(JPanel container, List<ClassModel> classes, boolean active) {
        container.removeAll();
        container.setLayout(new BorderLayout());

        JPanel content = new JPanel();
        content.setOpaque(false);
        content.setLayout(new BoxLayout(content, BoxLayout.Y_AXIS));

        // Filter classes by status
        List<ClassModel> filteredClasses = classes.stream()
            .filter(c -> "Active".equals(c.getModule().getStatus()) == active)
            .toList();
        
        // No classes - add empty panel
        if (filteredClasses.isEmpty()) {
            content.add(new EmptyClass());
            container.add(content, BorderLayout.NORTH);
            container.revalidate();
            container.repaint();
            return;
        }

        JPanel rowPanel = null;
        int col = 0;
        ClassCard lastCard = null;

        for (ClassModel c : filteredClasses) {

            if (col == 0) {
                rowPanel = new JPanel(new GridBagLayout());
                rowPanel.setOpaque(false);
                rowPanel.setBorder(BorderFactory.createEmptyBorder(0, 15, 15, 15));
            }

            ClassCard card = new ClassCard(this.mainFrame, c);
            lastCard = card;

            GridBagConstraints gbc = new GridBagConstraints();
            gbc.gridx = col;
            gbc.gridy = 0;
            gbc.fill = GridBagConstraints.HORIZONTAL;
            gbc.weightx = 0.5;
            gbc.anchor = GridBagConstraints.NORTHWEST;
            gbc.insets = (col == 0) ? new Insets(0, 0, 0, 30) : new Insets(0, 0, 0, 0);

            rowPanel.add(card, gbc);
            col++;

            if (col == 2) {
                content.add(rowPanel);
                col = 0;
            }
        }

        // Last row with one card
        if (col == 1 && rowPanel != null && lastCard != null) {
            GridBagConstraints gbc = new GridBagConstraints();
            gbc.gridx = 1;
            gbc.gridy = 0;
            gbc.fill = GridBagConstraints.HORIZONTAL;
            gbc.weightx = 0.5;
            gbc.anchor = GridBagConstraints.NORTHWEST;
            rowPanel.add(createEmptyCardPlaceholder(lastCard), gbc);
            content.add(rowPanel);
        }

        container.add(content, BorderLayout.NORTH);
        container.revalidate();
        container.repaint();
    }
    
    public void refreshCard(){
        List<ClassModel> classes = Lecturer.getClassByLecturerId(lecturer);

        populateClassContainer(ActiveClassCardContainer, classes, true);
        populateClassContainer(InactiveClassCardContainer, classes, false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        classHeader = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ActiveClassSP = new javax.swing.JScrollPane();
        ActiveClassCardContainer = new javax.swing.JPanel();
        InactiveClassSP = new javax.swing.JScrollPane();
        InactiveClassCardContainer = new javax.swing.JPanel();

        setBackground(new java.awt.Color(239, 242, 247));
        setPreferredSize(new java.awt.Dimension(770, 540));

        classHeader.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        classHeader.setText("Class");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        ActiveClassSP.setBackground(new java.awt.Color(255, 255, 255));
        ActiveClassSP.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 1, 1));
        ActiveClassSP.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ActiveClassSP.setViewportView(ActiveClassCardContainer);

        ActiveClassCardContainer.setBackground(new java.awt.Color(237, 241, 246));
        ActiveClassCardContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 25));
        ActiveClassCardContainer.setLayout(new java.awt.BorderLayout());
        ActiveClassSP.setViewportView(ActiveClassCardContainer);

        jTabbedPane1.addTab("     Active     ", ActiveClassSP);

        InactiveClassSP.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 1, 1));
        InactiveClassSP.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        InactiveClassCardContainer.setBackground(new java.awt.Color(239, 242, 247));
        InactiveClassCardContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 25));
        InactiveClassCardContainer.setLayout(new java.awt.BorderLayout());
        InactiveClassSP.setViewportView(InactiveClassCardContainer);

        jTabbedPane1.addTab("     Inactive     ", InactiveClassSP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(classHeader)
                        .addGap(0, 690, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(classHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ActiveClassCardContainer;
    private javax.swing.JScrollPane ActiveClassSP;
    private javax.swing.JPanel InactiveClassCardContainer;
    private javax.swing.JScrollPane InactiveClassSP;
    private javax.swing.JLabel classHeader;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
