/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.Lecturer;
import assessmentfeedbacksystem.ClassModel;


public class ClassCard extends javax.swing.JPanel {
    private MainFrame mainFrame;
    private String selected_class;
    
    
    public ClassCard(MainFrame mainFrame, ClassModel c) {
        this.mainFrame = mainFrame;

        initComponents();
        
        selected_class = c.getClassId();
        ClassName.setText(c.getClassName());
        Time.setText(c.getStartTime() + " - " + c.getEndTime() + " | " + c.getCapitalizedDay());
        ModuleName.setText(c.getModule().getModuleName());
        NoOfStudent.setText(Integer.toString(ClassModel.getNoOfStudentInClass(c.getClassId())));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        ClassName = new javax.swing.JTextArea();
        moduleNameLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ModuleName = new javax.swing.JTextArea();
        studentLabel = new javax.swing.JLabel();
        NoOfStudent = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        ViewClassDetailBtn = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        setMaximumSize(new java.awt.Dimension(272, 300));
        setMinimumSize(new java.awt.Dimension(272, 300));
        setPreferredSize(new java.awt.Dimension(272, 300));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setEnabled(false);

        ClassName.setEditable(false);
        ClassName.setBackground(new java.awt.Color(255, 255, 255));
        ClassName.setColumns(20);
        ClassName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ClassName.setLineWrap(true);
        ClassName.setRows(1);
        ClassName.setText("class name");
        ClassName.setToolTipText("");
        ClassName.setWrapStyleWord(true);
        ClassName.setAutoscrolls(false);
        ClassName.setBorder(null);
        ClassName.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        ClassName.setFocusable(false);
        jScrollPane1.setViewportView(ClassName);

        moduleNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        moduleNameLabel.setForeground(new java.awt.Color(102, 102, 102));
        moduleNameLabel.setText("Module Name");

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        ModuleName.setEditable(false);
        ModuleName.setBackground(new java.awt.Color(255, 255, 255));
        ModuleName.setColumns(20);
        ModuleName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        ModuleName.setLineWrap(true);
        ModuleName.setRows(2);
        ModuleName.setText("module name");
        ModuleName.setWrapStyleWord(true);
        ModuleName.setBorder(null);
        ModuleName.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        ModuleName.setFocusable(false);
        jScrollPane2.setViewportView(ModuleName);

        studentLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        studentLabel.setForeground(new java.awt.Color(102, 102, 102));
        studentLabel.setText("Student");

        NoOfStudent.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        NoOfStudent.setText("jLabel3");

        Time.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Time.setForeground(new java.awt.Color(102, 102, 102));
        Time.setText("time");
        Time.setToolTipText("");

        ViewClassDetailBtn.setBackground(new java.awt.Color(30, 58, 138));
        ViewClassDetailBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        ViewClassDetailBtn.setForeground(new java.awt.Color(255, 255, 255));
        ViewClassDetailBtn.setText("View Detail");
        ViewClassDetailBtn.setToolTipText("View Class Detail");
        ViewClassDetailBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 58, 138), 1, true));
        ViewClassDetailBtn.setContentAreaFilled(false);
        ViewClassDetailBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewClassDetailBtn.setFocusPainted(false);
        ViewClassDetailBtn.setFocusable(false);
        ViewClassDetailBtn.setMargin(new java.awt.Insets(5, 14, 5, 14));
        ViewClassDetailBtn.setOpaque(true);
        ViewClassDetailBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewClassDetailBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewClassDetailBtnMouseExited(evt);
            }
        });
        ViewClassDetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewClassDetailBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ViewClassDetailBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(Time)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(NoOfStudent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moduleNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(Time)
                .addGap(18, 18, 18)
                .addComponent(moduleNameLabel)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(studentLabel)
                .addGap(0, 0, 0)
                .addComponent(NoOfStudent)
                .addGap(18, 18, 18)
                .addComponent(ViewClassDetailBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewClassDetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewClassDetailBtnActionPerformed
        mainFrame.showClassDetail(selected_class, null);
    }//GEN-LAST:event_ViewClassDetailBtnActionPerformed

    private void ViewClassDetailBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewClassDetailBtnMouseEntered
        ViewClassDetailBtn.setForeground(new java.awt.Color(30, 58, 138));
        ViewClassDetailBtn.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_ViewClassDetailBtnMouseEntered

    private void ViewClassDetailBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewClassDetailBtnMouseExited
        ViewClassDetailBtn.setForeground(new java.awt.Color(255, 255, 255));
        ViewClassDetailBtn.setBackground(new java.awt.Color(30, 58, 138));
    }//GEN-LAST:event_ViewClassDetailBtnMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ClassName;
    private javax.swing.JTextArea ModuleName;
    private javax.swing.JLabel NoOfStudent;
    private javax.swing.JLabel Time;
    private javax.swing.JButton ViewClassDetailBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel moduleNameLabel;
    private javax.swing.JLabel studentLabel;
    // End of variables declaration//GEN-END:variables
}
