/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.Lecturer;

import assessmentfeedbacksystem.Assessment;
import assessmentfeedbacksystem.AssessmentStatus;
import assessmentfeedbacksystem.AssessmentType;
import assessmentfeedbacksystem.ClassModel;
import assessmentfeedbacksystem.Lecturer;
import java.awt.Color;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Jing Yi
 */
public class EditAssessment extends javax.swing.JPanel {
    private MainFrame mainFrame;
    private String selected_class_id;
    private Lecturer logged_in_user;
    private String module_id;
    private Assessment assessment;
    /**
     * Creates new form EditAssessment
     * @param mainFrame
     * @param selected_class_id
     * @param logged_in_user
     * @param assessment
     */
    
    public EditAssessment(MainFrame mainFrame, String selected_class_id, Lecturer logged_in_user, Assessment assessment) {
        this.assessment = assessment;
        this.mainFrame = mainFrame;
        this.selected_class_id = selected_class_id;
        this.logged_in_user = logged_in_user;
        module_id = ClassModel.getModuleByClassId(selected_class_id).getModuleId();
        
        initComponents();
        
        // Inactive class - set to view only
        String module_status = ClassModel.getModuleByClassId(selected_class_id).getStatus();
        if ("Inactive".equalsIgnoreCase(module_status)){
            AssessmentCode.setEnabled(false);
            AssessmentName.setEnabled(false);
            Percentage.setEnabled(false);
            Type.setEnabled(false);
            TotalMarks.setEnabled(false);
            messageForRemainingPercentage.setVisible(false);
            PublishBtn.setVisible(false);
            SaveAsDraftBtn.setVisible(false);
            DeleteBtn.setVisible(false);
        }
        
        int selectedIndex = 0;
        int loop = 1;
        Type.addItem("Please select a assessment type");
        for (AssessmentType type : AssessmentType.values()) {
            Type.addItem(type.toString());
            if (assessment.getAssessmentType().equals(type)){
                selectedIndex = loop;
            }
            loop ++;
        }
        
        AssessmentCode.setText(assessment.getAssessmentId());
        AssessmentName.setText(assessment.getAssessmentName());
        try {
            Type.setSelectedIndex(selectedIndex);
        }catch (ArrayIndexOutOfBoundsException e){
            Type.setSelectedIndex(0);
        }
        TotalMarks.setValue(assessment.getTotalMarks());
        if (Assessment.remainingPercentage(module_id) == 0 && assessment.getWeightPercentage() == 0){
            Percentage.setEnabled(false);
            Percentage.setFocusable(false);
        }else{
            Percentage.setModel(new javax.swing.SpinnerNumberModel(assessment.getWeightPercentage(), 0, Assessment.remainingPercentage(module_id)+ assessment.getWeightPercentage(), 1));
        }
        messageForRemainingPercentage.setText("Remaining Percentage: " + (Assessment.remainingPercentage(module_id)+ assessment.getWeightPercentage()));
    }
    
    public String formatStringData(AssessmentStatus status){
        String id = AssessmentCode.getText();
        String name = AssessmentName.getText();
        String type = Type.getItemAt(Type.getSelectedIndex());
        String totalMarks = TotalMarks.getValue().toString();
        String percentage = Percentage.getValue().toString();
        LocalDate today = LocalDate.now();
        
        String data = String.join(";", id, name, type, module_id, 
                totalMarks, percentage, status.toString(), logged_in_user.getUser_id(), today.toString());
        
        return data;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AssessmentName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Percentage = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        Type = new javax.swing.JComboBox<>();
        TotalMarks = new javax.swing.JSpinner();
        AssessmentCode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CloseBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        PublishBtn = new javax.swing.JButton();
        SaveAsDraftBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        messageForRemainingPercentage = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(237, 241, 246));
        jPanel2.setPreferredSize(new java.awt.Dimension(770, 540));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Assessment Code:");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Total Marks:");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Assessment Name:");

        AssessmentName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AssessmentName.setToolTipText("");
        AssessmentName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        AssessmentName.setMargin(new java.awt.Insets(2, 15, 2, 15));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Assessment Type: ");

        Percentage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Percentage.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Percentage of Final Exam:");

        Type.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        TotalMarks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TotalMarks.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        AssessmentCode.setEditable(false);
        AssessmentCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AssessmentCode.setToolTipText("");
        AssessmentCode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        AssessmentCode.setEnabled(false);
        AssessmentCode.setFocusable(false);
        AssessmentCode.setMargin(new java.awt.Insets(2, 15, 2, 15));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setText("Edit Assessment");

        CloseBtn.setBackground(new java.awt.Color(237, 241, 246));
        CloseBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CloseBtn.setForeground(new java.awt.Color(120, 120, 120));
        CloseBtn.setText("x");
        CloseBtn.setToolTipText("Close");
        CloseBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CloseBtn.setBorderPainted(false);
        CloseBtn.setContentAreaFilled(false);
        CloseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseBtn.setDefaultCapable(false);
        CloseBtn.setFocusPainted(false);
        CloseBtn.setFocusable(false);
        CloseBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        CloseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseBtnMouseExited(evt);
            }
        });
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {0, 20, 0, 20, 0};
        jPanel3Layout.rowHeights = new int[] {0};
        jPanel3.setLayout(jPanel3Layout);

        PublishBtn.setBackground(new java.awt.Color(26, 62, 142));
        PublishBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PublishBtn.setForeground(new java.awt.Color(255, 255, 255));
        PublishBtn.setText("Publish Assessment");
        PublishBtn.setToolTipText("Publish Assessment");
        PublishBtn.setBorderPainted(false);
        PublishBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PublishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PublishBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        jPanel3.add(PublishBtn, gridBagConstraints);

        SaveAsDraftBtn.setText("Save As Draft");
        SaveAsDraftBtn.setToolTipText("Save As Draft");
        SaveAsDraftBtn.setMaximumSize(new java.awt.Dimension(134, 23));
        SaveAsDraftBtn.setMinimumSize(new java.awt.Dimension(134, 23));
        SaveAsDraftBtn.setPreferredSize(new java.awt.Dimension(134, 23));
        SaveAsDraftBtn.setRequestFocusEnabled(false);
        SaveAsDraftBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAsDraftBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        jPanel3.add(SaveAsDraftBtn, gridBagConstraints);

        DeleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(197, 0, 0));
        DeleteBtn.setText("Delete");
        DeleteBtn.setToolTipText("Delete Assessment");
        DeleteBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 45), 2, true));
        DeleteBtn.setContentAreaFilled(false);
        DeleteBtn.setMaximumSize(new java.awt.Dimension(134, 23));
        DeleteBtn.setMinimumSize(new java.awt.Dimension(134, 23));
        DeleteBtn.setPreferredSize(new java.awt.Dimension(134, 23));
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        jPanel3.add(DeleteBtn, gridBagConstraints);

        messageForRemainingPercentage.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        messageForRemainingPercentage.setForeground(new java.awt.Color(204, 0, 0));
        messageForRemainingPercentage.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AssessmentName, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Type, 0, 426, Short.MAX_VALUE)
                                .addComponent(TotalMarks)
                                .addComponent(Percentage))
                            .addComponent(AssessmentCode, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(messageForRemainingPercentage)))
                    .addComponent(jLabel9)
                    .addComponent(jLabel6))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CloseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(CloseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AssessmentCode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AssessmentName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(messageForRemainingPercentage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CloseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseEntered
        CloseBtn.setForeground(Color.BLACK);
    }//GEN-LAST:event_CloseBtnMouseEntered

    private void CloseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseExited
        CloseBtn.setForeground(new java.awt.Color(120,120,120));
    }//GEN-LAST:event_CloseBtnMouseExited

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        mainFrame.showClassDetail(selected_class_id, AssessmentStatus.DRAFT);
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void PublishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PublishBtnActionPerformed
        int weightage = (int) Percentage.getValue();
        int total = 100 - Assessment.remainingPercentage(module_id);
        
        if (AssessmentCode.getText().trim().isEmpty() || AssessmentName.getText().trim().isEmpty() || Type.getSelectedIndex() == 0 || (int) TotalMarks.getValue() == 0 || (int) Percentage.getValue() < 0){
            JOptionPane.showMessageDialog(null,
                "Please fill in all fields correctly before publishing.\n" +
                "- Make sure Assessment Code and Name are not empty.\n" +
                "- Select an Assessment Type.\n" +
                "- Total Marks must be greater than 0.\n" +
                "- Percentage must be greater or equals to 0.",
                "Incomplete Form",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // CASE 1: Zero-weightage assessment
        if (weightage == 0) {
            int confirm = JOptionPane.showConfirmDialog(
                null, 
                """
                    This assessment has 0% weightage and will NOT affect the final result.

                    Do you want to publish it now?""",
                "Publish Practice Assessment",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE
            );

            if (confirm == JOptionPane.YES_OPTION) {
                Assessment.saveOrUpdateAssessment(formatStringData(AssessmentStatus.PUBLISHED));
                JOptionPane.showMessageDialog(
                    null,
                    AssessmentName.getText() + " has been published.",
                    "Published",
                    JOptionPane.INFORMATION_MESSAGE
                );
                mainFrame.showClassDetail(selected_class_id, AssessmentStatus.PUBLISHED);
            }
            return;
        }

        // CASE 2: Weighted assessments – total must be exactly 100
        if (total == 100) {
            List<Assessment> list = Assessment.getWeightedAssessments(module_id);

            StringBuilder message = new StringBuilder();
            message.append("The following assessments will be published:\n\n");

            for (Assessment a : list) {
                message.append("• ")
                        .append(a.getAssessmentName())
                        .append("(")
                        .append(a.getAssessmentType())
                        .append(")")
                        .append(" – ")
                        .append(a.getWeightPercentage())
                        .append("%\n");
            }

            message.append("\nTotal weightage: 100%\n\n")
                   .append("Published assessments cannot be edited or deleted.\n")
                   .append("Students will be able to view their results.\n\n")
                   .append("Do you want to proceed?");

            int confirm = JOptionPane.showConfirmDialog(
                null,
                message.toString(),
                "Confirm Publish Final Assessments",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
            );

            if (confirm == JOptionPane.YES_OPTION) {
                Assessment.saveOrUpdateAssessment(formatStringData(AssessmentStatus.DRAFT));
                String error = Assessment.publishAllFinalAssessments(module_id);
                if (error == null){
                    JOptionPane.showMessageDialog(
                        null,
                        "Final assessments published successfully.",
                        "Publish Successful",
                        JOptionPane.INFORMATION_MESSAGE
                    );
                    mainFrame.showClassDetail(selected_class_id, AssessmentStatus.PUBLISHED);
                }else{
                    JOptionPane.showMessageDialog(
                        null,
                        error,
                        "Publish Failed",
                        JOptionPane.ERROR_MESSAGE
                    );
                }
            }
            return;
        }

        // CASE 3: Invalid total
        JOptionPane.showMessageDialog(
            null,
            """
            You must allocate exactly 100% before publishing.
            
            Current total: """ + total + "%",
            "Cannot Publish",
            JOptionPane.WARNING_MESSAGE
        );
    }//GEN-LAST:event_PublishBtnActionPerformed

    private void SaveAsDraftBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAsDraftBtnActionPerformed
        if (AssessmentCode.getText().trim().isEmpty() || AssessmentName.getText().trim().isEmpty() || Type.getSelectedIndex() == 0 || (int) TotalMarks.getValue() == 0 || (int) Percentage.getValue() < 0){
            JOptionPane.showMessageDialog(null,
                "Please fill in all fields correctly before saving.\n" +
                "- Make sure Assessment Code and Name are not empty.\n" +
                "- Select an Assessment Type.\n" +
                "- Total Marks must be greater than 0.\n" +
                "- Percentage must be greater or equals to 0.",
                "Incomplete Form",
                JOptionPane.WARNING_MESSAGE);
        }else{
            Assessment.saveOrUpdateAssessment(formatStringData(AssessmentStatus.DRAFT));
            JOptionPane.showMessageDialog(
                null, 
                "Assessment saved successfully as Draft!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE
            );
            mainFrame.showClassDetail(selected_class_id, AssessmentStatus.DRAFT);
        }
    }//GEN-LAST:event_SaveAsDraftBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
                null, 
                """
                    Are you sure you want to delete this assessment?""",
                "Confirmation",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
            );

            if (confirm == JOptionPane.YES_OPTION) {
                Assessment.deleteAssessment(assessment.getAssessmentId());
                JOptionPane.showMessageDialog(
                    null,
                    AssessmentName.getText() + " has been deleted.",
                    "Deleted",
                    JOptionPane.INFORMATION_MESSAGE
                );
                mainFrame.showClassDetail(selected_class_id, AssessmentStatus.DRAFT);
            }
            Assessment.deleteAssessment(assessment.getAssessmentId());
    }//GEN-LAST:event_DeleteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AssessmentCode;
    private javax.swing.JTextField AssessmentName;
    private javax.swing.JButton CloseBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JSpinner Percentage;
    private javax.swing.JButton PublishBtn;
    private javax.swing.JButton SaveAsDraftBtn;
    private javax.swing.JSpinner TotalMarks;
    private javax.swing.JComboBox<String> Type;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel messageForRemainingPercentage;
    // End of variables declaration//GEN-END:variables
}
