/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.Lecturer;

import assessmentfeedbacksystem.Feedback;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JTextArea;

/**
 *
 * @author Jing Yi
 */
public class FeedbackCard extends javax.swing.JPanel {

    /**
     * Creates new form FeedbackCard
     */
    public FeedbackCard(Feedback feedback) {
        initComponents();

        RatingPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));
        RatingPanel.add(new RatingStarPanel(feedback.getRating()));

        FeedbackText.setText(feedback.getComment());
        autoResizeTextArea(FeedbackText);

        FeedbackCategory.setText(feedback.getCategory());
        Date.setText(feedback.getSubmittedAt().toString());
        ClassName.setText("Anonymous Feedback (Class: " + feedback.getClassModel().getClassName() + ")");

        RatingPanel.revalidate();
        RatingPanel.repaint();
        jPanel4.revalidate();
        jPanel4.repaint();
        jPanel1.revalidate();
        jPanel1.repaint();
        
        setMaximumSize(new java.awt.Dimension(
            Integer.MAX_VALUE,
            getPreferredSize().height
        ));
        

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 211, 214), 1, true), javax.swing.BorderFactory.createEmptyBorder(18, 18, 18, 18)));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 231, 235), 1, true), javax.swing.BorderFactory.createEmptyBorder(18, 18, 18, 18)));
            }
        });
    }
    
    private void autoResizeTextArea(JTextArea textArea) {
        textArea.setRows(1);

        int lineHeight = textArea.getFontMetrics(textArea.getFont()).getHeight();
        int lines = textArea.getLineCount();

        int height = lines * lineHeight + 8;
        textArea.setPreferredSize(new java.awt.Dimension(660, height));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ClassName = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        RatingPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        FeedbackCategory = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FeedbackText = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(699, 252));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 231, 235), 1, true), javax.swing.BorderFactory.createEmptyBorder(18, 18, 18, 18)));
        jPanel1.setMaximumSize(new java.awt.Dimension(699, 200));
        jPanel1.setMinimumSize(new java.awt.Dimension(699, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(699, 200));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(663, 30));

        ClassName.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        ClassName.setForeground(new java.awt.Color(17, 24, 39));
        ClassName.setText("jLabel1");

        Date.setForeground(new java.awt.Color(107, 114, 128));
        Date.setText("2026-01-01");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ClassName, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(494, 494, 494)
                .addComponent(Date)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClassName)
                    .addComponent(Date))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);

        RatingPanel.setBackground(new java.awt.Color(255, 255, 255));
        RatingPanel.setPreferredSize(new java.awt.Dimension(663, 30));

        javax.swing.GroupLayout RatingPanelLayout = new javax.swing.GroupLayout(RatingPanel);
        RatingPanel.setLayout(RatingPanelLayout);
        RatingPanelLayout.setHorizontalGroup(
            RatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
        );
        RatingPanelLayout.setVerticalGroup(
            RatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        jPanel1.add(RatingPanel);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(663, 30));

        FeedbackCategory.setBackground(new java.awt.Color(255, 255, 255));
        FeedbackCategory.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        FeedbackCategory.setForeground(new java.awt.Color(30, 58, 138));
        FeedbackCategory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FeedbackCategory.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FeedbackCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(FeedbackCategory)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(663, 30));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setFocusable(false);

        FeedbackText.setEditable(false);
        FeedbackText.setBackground(new java.awt.Color(255, 255, 255));
        FeedbackText.setColumns(20);
        FeedbackText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FeedbackText.setForeground(new java.awt.Color(55, 65, 81));
        FeedbackText.setLineWrap(true);
        FeedbackText.setRows(1);
        FeedbackText.setWrapStyleWord(true);
        FeedbackText.setBorder(null);
        FeedbackText.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        FeedbackText.setFocusable(false);
        FeedbackText.setOpaque(false);
        jScrollPane1.setViewportView(FeedbackText);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClassName;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel FeedbackCategory;
    private javax.swing.JTextArea FeedbackText;
    private javax.swing.JPanel RatingPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
