/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.Lecturer;

import assessmentfeedbacksystem.Feedback;
import assessmentfeedbacksystem.Lecturer;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JProgressBar;
import javax.swing.UIManager;
import javax.swing.plaf.basic.BasicProgressBarUI;

/**
 *
 * @author Jing Yi
 */
public class FeedbackSumaryCard extends javax.swing.JPanel {

    /**
     * Creates new form FeedbackSumaryCard
     */
    public FeedbackSumaryCard(Lecturer logged_in_user) {
        UIManager.put("ProgressBar.selectionForeground", Color.GRAY); 
        UIManager.put("ProgressBar.selectionBackground", Color.GRAY);
        
        initComponents();
        
        styleProgressBar(star1, new Color(250, 187, 5));
        styleProgressBar(star2, new Color(250, 187, 5));
        styleProgressBar(star3, new Color(250, 187, 5));
        styleProgressBar(star4, new Color(250, 187, 5));
        styleProgressBar(star5, new Color(250, 187, 5));

        double overall = Feedback.getOverallRatingByLecturerId(logged_in_user.getUser_id());
        overallRating.setText(String.format("%.1f", overall));


        int total = Feedback.getFeedbackByLecturerId(logged_in_user.getUser_id()).size();
        TotalFeedback.setText(total + " reviews");

        initProgressBars();
        updateRatingProgressBars(logged_in_user);
        
    }
    
    private void updateRatingProgressBars(Lecturer lecturer) {
        var feedbacks = Feedback.getFeedbackByLecturerId(lecturer.getUser_id());

        int total = feedbacks.size();
        if (total == 0) {
            // No feedback → reset bars
            star1.setValue(0);
            star2.setValue(0);
            star3.setValue(0);
            star4.setValue(0);
            star5.setValue(0);
            return;
        }

        int[] counts = new int[6]; // index 1–5 used

        for (Feedback f : feedbacks) {
            int rating = f.getRating();
            if (rating >= 1 && rating <= 5) {
                counts[rating]++;
            }
        }

        // Convert to percentage
        star1.setValue(counts[1] * 100 / total);
        star2.setValue(counts[2] * 100 / total);
        star3.setValue(counts[3] * 100 / total);
        star4.setValue(counts[4] * 100 / total);
        star5.setValue(counts[5] * 100 / total);
    }
    
    private void initProgressBars() {
        star1.setMaximum(100);
        star2.setMaximum(100);
        star3.setMaximum(100);
        star4.setMaximum(100);
        star5.setMaximum(100);
    }
    
    
    private void styleProgressBar(JProgressBar bar, Color color) {
        bar.setUI(new BasicProgressBarUI());
        bar.setForeground(color);
        bar.setBackground(new Color(232, 232, 232));
        bar.setBorderPainted(false);
        bar.setStringPainted(false);
        bar.setPreferredSize(new Dimension(450, 15));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        overallRating = new javax.swing.JLabel();
        TotalFeedback = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        star5 = new javax.swing.JProgressBar();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        star4 = new javax.swing.JProgressBar();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        star3 = new javax.swing.JProgressBar();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        star2 = new javax.swing.JProgressBar();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        star1 = new javax.swing.JProgressBar();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 231, 235), 1, true));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        overallRating.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        overallRating.setForeground(new java.awt.Color(30, 58, 138));
        overallRating.setText("4.0");
        overallRating.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        overallRating.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(overallRating, new java.awt.GridBagConstraints());

        TotalFeedback.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        TotalFeedback.setForeground(new java.awt.Color(107, 114, 128));
        TotalFeedback.setText("jLabel1");
        TotalFeedback.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TotalFeedback.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel1.add(TotalFeedback, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("5");
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        star5.setBackground(new java.awt.Color(255, 255, 255));
        star5.setForeground(new java.awt.Color(255, 204, 153));
        star5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        star5.setMaximumSize(new java.awt.Dimension(146, 15));
        star5.setMinimumSize(new java.awt.Dimension(146, 15));
        star5.setOpaque(true);
        star5.setPreferredSize(new java.awt.Dimension(146, 15));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(star5, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(star5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("4");
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        star4.setBackground(new java.awt.Color(255, 255, 255));
        star4.setForeground(new java.awt.Color(255, 204, 153));
        star4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        star4.setMaximumSize(new java.awt.Dimension(146, 15));
        star4.setMinimumSize(new java.awt.Dimension(146, 15));
        star4.setOpaque(true);
        star4.setPreferredSize(new java.awt.Dimension(146, 15));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(star4, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(star4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("3");
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        star3.setBackground(new java.awt.Color(255, 255, 255));
        star3.setForeground(new java.awt.Color(255, 204, 153));
        star3.setValue(50);
        star3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        star3.setMaximumSize(new java.awt.Dimension(146, 15));
        star3.setMinimumSize(new java.awt.Dimension(146, 15));
        star3.setOpaque(true);
        star3.setPreferredSize(new java.awt.Dimension(146, 15));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(star3, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(star3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("2");
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        star2.setBackground(new java.awt.Color(255, 255, 255));
        star2.setForeground(new java.awt.Color(255, 204, 153));
        star2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        star2.setMaximumSize(new java.awt.Dimension(146, 15));
        star2.setMinimumSize(new java.awt.Dimension(146, 15));
        star2.setOpaque(true);
        star2.setPreferredSize(new java.awt.Dimension(146, 15));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(star2, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(star2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("1");
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        star1.setBackground(new java.awt.Color(255, 255, 255));
        star1.setForeground(new java.awt.Color(255, 204, 153));
        star1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        star1.setMaximumSize(new java.awt.Dimension(146, 15));
        star1.setMinimumSize(new java.awt.Dimension(146, 15));
        star1.setOpaque(true);
        star1.setPreferredSize(new java.awt.Dimension(146, 15));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(star1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(star1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jPanel2.add(jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TotalFeedback;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel overallRating;
    private javax.swing.JProgressBar star1;
    private javax.swing.JProgressBar star2;
    private javax.swing.JProgressBar star3;
    private javax.swing.JProgressBar star4;
    private javax.swing.JProgressBar star5;
    // End of variables declaration//GEN-END:variables
}
