/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assessmentfeedbacksystem.GUI.Lecturer;

import assessmentfeedbacksystem.Assessment;
import assessmentfeedbacksystem.AssessmentStatus;
import assessmentfeedbacksystem.Lecturer;
import java.awt.BorderLayout;
import java.awt.CardLayout;

/**
 *
 * @author Jing Yi
 */
public class MainFrame extends javax.swing.JFrame {
    private final Lecturer logged_in_user;
    private String selected_class_id;
    private Assessment selected_assessment_id;
    private SideBar sideBar;
    /**
     * Creates new form Lecturer_MainFrame
     * @param lecturer
     */
    public MainFrame(Lecturer lecturer) {
        this.logged_in_user = lecturer;
        
        initComponents();
        setLocationRelativeTo(null);
        
        System.out.println(logged_in_user);
        // NAVBAR
        NavBar navBar = new NavBar();
        navContainer.removeAll();
        navContainer.add(navBar, BorderLayout.CENTER);

        // SIDEBAR
        sideBar = new SideBar(this);
        sidebarContainer.removeAll();
        sidebarContainer.add(sideBar, BorderLayout.CENTER);
        
        navContainer.revalidate();
        sidebarContainer.revalidate();

        sideBar.selectMenu("Dashboard");
        showPage("Dashboard");
    }
    
    public void showClassDetail(String selected_class_id, AssessmentStatus status) {
        this.selected_class_id = selected_class_id;
        ViewClassPanel detailPanel = new ViewClassPanel(selected_class_id, this, status);
        
        contentPanel.add(detailPanel, "View Class Detail");
        sideBar.selectMenu("Class");
        showPage("View Class Detail");
    }
    
    public void showAssessmentDetails(Assessment assessment_id, String selected_class_id) {
        this.selected_assessment_id = assessment_id;
        ViewAssessmentPanel assessmentPanel = new ViewAssessmentPanel(this, selected_class_id, assessment_id, logged_in_user);

        contentPanel.add(assessmentPanel, "View Assessment Detail");
        sideBar.selectMenu("Class");
        showPage("View Assessment Detail");
    }
    
    public void createNewAssessment(String selected_class_id){
        CreateAssessment newAssessment = new CreateAssessment(this, selected_class_id, logged_in_user);
        contentPanel.add(newAssessment, "New Assessment");
        sideBar.selectMenu("Class");
        showPage("New Assessment");
    }
    
    public void editAssessment(Assessment selected_assessment_id, String selected_class_id){
        EditAssessment selected_assessment = new EditAssessment(this, selected_class_id, logged_in_user, selected_assessment_id);
        contentPanel.add(selected_assessment,"Edit Assessment");
        sideBar.selectMenu("Class");
        showPage("Edit Assessment");
    }
    

    public void showPage(String page) {
        if ("Dashboard".equals(page)) {
            dashboardPanel1.refreshDashboard(); 
        }else if ("Class".equals(page)){
            classPanel1.refreshCard();
        }
        
        CardLayout cl = (CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, page);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navContainer = new javax.swing.JPanel();
        sidebarContainer = new javax.swing.JPanel();
        contentPanel = new javax.swing.JPanel();
        dashboardPanel1 = new assessmentfeedbacksystem.GUI.Lecturer.DashboardPanel(this, logged_in_user);
        classPanel1 = new assessmentfeedbacksystem.GUI.Lecturer.ClassPanel(this, logged_in_user);
        viewFeedbackPanel1 = new assessmentfeedbacksystem.GUI.Lecturer.ViewFeedbackPanel(this, logged_in_user);
        profileContainer1 = new assessmentfeedbacksystem.GUI.Lecturer.ProfileContainer(logged_in_user);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(940, 600));
        setMinimumSize(new java.awt.Dimension(940, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(940, 600));

        navContainer.setMaximumSize(new java.awt.Dimension(0, 60));
        navContainer.setMinimumSize(new java.awt.Dimension(0, 60));
        navContainer.setPreferredSize(new java.awt.Dimension(0, 60));
        navContainer.setLayout(new java.awt.BorderLayout());
        getContentPane().add(navContainer, java.awt.BorderLayout.PAGE_START);

        sidebarContainer.setMaximumSize(new java.awt.Dimension(170, 0));
        sidebarContainer.setMinimumSize(new java.awt.Dimension(170, 0));
        sidebarContainer.setPreferredSize(new java.awt.Dimension(170, 0));
        sidebarContainer.setLayout(new java.awt.BorderLayout());
        getContentPane().add(sidebarContainer, java.awt.BorderLayout.LINE_START);

        contentPanel.setMaximumSize(new java.awt.Dimension(770, 540));
        contentPanel.setMinimumSize(new java.awt.Dimension(770, 540));
        contentPanel.setPreferredSize(new java.awt.Dimension(770, 540));
        contentPanel.setLayout(new java.awt.CardLayout());

        dashboardPanel1.setMaximumSize(new java.awt.Dimension(770, 540));
        dashboardPanel1.setMinimumSize(new java.awt.Dimension(770, 540));
        dashboardPanel1.setPreferredSize(new java.awt.Dimension(770, 540));
        contentPanel.add(dashboardPanel1, "Dashboard");

        classPanel1.setMaximumSize(new java.awt.Dimension(770, 540));
        classPanel1.setMinimumSize(new java.awt.Dimension(770, 540));
        classPanel1.setPreferredSize(new java.awt.Dimension(770, 540));
        contentPanel.add(classPanel1, "Class");

        viewFeedbackPanel1.setMaximumSize(new java.awt.Dimension(770, 540));
        viewFeedbackPanel1.setMinimumSize(new java.awt.Dimension(770, 540));
        viewFeedbackPanel1.setPreferredSize(new java.awt.Dimension(770, 540));
        contentPanel.add(viewFeedbackPanel1, "View Feedback");

        profileContainer1.setMaximumSize(new java.awt.Dimension(770, 540));
        profileContainer1.setMinimumSize(new java.awt.Dimension(770, 540));
        profileContainer1.setPreferredSize(new java.awt.Dimension(770, 540));
        contentPanel.add(profileContainer1, "Profile");

        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private assessmentfeedbacksystem.GUI.Lecturer.ClassPanel classPanel1;
    private javax.swing.JPanel contentPanel;
    private assessmentfeedbacksystem.GUI.Lecturer.DashboardPanel dashboardPanel1;
    private javax.swing.JPanel navContainer;
    private assessmentfeedbacksystem.GUI.Lecturer.ProfileContainer profileContainer1;
    private javax.swing.JPanel sidebarContainer;
    private assessmentfeedbacksystem.GUI.Lecturer.ViewFeedbackPanel viewFeedbackPanel1;
    // End of variables declaration//GEN-END:variables
}
