/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.Lecturer;

import assessmentfeedbacksystem.AcademicLeader;
import assessmentfeedbacksystem.Lecturer;
import assessmentfeedbacksystem.User;
import javax.swing.JOptionPane;

/**
 *
 * @author Jing Yi
 */
public class ProfileDetail extends javax.swing.JPanel {
    private String state = "View";
    private Lecturer logged_in_user;
    /**
     * Creates new form ProfileDetailPanel
     */
    public ProfileDetail(Lecturer logged_in_user) {
        this.logged_in_user = logged_in_user;
        initComponents();
        initValue(logged_in_user);
        if ("Edit".equals(state)){
            editState();
        }else{
            viewState();
        }
    }
    
    private void editState(){
        EmailText.setEnabled(true);
        EmailText.setEditable(true);
        
        ContactNoText.setEnabled(true);
        ContactNoText.setEditable(true);
        
        PasswordText.setEnabled(true);
        PasswordText.setEditable(true);
        
        CancelBtn.setVisible(true);
        EditOrSaveBtn.setText("Save");
    }
    
    private void viewState(){
        UserIdText.setEnabled(false);
        UserNameText.setEnabled(false);
        GenderText.setEnabled(false);
        DOBText.setEnabled(false);
        EmailText.setEnabled(false);
        ContactNoText.setEnabled(false);
        RoleText.setEnabled(false);
        DepartmentText.setEnabled(false);
        AcademicLeaderNameText.setEnabled(false);
        PasswordText.setEnabled(false);
        
        CancelBtn.setVisible(false);
        EditOrSaveBtn.setText("Edit Profile");
    }
    
    private void initValue(Lecturer logged_in_user){
        UserIdText.setText(logged_in_user.getUser_id());
        UserNameText.setText(logged_in_user.getName());
        
        if ("F".equals(logged_in_user.getGender())){
            GenderText.setText("Female");
        }else if ("M".equals(logged_in_user.getGender())){
            GenderText.setText("Male");
        }else{
            GenderText.setText("-");
        }
        
        DOBText.setText(logged_in_user.getDob().toString());
        EmailText.setText(logged_in_user.getEmail());
        ContactNoText.setText(logged_in_user.getContact_no());
        RoleText.setText(logged_in_user.getRole());
        DepartmentText.setText(logged_in_user.getDepartment());
        AcademicLeaderNameText.setText(AcademicLeader.getUserNameById(logged_in_user.getLeaderId()));
        PasswordText.setText(logged_in_user.getPassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        detailContentPanel = new javax.swing.JPanel();
        profileIconPanel = new javax.swing.JPanel();
        profileIcon = new javax.swing.JLabel();
        lblUserID = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        lblContactNumber = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblDepartment = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        UserIdText = new javax.swing.JTextField();
        UserNameText = new javax.swing.JTextField();
        GenderText = new javax.swing.JTextField();
        DOBText = new javax.swing.JTextField();
        EmailText = new javax.swing.JTextField();
        ContactNoText = new javax.swing.JTextField();
        RoleText = new javax.swing.JTextField();
        DepartmentText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        AcademicLeaderNameText = new javax.swing.JTextField();
        PasswordText = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        EditOrSaveBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(704, 446));
        setMinimumSize(new java.awt.Dimension(704, 446));
        setPreferredSize(new java.awt.Dimension(704, 446));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        detailContentPanel.setBackground(new java.awt.Color(255, 255, 255));
        detailContentPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 0, 20));
        detailContentPanel.setMaximumSize(new java.awt.Dimension(704, 384));
        detailContentPanel.setMinimumSize(new java.awt.Dimension(704, 384));
        detailContentPanel.setPreferredSize(new java.awt.Dimension(704, 384));
        detailContentPanel.setLayout(new java.awt.GridBagLayout());

        profileIconPanel.setBackground(new java.awt.Color(247, 247, 247));
        profileIconPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        profileIconPanel.setMaximumSize(new java.awt.Dimension(180, 180));
        profileIconPanel.setMinimumSize(new java.awt.Dimension(180, 180));
        profileIconPanel.setPreferredSize(new java.awt.Dimension(180, 180));
        profileIconPanel.setLayout(new java.awt.BorderLayout());

        profileIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit profile.png"))); // NOI18N
        profileIcon.setAlignmentX(0.5F);
        profileIcon.setMaximumSize(new java.awt.Dimension(100, 100));
        profileIcon.setMinimumSize(new java.awt.Dimension(100, 100));
        profileIcon.setPreferredSize(new java.awt.Dimension(100, 100));
        profileIconPanel.add(profileIcon, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 8;
        gridBagConstraints.insets = new java.awt.Insets(30, 5, 30, 30);
        detailContentPanel.add(profileIconPanel, gridBagConstraints);

        lblUserID.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblUserID.setForeground(new java.awt.Color(102, 102, 102));
        lblUserID.setText("User ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblUserID, gridBagConstraints);

        lblRole.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblRole.setForeground(new java.awt.Color(102, 102, 102));
        lblRole.setText("Role");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblRole, gridBagConstraints);

        lblUserName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(102, 102, 102));
        lblUserName.setText("User Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblUserName, gridBagConstraints);

        lblEmailAddress.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblEmailAddress.setForeground(new java.awt.Color(102, 102, 102));
        lblEmailAddress.setText("Email Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblEmailAddress, gridBagConstraints);

        lblContactNumber.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblContactNumber.setForeground(new java.awt.Color(102, 102, 102));
        lblContactNumber.setText("Contact Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblContactNumber, gridBagConstraints);

        lblGender.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblGender.setForeground(new java.awt.Color(102, 102, 102));
        lblGender.setText("Gender");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblGender, gridBagConstraints);

        lblDOB.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblDOB.setForeground(new java.awt.Color(102, 102, 102));
        lblDOB.setText("DOB");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblDOB, gridBagConstraints);

        lblDepartment.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblDepartment.setForeground(new java.awt.Color(102, 102, 102));
        lblDepartment.setText("Department");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblDepartment, gridBagConstraints);

        lblPassword.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(102, 102, 102));
        lblPassword.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(lblPassword, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(UserIdText, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(UserNameText, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(GenderText, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(DOBText, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(EmailText, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(ContactNoText, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(RoleText, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(DepartmentText, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Academic Leader");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(AcademicLeaderNameText, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        detailContentPanel.add(PasswordText, gridBagConstraints);

        add(detailContentPanel);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(704, 62));
        jPanel1.setMinimumSize(new java.awt.Dimension(704, 62));
        jPanel1.setPreferredSize(new java.awt.Dimension(704, 62));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        EditOrSaveBtn.setBackground(new java.awt.Color(30, 58, 138));
        EditOrSaveBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        EditOrSaveBtn.setForeground(new java.awt.Color(255, 255, 255));
        EditOrSaveBtn.setText("Edit Profile");
        EditOrSaveBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 58, 138), 1, true));
        EditOrSaveBtn.setContentAreaFilled(false);
        EditOrSaveBtn.setFocusPainted(false);
        EditOrSaveBtn.setFocusable(false);
        EditOrSaveBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        EditOrSaveBtn.setMinimumSize(new java.awt.Dimension(100, 23));
        EditOrSaveBtn.setOpaque(true);
        EditOrSaveBtn.setPreferredSize(new java.awt.Dimension(100, 23));
        EditOrSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditOrSaveBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel1.add(EditOrSaveBtn, gridBagConstraints);

        CancelBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        CancelBtn.setForeground(new java.awt.Color(30, 58, 138));
        CancelBtn.setText("Cancel");
        CancelBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 58, 138), 1, true));
        CancelBtn.setContentAreaFilled(false);
        CancelBtn.setFocusPainted(false);
        CancelBtn.setFocusable(false);
        CancelBtn.setMaximumSize(new java.awt.Dimension(67, 23));
        CancelBtn.setMinimumSize(new java.awt.Dimension(67, 23));
        CancelBtn.setPreferredSize(new java.awt.Dimension(67, 23));
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel1.add(CancelBtn, gridBagConstraints);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        viewState();
        state = "View";
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void EditOrSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditOrSaveBtnActionPerformed
        if ("Edit".equals(state)){
            String email = EmailText.getText().trim();
            String contact = ContactNoText.getText().trim();
            String password = new String(PasswordText.getPassword()).trim();

            if (email.isEmpty() || contact.isEmpty()) {
                JOptionPane.showMessageDialog(
                    null,
                    "Please fill in all required fields.",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            boolean success = User.updateProfile(
                logged_in_user.getUser_id(),
                email,
                contact,
                password.isEmpty() ? null : password
            );

            if (!success) {
                JOptionPane.showMessageDialog(
                    null,
                    "Failed to update profile.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
                );
                return;
            }
            JOptionPane.showMessageDialog(
                    null,
                    "Profile successfully updated.",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE
                );
            viewState();
            state = "View";
        }else{
            editState();
            state = "Edit";
        }
    }//GEN-LAST:event_EditOrSaveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AcademicLeaderNameText;
    private javax.swing.JButton CancelBtn;
    private javax.swing.JTextField ContactNoText;
    private javax.swing.JTextField DOBText;
    private javax.swing.JTextField DepartmentText;
    private javax.swing.JButton EditOrSaveBtn;
    private javax.swing.JTextField EmailText;
    private javax.swing.JTextField GenderText;
    private javax.swing.JPasswordField PasswordText;
    private javax.swing.JTextField RoleText;
    private javax.swing.JTextField UserIdText;
    private javax.swing.JTextField UserNameText;
    private javax.swing.JPanel detailContentPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContactNumber;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel profileIcon;
    private javax.swing.JPanel profileIconPanel;
    // End of variables declaration//GEN-END:variables
}
