/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.Lecturer;

import javax.swing.JLabel;

/**
 *
 * @author Jing Yi
 */
public class RatingStarPanel extends javax.swing.JPanel {

    /**
     * Creates new form RatingPanel
     */
    public RatingStarPanel(int numOfStarSelected) {
        initComponents();
        
        JLabel[] stars = {
            ratingStar1,
            ratingStar2,
            ratingStar3,
            ratingStar4,
            ratingStar5
        };
  
        
        if (numOfStarSelected <= 5 && numOfStarSelected > 0){
            for (int i = 0; i < stars.length; i++) {
                selectedStar(stars[i], i < numOfStarSelected);
            }
        }
    }
    
    private void selectedStar(JLabel star, boolean selected){
        if (selected){
            star.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/yellowStar.png")));
        }else{
            star.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/whiteStar.png")));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ratingStar1 = new javax.swing.JLabel();
        ratingStar2 = new javax.swing.JLabel();
        ratingStar3 = new javax.swing.JLabel();
        ratingStar4 = new javax.swing.JLabel();
        ratingStar5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(122, 24));
        setMinimumSize(new java.awt.Dimension(122, 24));
        setPreferredSize(new java.awt.Dimension(122, 24));
        setLayout(new java.awt.GridLayout(1, 5));

        ratingStar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/whiteStar.png"))); // NOI18N
        ratingStar1.setFocusable(false);
        ratingStar1.setIconTextGap(0);
        add(ratingStar1);

        ratingStar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/whiteStar.png"))); // NOI18N
        ratingStar2.setFocusable(false);
        ratingStar2.setIconTextGap(0);
        add(ratingStar2);

        ratingStar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/whiteStar.png"))); // NOI18N
        ratingStar3.setFocusable(false);
        ratingStar3.setIconTextGap(0);
        add(ratingStar3);

        ratingStar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/whiteStar.png"))); // NOI18N
        ratingStar4.setFocusable(false);
        ratingStar4.setIconTextGap(0);
        add(ratingStar4);

        ratingStar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/whiteStar.png"))); // NOI18N
        ratingStar5.setFocusable(false);
        ratingStar5.setIconTextGap(0);
        add(ratingStar5);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ratingStar1;
    private javax.swing.JLabel ratingStar2;
    private javax.swing.JLabel ratingStar3;
    private javax.swing.JLabel ratingStar4;
    private javax.swing.JLabel ratingStar5;
    // End of variables declaration//GEN-END:variables
}
