/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assessmentfeedbacksystem.GUI.Lecturer;

import assessmentfeedbacksystem.GUI.LoginFrame;
import java.awt.Color;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Jing Yi
 */
public class SideBar extends javax.swing.JPanel {
    
    private final MainFrame mainFrame;
    private final Color DEFAULT_COLOR = new Color(255, 255, 255);
    private final Color SELECTED_BACKGROUND_COLOR = new Color(215, 236, 255);
    private final Color SELECTED_INDICATOR_COLOR = new Color(19,85,227);
    private String selected_btn = "Dashboard";

    public SideBar(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        selectButton(dashboard_sidebar,"/icons/DashboardSelected.png", DashboardIndicatorLine);
        selected_btn = "Dashboard";
    }
    

    private void resetButtonStyles() {
        dashboard_sidebar.setBackground(DEFAULT_COLOR);
        class_sidebar.setBackground(DEFAULT_COLOR);
        feedback_sidebar.setBackground(DEFAULT_COLOR);
        profile_sidebar.setBackground(DEFAULT_COLOR);
        
        dashboard_sidebar.setForeground(new java.awt.Color(180,180,180));
        class_sidebar.setForeground(new java.awt.Color(180,180,180));
        feedback_sidebar.setForeground(new java.awt.Color(180,180,180));
        profile_sidebar.setForeground(new java.awt.Color(180,180,180));
        
        dashboard_sidebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/DashboardIcon.png")));
        class_sidebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ClassIcon.png")));
        feedback_sidebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/FeedbackIcon.png")));
        profile_sidebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ProfileIcon.png")));
        
        DashboardIndicatorLine.setBackground(DEFAULT_COLOR);
        ClassIndicatorLine.setBackground(DEFAULT_COLOR);
        FeedbackIndicatorLine.setBackground(DEFAULT_COLOR);
        ProfileIndicatorLine.setBackground(DEFAULT_COLOR);
    }

    private void selectButton(JButton btn, String icon_path, JPanel panel) {
        resetButtonStyles();
        btn.setBackground(SELECTED_BACKGROUND_COLOR);
        btn.setForeground(new java.awt.Color(66,84,167));
        btn.setIcon(new javax.swing.ImageIcon(getClass().getResource(icon_path)));
        panel.setBackground(SELECTED_INDICATOR_COLOR);
    }
  
    private void hoverButton(JButton btn, String icon_path) {
        btn.setForeground(new java.awt.Color(66,84,167));
        btn.setIcon(new javax.swing.ImageIcon(getClass().getResource(icon_path)));
    }
    
    private void stopHoverButton(JButton btn, String icon_path) {
        btn.setForeground(new java.awt.Color(180,180,180));
        btn.setIcon(new javax.swing.ImageIcon(getClass().getResource(icon_path)));
    }

    public void selectMenu(String menu) {
        switch (menu) {
            case "Dashboard":
                selectButton(dashboard_sidebar,"/icons/DashboardSelected.png", DashboardIndicatorLine);
                selected_btn = "Dashboard";
                break;
            case "Class":
                selectButton(class_sidebar, "/icons/ClassSelected.png", ClassIndicatorLine);
                selected_btn = "Class";
                break;
            case "Feedback":
                selectButton(feedback_sidebar, "/icons/FeedbackSelected.png", FeedbackIndicatorLine);
                selected_btn = "Feedback";
                break;
            case "Profile":
                selectButton(profile_sidebar, "/icons/ProfileSelected.png", ProfileIndicatorLine);
                selected_btn = "Profile";
                break;
             
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        DashboardPanel = new javax.swing.JPanel();
        DashboardIndicatorLine = new javax.swing.JPanel();
        dashboard_sidebar = new javax.swing.JButton();
        ClassPanel = new javax.swing.JPanel();
        ClassIndicatorLine = new javax.swing.JPanel();
        class_sidebar = new javax.swing.JButton();
        FeedbackPanel = new javax.swing.JPanel();
        FeedbackIndicatorLine = new javax.swing.JPanel();
        feedback_sidebar = new javax.swing.JButton();
        ProfilePanel = new javax.swing.JPanel();
        ProfileIndicatorLine = new javax.swing.JPanel();
        profile_sidebar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        logout_sidebar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(170, 540));
        setMinimumSize(new java.awt.Dimension(170, 540));
        setPreferredSize(new java.awt.Dimension(170, 540));
        setLayout(new java.awt.GridBagLayout());

        DashboardPanel.setBackground(new java.awt.Color(255, 255, 255));
        DashboardPanel.setMaximumSize(new java.awt.Dimension(170, 48));
        DashboardPanel.setMinimumSize(new java.awt.Dimension(170, 48));
        DashboardPanel.setPreferredSize(new java.awt.Dimension(170, 48));
        DashboardPanel.setLayout(new java.awt.BorderLayout());

        DashboardIndicatorLine.setBackground(new java.awt.Color(19, 85, 227));
        DashboardIndicatorLine.setMaximumSize(new java.awt.Dimension(4, 48));
        DashboardIndicatorLine.setMinimumSize(new java.awt.Dimension(4, 48));
        DashboardIndicatorLine.setPreferredSize(new java.awt.Dimension(4, 48));

        javax.swing.GroupLayout DashboardIndicatorLineLayout = new javax.swing.GroupLayout(DashboardIndicatorLine);
        DashboardIndicatorLine.setLayout(DashboardIndicatorLineLayout);
        DashboardIndicatorLineLayout.setHorizontalGroup(
            DashboardIndicatorLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        DashboardIndicatorLineLayout.setVerticalGroup(
            DashboardIndicatorLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        DashboardPanel.add(DashboardIndicatorLine, java.awt.BorderLayout.WEST);

        dashboard_sidebar.setBackground(new java.awt.Color(215, 236, 255));
        dashboard_sidebar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        dashboard_sidebar.setForeground(new java.awt.Color(66, 84, 167));
        dashboard_sidebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dashboardSelected.png"))); // NOI18N
        dashboard_sidebar.setText("Dashboard");
        dashboard_sidebar.setToolTipText("Dashboard");
        dashboard_sidebar.setBorder(null);
        dashboard_sidebar.setBorderPainted(false);
        dashboard_sidebar.setContentAreaFilled(false);
        dashboard_sidebar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboard_sidebar.setIconTextGap(15);
        dashboard_sidebar.setMargin(new java.awt.Insets(10, 14, 10, 14));
        dashboard_sidebar.setMaximumSize(new java.awt.Dimension(166, 48));
        dashboard_sidebar.setMinimumSize(new java.awt.Dimension(166, 48));
        dashboard_sidebar.setName(""); // NOI18N
        dashboard_sidebar.setOpaque(true);
        dashboard_sidebar.setPreferredSize(new java.awt.Dimension(166, 48));
        dashboard_sidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboard_sidebarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboard_sidebarMouseExited(evt);
            }
        });
        dashboard_sidebar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboard_sidebarActionPerformed(evt);
            }
        });
        DashboardPanel.add(dashboard_sidebar, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 0, 0, 0);
        add(DashboardPanel, gridBagConstraints);

        ClassPanel.setBackground(new java.awt.Color(255, 255, 255));
        ClassPanel.setMaximumSize(new java.awt.Dimension(162, 48));
        ClassPanel.setLayout(new java.awt.BorderLayout());

        ClassIndicatorLine.setBackground(new java.awt.Color(19, 85, 227));
        ClassIndicatorLine.setMaximumSize(new java.awt.Dimension(4, 48));
        ClassIndicatorLine.setMinimumSize(new java.awt.Dimension(4, 48));

        javax.swing.GroupLayout ClassIndicatorLineLayout = new javax.swing.GroupLayout(ClassIndicatorLine);
        ClassIndicatorLine.setLayout(ClassIndicatorLineLayout);
        ClassIndicatorLineLayout.setHorizontalGroup(
            ClassIndicatorLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ClassIndicatorLineLayout.setVerticalGroup(
            ClassIndicatorLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        ClassPanel.add(ClassIndicatorLine, java.awt.BorderLayout.WEST);

        class_sidebar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        class_sidebar.setForeground(new java.awt.Color(180, 180, 180));
        class_sidebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ClassIcon.png"))); // NOI18N
        class_sidebar.setText("Class         ");
        class_sidebar.setToolTipText("Class");
        class_sidebar.setBorder(null);
        class_sidebar.setBorderPainted(false);
        class_sidebar.setContentAreaFilled(false);
        class_sidebar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        class_sidebar.setIconTextGap(15);
        class_sidebar.setMargin(new java.awt.Insets(10, 14, 10, 14));
        class_sidebar.setMaximumSize(new java.awt.Dimension(170, 48));
        class_sidebar.setMinimumSize(new java.awt.Dimension(170, 48));
        class_sidebar.setOpaque(true);
        class_sidebar.setPreferredSize(new java.awt.Dimension(170, 48));
        class_sidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                class_sidebarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                class_sidebarMouseExited(evt);
            }
        });
        class_sidebar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                class_sidebarActionPerformed(evt);
            }
        });
        ClassPanel.add(class_sidebar, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 0, 0, 0);
        add(ClassPanel, gridBagConstraints);

        FeedbackPanel.setBackground(new java.awt.Color(255, 255, 255));
        FeedbackPanel.setMaximumSize(new java.awt.Dimension(162, 48));
        FeedbackPanel.setLayout(new java.awt.BorderLayout());

        FeedbackIndicatorLine.setBackground(new java.awt.Color(19, 85, 227));
        FeedbackIndicatorLine.setMaximumSize(new java.awt.Dimension(4, 48));
        FeedbackIndicatorLine.setMinimumSize(new java.awt.Dimension(4, 48));

        javax.swing.GroupLayout FeedbackIndicatorLineLayout = new javax.swing.GroupLayout(FeedbackIndicatorLine);
        FeedbackIndicatorLine.setLayout(FeedbackIndicatorLineLayout);
        FeedbackIndicatorLineLayout.setHorizontalGroup(
            FeedbackIndicatorLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        FeedbackIndicatorLineLayout.setVerticalGroup(
            FeedbackIndicatorLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        FeedbackPanel.add(FeedbackIndicatorLine, java.awt.BorderLayout.WEST);

        feedback_sidebar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        feedback_sidebar.setForeground(new java.awt.Color(180, 180, 180));
        feedback_sidebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/FeedbackIcon.png"))); // NOI18N
        feedback_sidebar.setText("Feedback   ");
        feedback_sidebar.setToolTipText("Feedback");
        feedback_sidebar.setBorder(null);
        feedback_sidebar.setBorderPainted(false);
        feedback_sidebar.setContentAreaFilled(false);
        feedback_sidebar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        feedback_sidebar.setIconTextGap(15);
        feedback_sidebar.setMargin(new java.awt.Insets(10, 14, 10, 14));
        feedback_sidebar.setMaximumSize(new java.awt.Dimension(170, 48));
        feedback_sidebar.setMinimumSize(new java.awt.Dimension(170, 48));
        feedback_sidebar.setOpaque(true);
        feedback_sidebar.setPreferredSize(new java.awt.Dimension(170, 48));
        feedback_sidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                feedback_sidebarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                feedback_sidebarMouseExited(evt);
            }
        });
        feedback_sidebar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedback_sidebarActionPerformed(evt);
            }
        });
        FeedbackPanel.add(feedback_sidebar, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 0, 0, 0);
        add(FeedbackPanel, gridBagConstraints);

        ProfilePanel.setBackground(new java.awt.Color(255, 255, 255));
        ProfilePanel.setMaximumSize(new java.awt.Dimension(162, 48));
        ProfilePanel.setLayout(new java.awt.BorderLayout());

        ProfileIndicatorLine.setBackground(new java.awt.Color(19, 85, 227));
        ProfileIndicatorLine.setMaximumSize(new java.awt.Dimension(4, 48));
        ProfileIndicatorLine.setMinimumSize(new java.awt.Dimension(4, 48));

        javax.swing.GroupLayout ProfileIndicatorLineLayout = new javax.swing.GroupLayout(ProfileIndicatorLine);
        ProfileIndicatorLine.setLayout(ProfileIndicatorLineLayout);
        ProfileIndicatorLineLayout.setHorizontalGroup(
            ProfileIndicatorLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ProfileIndicatorLineLayout.setVerticalGroup(
            ProfileIndicatorLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        ProfilePanel.add(ProfileIndicatorLine, java.awt.BorderLayout.WEST);

        profile_sidebar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        profile_sidebar.setForeground(new java.awt.Color(180, 180, 180));
        profile_sidebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ProfileIcon.png"))); // NOI18N
        profile_sidebar.setText("Profile        ");
        profile_sidebar.setToolTipText("Profile");
        profile_sidebar.setBorder(null);
        profile_sidebar.setBorderPainted(false);
        profile_sidebar.setContentAreaFilled(false);
        profile_sidebar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profile_sidebar.setIconTextGap(15);
        profile_sidebar.setMargin(new java.awt.Insets(10, 14, 10, 14));
        profile_sidebar.setMaximumSize(new java.awt.Dimension(170, 48));
        profile_sidebar.setMinimumSize(new java.awt.Dimension(170, 48));
        profile_sidebar.setOpaque(true);
        profile_sidebar.setPreferredSize(new java.awt.Dimension(170, 48));
        profile_sidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profile_sidebarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profile_sidebarMouseExited(evt);
            }
        });
        profile_sidebar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profile_sidebarActionPerformed(evt);
            }
        });
        ProfilePanel.add(profile_sidebar, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 0, 0, 0);
        add(ProfilePanel, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 160;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(165, 0, 0, 0);
        add(jSeparator1, gridBagConstraints);

        logout_sidebar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        logout_sidebar.setBackground(new java.awt.Color(255, 255, 255));
        logout_sidebar.setForeground(new java.awt.Color(255, 51, 51));
        logout_sidebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/LogoutIcon.png"))); // NOI18N
        logout_sidebar.setText("Logout     ");
        logout_sidebar.setToolTipText("Logout");
        logout_sidebar.setBorder(null);
        logout_sidebar.setBorderPainted(false);
        logout_sidebar.setContentAreaFilled(false);
        logout_sidebar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout_sidebar.setIconTextGap(15);
        logout_sidebar.setMargin(new java.awt.Insets(10, 14, 10, 14));
        logout_sidebar.setMaximumSize(new java.awt.Dimension(162, 48));
        logout_sidebar.setMinimumSize(new java.awt.Dimension(162, 48));
        logout_sidebar.setOpaque(true);
        logout_sidebar.setPreferredSize(new java.awt.Dimension(162, 48));
        logout_sidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout_sidebarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout_sidebarMouseExited(evt);
            }
        });
        logout_sidebar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_sidebarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = -9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 0, 0);
        add(logout_sidebar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void dashboard_sidebarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboard_sidebarActionPerformed
        mainFrame.showPage("Dashboard");
        selectButton(dashboard_sidebar,"/icons/DashboardSelected.png", DashboardIndicatorLine);
        selected_btn = "Dashboard";
    }//GEN-LAST:event_dashboard_sidebarActionPerformed

    private void class_sidebarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_class_sidebarActionPerformed
        mainFrame.showPage("Class");
        selectButton(class_sidebar, "/icons/ClassSelected.png", ClassIndicatorLine);
        selected_btn = "Class";
    }//GEN-LAST:event_class_sidebarActionPerformed

    private void feedback_sidebarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedback_sidebarActionPerformed
        mainFrame.showPage("View Feedback");
        selectButton(feedback_sidebar, "/icons/FeedbackSelected.png", FeedbackIndicatorLine);
        selected_btn = "Feedback";
    }//GEN-LAST:event_feedback_sidebarActionPerformed

    private void logout_sidebarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_sidebarActionPerformed
        LoginFrame login = new LoginFrame();
        login.setVisible(true);
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose(); 
        }
    }//GEN-LAST:event_logout_sidebarActionPerformed

    private void logout_sidebarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_sidebarMouseEntered
        logout_sidebar.setForeground(new java.awt.Color(255, 102, 102));
        logout_sidebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/LogoutSelected.png")));
    }//GEN-LAST:event_logout_sidebarMouseEntered

    private void logout_sidebarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_sidebarMouseExited
        logout_sidebar.setForeground(new java.awt.Color(255,51,51));
        logout_sidebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/LogoutIcon.png")));
    }//GEN-LAST:event_logout_sidebarMouseExited

    private void dashboard_sidebarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_sidebarMouseEntered
        if ("Dashboard".equals(selected_btn)){
            return;
        }
        hoverButton(dashboard_sidebar,"/icons/DashboardSelected.png");
    }//GEN-LAST:event_dashboard_sidebarMouseEntered

    private void class_sidebarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_class_sidebarMouseExited
        if ("Class".equals(selected_btn)){
            return;
        }
        stopHoverButton(class_sidebar,"/icons/ClassIcon.png");
    }//GEN-LAST:event_class_sidebarMouseExited

    private void dashboard_sidebarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_sidebarMouseExited
        if ("Dashboard".equals(selected_btn)){
            return;
        }
        stopHoverButton(dashboard_sidebar,"/icons/DashboardIcon.png");
    }//GEN-LAST:event_dashboard_sidebarMouseExited

    private void class_sidebarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_class_sidebarMouseEntered
        if ("Class".equals(selected_btn)){
            return;
        }
        hoverButton(class_sidebar,"/icons/ClassSelected.png");
    }//GEN-LAST:event_class_sidebarMouseEntered

    private void feedback_sidebarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedback_sidebarMouseEntered
        if ("Feedback".equals(selected_btn)){
            return;
        }
        hoverButton(feedback_sidebar,"/icons/FeedbackSelected.png");
    }//GEN-LAST:event_feedback_sidebarMouseEntered

    private void feedback_sidebarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedback_sidebarMouseExited
        if ("Feedback".equals(selected_btn)){
            return;
        }
        stopHoverButton(feedback_sidebar,"/icons/FeedbackIcon.png");
    }//GEN-LAST:event_feedback_sidebarMouseExited

    private void profile_sidebarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_sidebarMouseEntered
        if ("Profile".equals(selected_btn)){
            return;
        }
        hoverButton(profile_sidebar,"/icons/ProfileSelected.png");
    }//GEN-LAST:event_profile_sidebarMouseEntered

    private void profile_sidebarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_sidebarMouseExited
        if ("Profile".equals(selected_btn)){
            return;
        }
        stopHoverButton(profile_sidebar,"/icons/ProfileIcon.png");
    }//GEN-LAST:event_profile_sidebarMouseExited

    private void profile_sidebarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_sidebarActionPerformed
        mainFrame.showPage("Profile");
        selectButton(profile_sidebar, "/icons/ProfileSelected.png", ProfileIndicatorLine);
        selected_btn = "Profile";
    }//GEN-LAST:event_profile_sidebarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ClassIndicatorLine;
    private javax.swing.JPanel ClassPanel;
    private javax.swing.JPanel DashboardIndicatorLine;
    private javax.swing.JPanel DashboardPanel;
    private javax.swing.JPanel FeedbackIndicatorLine;
    private javax.swing.JPanel FeedbackPanel;
    private javax.swing.JPanel ProfileIndicatorLine;
    private javax.swing.JPanel ProfilePanel;
    private javax.swing.JButton class_sidebar;
    private javax.swing.JButton dashboard_sidebar;
    private javax.swing.JButton feedback_sidebar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logout_sidebar;
    private javax.swing.JButton profile_sidebar;
    // End of variables declaration//GEN-END:variables
}
